/*
Trnsfrm english suffixes into fonetic letters, such
as ing = ŋ » e.g. driving » drivŋ
*/
// makiŋ t wrds shorter wi mor alphabet, i.e. ss = ß
// 

/*
Symbols available
- æ
"!@#$%¨&*()_+/*- `{}^:><|?
¬¹²³£¢¬{[]}\§ª´~º.·─ˇ°/?°®ŧ←↓→øþ´łĸˀħŋđðßæ«»©“”nµ─n·̣
¬½¾¼⅜¨⅞™±°¿˛¯`^º˙̣  ÷× <˘/?°®Ŧ¥↑ıØÞ˝Ł&̛ĦŊªÐ§Æ<>©‘’Nµ
 
available: µ

# DIGRAPH to Letter

¨ means i after the vowel, i.e. ai = ä
1. ai = ä » x|-e.g. available = avälable | 107
2. ei = ë » x| 26
3. oi = ö » x| 19
4. ui = ü » x| 52
5. ee = ē » x|between = betwēn | 106
6. oo = ō » x|hood = hōd | 94
7. uu = ū » x|vacuum = vacūm | 1
au = â
ou = ô x|
iu

ęąǫų


8. ss = ß x|» assault = aßault | 158
10. ng = ŋ x|» authoring = authoriŋ, along = aloµ | 368
11. th = ŧ x|» authoring = auŧoring | 270
12. ch = ħ x|» champion = ħampion | 173
13. ed = ð x|» balanced = balancð n Education = Ðucation | 183 
15. at = @ x|» attitude = @itude | 496
17. ion = ¬ x|» evaluation = evalu@¬ | 313
18. til = ~ x|» still = s~ | 7
22. st = § x| 452
23. ry = ỷ x| 115
24. ty = ¥ x|» ability = abili¥ | 127
25. ae = æ x|
al = ø x| 445
nt = £ x|» want = wa¢ wa | 503 
nd = đ x| 243
ct = ¢ x| 283

tic



igh 
oa
oo
ar
or
ur


ear
air
ure
er 

 
# TRIGRAPHS
1. nth | 5
2. sch | 10
3. scr | 8
4. shr | 2
5. spl | 5
6. spr | 11
7. squ | 3
8. str | 91
9. thr | 15

# VOWEL DIGRAPH
. au
. aw
. ay
. ea
. eu
. ew
. ey
. ie
. oo
. ou
. ow
. oy

BLEND

vowel: 
      x,x,x,x,x,x,-,x,-,x,x,x,-,x,x,x,?,x,-,?,
1.a » ɓ,ƈ,ɗ,ƒ,ɠ,ɦ, ,ƙ, ,ɱ,ɲ,ƥ,ʠ,ɼ,ʂ,ƭ,ʋ,ⱳ, ,ỷ,ȥ
      x,x,x,?,-,x,-,x,x,x,x,-,-,x,x,x,x,x,-,x,x
2.e » ḅ,c,ḍ,þ, ,ḥ, ,ḳ,ḷ,ṃ,ṇ,1, ,ṛ,ṣ,ṭ,ṿ,ẉ, ,ỵ,ẓ
      x,x,x,x,x,x,?,-,x,x,x,x,-,x,x,x,-,x,x,x,x
3.i » ḃ,ċ,ḋ,ḟ,ġ,ḣ,ȷ, ,ŀ,ṁ,ṅ,ṗ, ,ṙ,ṡ,ṫ, ,ẇ,ẋ,ẏ,ż
      ̣
4.o » ḇ,©,ḏ,£, ,ẖ, ,ḵ,ḻ, ,ṉ, , ,ṟ, ,ṯ, , , , ,ẕ
      
5.u » đĸ
º
6.y » -,-,-,-,-,-,-,-,ł
consonant: 
1.b,
2.c,
3.d,
4.f,
5.g,
6.h,
7.j,
8.k,
9.l,
10.m,
11.n,
12.p,
13.q,
14.r,
15.s,
16.t,
17.v,
18.w,
19.x,
20.y,
21.z

*/

/*
SUFFIXES
1. anti » 
2. de
3. dis
4. en, im
5. fore
6. in, im
7. 
8.
9.
10.
11.
12.
13.
14.
15.
16.
17.
18.
19.
20.

*/



const text = `

Of course that’s also what a lot of gamification platforms specialize in: adding PBLs into various products in a scalable manner. And as a result, many people who are less informed but curious about gamification start to believe that the sum total of gamification methodology and philosophy is merely the process of adding points, badges, and leaderboards to products. Justifiably, this leads them to believe that gamification is a shallow fad and not very impactful.

This has also generated a backlash from the game development community, as they claim that gamification is a bastardization of the true essence intrinsic to good gaming. And who can blame them? Foursquare seems to be nothing more than points, badges, and leaderboards based on going to places, while Nike+ seems to be the same thing based on running. Is this as deep as gamification goes?

Of course, points, badges, and leaderboards do have a place in game design. That’s why you see them in so many different games. They have the ability to motivate behavior and push people towards certain actions. But gamification is so much more than PBLs. Many gamification professionals are only familiar with how to implement PBL mechanics and even though these do create value, most of them completely miss the point of engaging the user. It is not unusual for users to feel insulted by shallow shell mechanics.

If you ask any gamer what makes a game fun, they will not tell you that it is because of the PBLs. They play it because there are elements of strategy and great ways to spend time with friends, or they want to challenge themselves to overcome difficult obstacles. The points and badges are often an added bonus that’s nice to have depending on the context. This is the difference between extrinsic motivation, where you are engaged because of a goal or reward, and intrinsic motivation, where the activity itself is fun and exciting, with or without a reward. We’ll dive deeper into these distinctions in Chapter 13 on Left Brain vs Right Brain Motivations.

<h3>A Trojan Horse without Greek Soldiers</h3>

Generic game mechanics and poorly constructed game elements such as levels, boss fights, or quests often fall into the same hole as PBLs. Simply put, applying traditional “game elements” ubiquitous in popular gameplay without diving deeper into user motivation contributes to shallow user experience: it’s all flash and no bang. An almost humorous example of this is when people I meet call something a “quest” instead of a “task” thinking that this automatically makes the same original actions fun and engaging. Sure, having a playful attitude can make a big difference, but it only goes so far, especially when your customers and employees may already distrust your motives.

<b>The truth is, simply incorporating game mechanics and game elements does not make a game fun.</b>

Games aren’t necessarily fun because of high quality graphics or flashy animations either. There are many unpopular, poor-selling games with state-of-the-art 3D high- resolution graphics. There are also games with very basic graphics such as Minecraft, or even no graphics, such as the purely text-based multi-user dungeon games (MUDs), that have large communities of players addicted to them. Clearly, there are more to games than “meets the eye.”

Unfortunately, a lot of people who work in gamification incorrectly think that applying game mechanics like points, badges, and leaderboards – elements that you can also find in boring and unsuccessful games - will automatically make the product or experience fun and engaging. Unfortunately, it’s not just what game elements you put in - it’s how, when, and most importantly, why these game elements appear.

It would be foolish for a modern army commander to say, “Hey! The Greeks sent a big wooden horse to the Trojans and won the war. Lets send our enemies a big wooden horse too!” In this case, he clearly doesn’t understand the true design behind the Trojan Horse, but he only copied the outer shell of it. Instead, it would be much more effective if he created a virus that pretended to be a normal file to corrupt enemy computers. Learn from the design; don’t copy the shell.

<h3>The Threat and Opportunities in Gamification</h3>

Even though gamification has become accepted in the mainstream, poorly designed applications threaten its long-term viability and impact development. I am genuinely afraid that in a few years, companies will look at gamification and say, “Hey, we tried the points stuff and it didn’t work out. I guess gamification was just a short-term fad.”

<i>That would be a huge loss for the world.</i>

Based on my years of research, observation, and design in gamification, I am a hundred percent certain that good gamification design can unlock tremendous potential and improve many lives in the process. There are hundreds of case studies that illustrate this also. And so it is my job (and hopefully yours one day) to continue protecting and innovating the core essence and the promise of gamification.

In the long run, the term “gamification” might actually fade and eventually disappear. Currently, no one describes a website’s design as being “so Web 2.0!” Gamification may just become the normal way we design, implement, and interact with the world around us. It’s my hope that the principles that optimize for human motivation becomes the standard for good design across the board.

Fortunately, there are enough good gamification examples that continue to show how thoughtful design can improve core business metrics and inspire new ways of thinking and execution. Besides the 90+ Gamification Case Studies listed on my site, as mentioned in the last chapter, it is interesting to note that some of the best historical examples of gamification, such as eBay or Woot.com, have not been categorized as gamification by most people in the industry. There are dozens, if not hundreds of companies that became extremely successful because, regardless of what it was called, they applied great game mechanics and gameplay dynamics to their processes. Some of these examples are illustrated in the following chapters.

Because of these success stories, I believe that gamification will continue to evolve and meet real needs if practitioners and the general gamification community also evolve in their understanding of its principles and practice.

So if “game mechanics” alone are not the true reason why games are so engaging and sometimes addictive, then what is?

<h3>The Story of the Good Designer vs. Bad Designer</h3>
To understand the core of good gamification design, let’s start with an example of how a bad game designer might design a game.

In designing a game, a bad designer might start off thinking, “Okay, what popular game mechanics and game elements should I use? Well, of course we need monsters in the game. We also need swords so where should I place those? How about crops that friends can fertilize? What about some birds that show a lot of attitude? I’m sure people will love it!”

As you can see from the exaggerated depiction above, a game might have all the “right game elements” but still be incredibly boring or stupid if they do not focus on their users’ motivations first. It is worth remembering that every single game in the market has what we call game mechanics and game elements. However, most are still boring and are financial losers. Only a few well-designed games become engaging and even addictive. Are you designing your experience to be the failing game or the successful game? How would you know?

So let us look at how a good game designer might tackle the problem. Instead of starting with what game elements and game mechanics to use, the good game designer may begin by thinking, “Okay, how do I want my users to feel ? Do I want them to feel inspired? Do I want them to feel proud? Should they be scared? Anxious? What’s my goal for their intended experience?

Once the designer understands how she wants her users to feel, then she begins to think, “Okay, what kind of game elements and mechanics can help me accomplish my goals of ensuring players feel this way.” The solution may lie in swords, plants, or perhaps word puzzles, but the whole point here is that game elements are just a means to an end, instead of an end in itself. Game elements are simply there to push and pull on their users’ behavioral core drives.

As a result, in order to further explore, systemize, and scale methods of combining game mechanics with our motivational core drives, in 2012 I decided to share my original gamification design framework called Octalysis to the world. The Octalysis Framework embodies my life’s work, and the majority of this book will be about how to use Octalysis to design experiences that are fun, engaging, and rewarding.






`



const abbreviation = {
  // ·ment = mt 
// ing = ng
// cal = al
'for': 'f',
'you': 'u',
'your': 'ur',
'yours': 'urs',
'want': 'ⱳ£',
'would': 'wôld',
'have': 'ɦṿ',
'having': 'ɦvŋ',
'here': 'ḥṛ',
'just': 'ju§',
'unlike': 'unŀḳ',
'unlikely': 'unŀḳł',
'back': 'ɓk',
'really': 'ṛøł',
'right': 'ṙght',
'rights': 'ṙghts',
'feel': 'fēl',
'great': 'gṛ@',
'keep': 'kēp',
'keeps': 'kēps',
'keeping': 'kēṗŋ',
'happen': 'ɦpn',
'last': 'la§',
'recovery': 'ṛcoṿỷ',
'overcome': 'oṿrcoṃ',
'question': 'que§¬', 'questions': 'que§¬s',
'read': 'ṛad',
'family': 'ƒṁł',
'maybe': 'ɱyḅ',
// A- \\
'are': 'r',
'ability': 'aḃŀ¥',
'able': 'abḷ',
'abortion': 'abort¬',
'about': 'abôt',

'above': 'aboṿ',
'abroad': 'abrd',
'absence': 'abṣnc',
'absolute': 'absluṭ',
'absolutely': 'absluṭł',
'abstract': 'ab§ɼ¢',
'abuse': 'abuṣ',
'academic': 'aƈḍṁk',
'accent': 'ac£',
'acceptable': 'acpƭbḷ',
'acceptance': 'acpƭnc',
'access': 'acß',
'accessible': 'aceßibḷ',
'accident': 'acċḍ£',
'accomplishment': 'accompŀshṃ£',
'according': 'accorḍŋ',
'account': 'acô£',
'accountability': 'acônƭḃŀ¥',
'accounting': 'acônṫŋ',
'accuracy': 'acɼcy',
'accurate': 'acr@',
'accurately': 'acr@ł',
'accusation': 'acs@t¬',
'achievement': 'acḣṿṃ£',
'acid': 'aċd',
'across': 'acroß',
'action': 'a¢¬',
'active': 'acṫiṿ',
'actively': 'acṫṿł',
'activist': 'acṫvi§',
'activity': 'acṫvi¥',
'actor': 'a¢or', 
'actress': 'a¢ṛß',
'actual': 'a¢ø',
'actually': 'a¢øł',
'added': 'adð',
'addition': 'adḋt¬',
'additional': 'adḋt¬ø',
'address': 'adṛß',
'adequate': 'aḍq@e',
'adjustment': 'adj§ṃ£',
'admission': 'adṁß¬',
'adolescent': 'adḷsc£',
'adapting': 'adapṫŋ',
'adopting': 'adopṫŋ',
'adoption': 'adopt¬',
'adult': 'adlt',
'advance': 'advnc',
'advanced': 'advncð',
'advantage': 'advnƭg',
'adventure': 'adṿ£uṛ',
'advertising': 'adṿrṫṡŋ',
'advice': 'advc',
'adviser': 'adviṣr',
'advocate': 'advc@e',
'aesthetic': 'æ§ḥṫc',
'affair': 'afär',
'afraid': 'afäd',
'African': 'Afṙƈn',
'African-American': 'Afṙƈn-Aṃṙƈn',
'after': 'afṭr',
'afternoon': 'afṭrnōn',
'afterward': 'afṭrⱳrd',
'again': 'agän',
'against': 'agän§',
'age': 'ag',
'agency': 'agnc',
'agenda': 'agnɗ',
'agent': 'age£',
'aggression': 'agṛß¬',
'aggressive': 'agṛßiṿ',
'agreement': 'agrēṃ£',
'agricultural': 'agṙculturø',
'agriculture': 'agṙcultuṛ',
'ahead': 'aḥad',
'aircraft': 'ärcɼft',
'airline': 'ärŀṇ',
'airplane': 'ärplaṇ',
'airport': 'ärprt',
'alarm': 'ørm',
'album': 'øbm',
'alcohol': 'øcl',
'alike': 'øiḳ',
'alive': 'øiṿ',
'all': 'ø',
'allegation': 'øḷg@t¬',
'alleged': 'øḷgð',
'allegedly': 'øḷgðł',
'alley': 'øey',
'alliance': 'øŀanc',
'ally': 'øy',
'almost': 'øm§',
'alone': 'øoṇ',
'along': 'øŋ',
'alongside': 'øŋṡḍ',
'already': 'øṛdy',
'also': 'øs',
'alternative': 'øt',
'although': 'øŧôgh',
'altogether': 'øtogtḥr',
'always': 'øⱳys',
'amazing': 'aɱżŋ',
'ambassador': 'amɓʂdr',
'ambition': 'amḃt¬',
'ambitious': 'amḃṫôs',
'amendment': 'aṃđṃ£',
'American': 'Aṃṙƈn',
'amid': 'aṁd',
'amount': 'amô£',
'analysis': 'aɲlyṡs',
'analyst': 'aɲly§',
'ancestor': 'anc§r',
'ancient': 'anċe£',
'and': 'n',
'angel': 'aŋel',
'anger': 'aŋer',
'angle': 'aŋḷ',
'animal': 'aṅɱl',
'anniversary': 'anṅṿrʂỷ',
'announcement': 'anoncṃ£',
'annual': 'annuø',
'annually': 'annuøł',
'anonymous': 'anonymôs',
'another': 'anotḥr',
'answer': 'ansẉr',
'anxiety': 'anẋe¥',
'anxious': 'anẋôs',
'anybody': 'anybdy',
'anymore': 'anymoṛ',
'anything': 'anyŧiŋ',
'anyway': 'anyⱳy',
'anywhere': 'anywḥṛ',
'apart': 'aƥrt',
'apartment': 'apt',
'apology': 'aplgy',
'apparent': 'aƥṛ£',
'apparently': 'aƥṛ£ł',
'appeal': 'appeø',
'appearance': 'apɼnc',
'apple': 'apḷ',
'application': 'appŀc@¬',
'appointment': 'appö£ṃ£',
'appreciation': 'appṛċ@¬',
'approach': 'aprħ',
'appropriate': 'apropṙ@e',
'approval': 'approvø',
'approximately': 'aprẋm@eł',
'architect': 'arcḣṭ¢',
'architecture': 'arcḣṭ¢tuṛ',
'arena': 'aṛɲ',
'argument': 'arg',
'arm': 'arm',
'armed': 'armð',
'army': 'army',
'around': 'arôđ',
'arrangement': 'aɼŋṃ£',
'array': 'aɼy',
'arrest': 'aṛ§',
'arrival': 'arṙvø',
'article': 'arṫcḷ',
'artifact': 'arṫƒ¢',
'artificial': 'arṫḟċø',
'artist': 'arṫ§',
'artistic': 'arṫsṫc',
'aside': 'aṡḍ',
'asleep': 'aslēp',
'aspect': 'asp¢',
'ass': 'aß',
'assault': 'aʂlt',
'assembly': 'aṣmbly',
'assessment': 'aṣßṃ£',
'asset': 'aṣt',
'assignment': 'aßignṃ£',
'assistance': 'aßisƭnc',
'assistant': 'aßisƭ£',
'associate': 'aßoċaṭ',
'associated': 'aßoċ@ð',
'association': 'aßoċ@¬',
'assumption': 'aßumpt¬',
'astronomer': 'a§ronoṃr',
'at': '@',
'athlete': '@hḷṭ',
'athletic': '@hḷṫc',
'atmosphere': '@mospḥṛ',
'atop': '@op',
'attack': '@ck',
'attempt': '@ṭmpt',
'attendance': '@ṭðanc',
'attention': '@ṭ£¬',
'attitude': '@ṫuḍ', 'attitudes': '@ṫuḍs',
'attorney': '@orṇy',
'attraction': '@ɼ¢¬',
'attractive': '@ɼcṫṿ',
'auction': 'ă¢¬',
'audience': 'ăḋence',
'author': 'ăŧor',
'authority': 'ăŧoṙ¥',
'automatic': 'ătoɱṫc',
'automobile': 'ătomḃḷ',
'autonomy': 'ătonmy',
'availability': 'avälḃŀ¥',
'available': 'avälbḷ',
'average': 'aṿg',
'award': 'aⱳrd',
'aware': 'aⱳṛ',
'awareness': 'aⱳṛṇß',
'awful': 'awfl',



'away': 'aⱳy',
'acknowledge': 'acknowḷdg',
'advantage': 'advƭg', 'advantages': 'advƭgs',
'accelerate': 'aceḷɼṭ',
'adjective': 'adj',
'accommodation': 'acomɗt¬',

'administration': 'adṁ§r@¬',
'administrative': 'adṁ§raṫṿ',
'administrator': 'adṁ§r@or',
'agriculture': 'agṙc',
'agricultural': 'agṙcɼl',
'association': 'aßoc',
'associate': 'aßoċaṭ', 'associates': 'aßoċaṭs',
'authentication': 'ăŧ',
'authenticate': 'ăŧƈṭ', 'authenticates': 'ăŧƈṭs',
'authority': 'auŧoṙ¥', 'authorities': 'auŧoṙṫes',
'argument': 'arg', 'arguments': 'args',
'assumption': 'aßumpt¬', 'assumptions': 'aßumpt¬s',
'avenue': 'aṿ',
// B- \\
'become': 'ḅcoṃ', 'becomes': 'ḅcoṃs',
'became': 'ḅƈṃ', 
'bring': 'bṙŋ', 'brings': 'bṙŋs',
'believe': 'ḅŀṿ', 'beŀeves': 'ḅŀṿs',
'bankruptcy': 'ɓnkr·',
'bureaucracy': 'buṛaucɼcy',


'baby': 'ɓb',
'back': 'ɓk',
'background': 'ɓckgrôđ',
'backyard': 'ɓkyard',
'bacteria': 'ɓ¢eṙa',
'bad': 'ɓd',
'badly': 'ɓdly',
'bag': 'ɓg',
'balance': 'ɓlanc',
'balanced': 'ɓlncð',
'ball': 'ɓl',
'balloon': 'ɓlōn',
'ballot': 'ɓllot',
'ban': 'ɓn',
'banana': 'ɓɲɲ',
'band': 'ɓđ',
'bank': 'ɓnk',
'banker': 'ɓnḳr',
'banking': 'ɓnkiŋ',
'bankruptcy': 'ɓnkruptcy',
'bar': 'ɓr',
'bare': 'ɓṛ',
'barely': 'ɓṛł',
'barn': 'ɓrn',
'barrel': 'ɓṛl',
'barrier': 'ɓṙer',
'base': 'ɓṣ',
'baseball': 'ɓṣɓl',
'basement': 'ɓṣṃ£',
'basic': 'ɓṡc',
'basically': 'ɓṡƈł',
'basis': 'ɓṡs',
'basket': 'ɓsḳt',
'basketball': 'ɓsḳtɓl',
'bat': 'ɓt',
'bath': 'ɓŧ',
'bathroom': 'ɓŧrōm',
'battery': 'ɓṭỷ',
'battle': 'ɓtḷ',
'bay': 'ɓy',
'be': 'b',
'beach': 'ḅħ',
'beam': 'ḅam',
'bean': 'ḅan',
'bear': 'ḅar',
'beard': 'ḅard',
'beast': 'ḅe§',
'beat': 'ḅ@',
'beautiful': 'ḅauṫful',
'beauty': 'ḅau¥',
'because': 'ḅƈuṣ',
'bed': 'ḅð',
'bedroom': 'ḅðrōm',
'bee': 'bē',
'beef': 'ḅf',
'beer': 'ḅr',
'before': 'ḅfoṛ',
'beginning': 'ḅġṅŋ',
'behalf': 'ḅɦlf',
'behave': 'ḅɦṿ', 'behaves': 'ḅɦṿs',
'behavior': 'ḅɦvior', 'behaviors': 'ḅɦviors',
'behaving': 'ḅɦviŋ', 'behavings': 'ḅɦviŋs',
'behavioral': 'ḅɦviorø',
'behind': 'ḅḣđ',
'being': 'ḅiŋ',
'belief': 'ḅŀef',
'bell': 'ḅl',
'belly': 'ḅł',
'below': 'ḅ',
'below': 'ḅlow',
'belt': 'ḅlt',
'bench': 'ḅnħ',
'beneath': 'ḅṇaŧ',
'benefit': 'ḅṇḟt',
'beside': 'ḅṡḍ',
'besides': 'ḅṡḍs',
'best': 'ḅ§',
'bet': 'ḅt',
'better': 'ḅtṭr',
'between': 'ḅtwēn',
'beyond': 'ḅyođ',
'bias': 'ḃas',
'Bible': 'Ḃbḷ',
'bicycle': 'ḃcycḷ',
'bid': 'ḃd',
'big': 'ḃg',
'bike': 'ḃḳ',
'bill': 'ḃll',
'billion': 'ḃll¬',
'biography': 'ḃogɼphy',
'biological': 'ḃoloġƈl',
'biology': 'ḃology',
'bird': 'ḃrd',
'birth': 'ḃrŧ',
'birthday': 'ḃrŧɗy',
'bishop': 'ḃshop',
'bit': 'ḃt',
'bite': 'ḃṭ',
'bitter': 'ḃtṭr',
'black': 'black',
'blade': 'blaḍ',
'blank': 'blank',
'blanket': 'blanḳt',
'blast': 'bla§',
'blessing': 'bḷßiŋ',
'blind': 'bŀđ',
'block': 'block',
'blond': 'blođ',
'blood': 'blōd',
'bloody': 'blōdy',
'blow': 'blow',
'blue': 'blue',
'board': 'board',
'boat': 'bo@',
'body': 'body',
'bold': 'bold',
'bolt': 'bolt',
'bomb': 'bomb',
'bombing': 'bomḃŋ',
'bond': 'bođ',
'bone': 'boṇ',
'bonus': 'bonus',
'book': 'bōk',
'boom': 'bōm',
'boot': 'bōt',
'booth': 'bōŧ',
'border': 'borḍr',
'boring': 'boṙŋ',
'boss': 'boß',
'both': 'boŧ',
'bottle': 'botḷ',
'bottom': 'bottom',
'boundary': 'bônɗỷ',
'bow': 'bow',
'bowl': 'bowl',
'box': 'box',
'boy': 'boy',
'boyfriend': 'boyfṙeđ',
'brain': 'bɼin',
'brake': 'bɼḳ',
'branch': 'bɼnħ',
'brand': 'bɼđ',
'brave': 'bɼṿ',
'bread': 'bṛad',
'break': 'bṛak',
'breakfast': 'bṛakƒ§',
'breast': 'bṛa§',
'breath': 'bṛaŧ',
'breathing': 'bṛaŧiŋ',
'breeze': 'brēẓ',
'brick': 'bṙck',
'bride': 'bṙḍ',
'bridge': 'bṙdge',
'brief': 'bṙef',
'briefly': 'bṙefł',
'bright': 'bṙght',
'brilliant': 'bṙlŀa£',
'British': 'Bṙṫsh',
'broad': 'broad',
'broadcast': 'broadƈ§',
'broken': 'broḳn',
'broker': 'broḳr',
'bronze': 'bronẓ',
'brother': 'bro',
'brothers': 'bros',
'brotherhood': 'brohōd',
'brown': 'brown',
'brush': 'brush',
'brutal': 'brutø',
'bubble': 'bubbḷ',
'buck': 'buck',
'bucket': 'bucḳt',
'buddy': 'buddy',
'budget': 'budget',
'bug': 'bug',
'build': 'büld',
'builder': 'bülḍr',
'building': 'bülḋŋ',
'bulb': 'bulb',
'bulk': 'bulk',
'bull': 'bull',
'bullet': 'bulḷt',
'bunch': 'bunħ',
'burden': 'burḍn',
'bureau': 'buṛau',
'burning': 'burṅŋ',
'bus': 'bus',
'bush': 'bush',
'business': 'ḃz', 'businesses': 'ḃẓs',
'businessman': 'ḃzɱn',
'busy': 'busy',
'but': 'but',
'butt': 'butt',
'butter': 'butṭr',
'butterfly': 'butṭrfly',
'button': 'button',
'buyer': 'buỵr',
'by': 'by',


// C- \\
'could': 'côld',
'country': 'cô£ỷ',
'create': 'cṛaṭ', 'creates': 'cṛaṭs',
'complete': 'cmpḷt', 'completes': 'cmpḷts',
'concept': 'concpt', 'concepts': 'concpts',
'compete': 'compṭ', 'competes': 'compṭs',
'compare': 'cmƥṛ', 'compares': 'cmƥṛs',
'customer': 'cu§omr', 'customers': 'cu§omrs',
'catholic': 'ƈŧoŀc',
'chemistry': 'cḥm',
'chemical': 'cḥmƈl',
'college': 'coḷg',
'clothes': 'cloŧes',
'clothing': 'cloŧiŋ',
'commerce': 'coṃrc',
'commercial': 'coṃrċø',
'community': 'commuṅ¥',
'condominium': 'cođo',
'consolidated': 'consoŀɗtð',
'contract': 'co£ɼ¢',
'correction': 'coṛ¢¬',
'contamination': 'conƭṁ',
'courtroom': 'côrtrōm',
'careful': 'ƈṛful',
'carefully': 'ƈṛfuł',



'cab': 'ƈb',
'cabin': 'ƈḃn',
'cabinet': 'ƈḃṇt',
'cable': 'ƈbḷ',
'cage': 'ƈg',
'cake': 'ƈḳ',
'calculation': 'ƈlcul@¬',
'calendar': 'ƈḷđar',
'call': 'ƈl',
'called': 'ƈlð',
'calm': 'ƈlm',
'camera': 'ƈṃɼ',
'camp': 'ƈmp',
'campaign': 'ƈmƥign',
'campus': 'ƈmpus',
'can': 'ƈn',
'Canadian': 'Ƈɲḋan',
'cancer': 'ƈncer',
'candidate': 'ƈđiɗṭ',
'candle': 'ƈđḷ',
'candy': 'ƈđy',
'canvas': 'ƈnvas',
'cap': 'ƈp',
'capability': 'ƈƥḃŀ¥',
'capable': 'ƈƥbḷ',
'capacity': 'ƈƥċ¥',
'capital': 'ƈṗƭl',
'captain': 'ƈpƭin',
'capture': 'ƈptuṛ',
'car': 'ƈr',
'carbohydrate': 'ƈrbo',
'carbon': 'ƈrbon',
'card': 'ƈrd',
'care': 'ƈṛ',
'career': 'ƈrēr',
'careful': 'ƈṛful',
'carefully': 'ƈṛfuł',
'cargo': 'ƈrgo',
'carpet': 'ƈrpet',
'carrier': 'ƈrṙer',
'carrot': 'ƈrot',
'cart': 'ƈrt',
'cartoon': 'ƈrtōn',
'case': 'ƈṣ',
'cash': 'ƈsh',
'casino': 'ƈṡno',
'cast': 'ƈ§',
'casual': 'ƈsuø',
'casualty': 'ƈsuø¥ ',
'cat': 'ƈt',
'catalog': 'ƈƭlog',
'catch': 'ƈtħ',
'category': 'ƈṭgoỷ',
'cattle': 'ƈttḷ',
'cause': 'ƈuṣ',
'cave': 'ƈṿ',
'ceiling': 'cëŀŋ',
'celebration': 'ceḷbɼt¬',
'celebrity': 'ceḷbṙ¥',
'cell': 'cel',
'cemetery': 'cṃṭỷ',

'center': 'cṭr',
'centre': 'cṭr',
'central': '¢ɼl',
'centralized': '¢ɼŀzð',
'century': 'c£uỷ',
'ceremony': 'cṛmony',
'certain': 'crƭin',
'certainly': 'crƭinł',
'chain': 'cɦin',
'chair': 'cɦir',
'chairman': 'cɦirɱn',
'challenge': 'cɦḷŋe',
'chamber': 'cɦmḅr',
'champion': 'cɦmp',
'championship': 'cɦmpsḣp',
'chance': 'cɦnc',
'change': 'cɦŋg', 'changes': 'cɦŋgs',
'changing': 'cɦŋiŋ',
'channel': 'cɦṇl',
'chaos': 'cɦos',
'chapter': 'cɦpṭr',
'character': 'cɦr',
'characteristic': 'cɦṙsṫc',
'charge': 'cɦrg',
'charity': 'cɦṙ¥',
'charm': 'cɦrm',
'chart': 'cɦrt',
'charter': 'cɦrṭr',
'cheap': 'cḥap',
'check': 'cḥk',
'cheek': 'ħēk',
'cheese': 'ħēṣ',
'chef': 'cḥf',
'chest': 'cḥ§',
'chicken': 'cḣcḳn',
'chief': 'cḣef',
'child': 'cḣld', 'children': 'cḣldṛn',
'childhood': 'cḣldhōd',
'chill': 'cḣl',
'chin': 'cḣn',
'Chinese': 'Cḣṇṣ',
'chip': 'cḣp',
'chocolate': 'ħocolaṭ',
'choice': 'ħöc',
'cholesterol': 'ħoḷsṭrol',
'Christian': 'Chṙsṫan',
'Christianity': 'Chṙsṫaṅ¥',
'Christmas': 'Chṙ§ɱs',
'chronic': 'ħroṅc',
'chunk': 'ħunk',
'church': 'ħurħ',
'cigarette': 'ċɠṛt',
'circle': 'ċrcḷ',
'circuit': 'ċrcüt',
'circumstance': 'ċrcumsƭnc',
'citizen': 'ċṫẓn',
'citizenship': 'ċṫẓnsḣp',
'city': 'ċ¥',
'civic': 'ċvic',
'civil': 'ċvil',
'civilian': 'ċviŀan',
'civilization': 'ċviŀz@¬',
'claim': 'cläm',
'class': 'claß',
'classic': 'claßic',
'classical': 'claßiƈl',
'classroom': 'claßrōm',
'clay': 'clay',
'clean': 'cḷan',
'clear': 'cḷar',
'clearly': 'cḷarł',
'clerk': 'cḷrk',
'client': 'cŀe£',
'cliff': 'cŀf',
'climate': 'cŀɱṭ',
'clinic': 'cŀṅc',
'clinical': 'cŀṅƈl',
'clip': 'cŀp',
'clock': 'clock',
'close': 'cloṣ',
'closed': 'closð',
'closely': 'cloṣł',
'closer': 'cloṣr',
'closest': 'cloṣ§',
'closet': 'cloṣt',
'cloth': 'cloŧ',
'clothes': 'cloŧes',
'clothing': 'cloŧiŋ',
'cloud': 'clôd',
'club': 'club',
'clue': 'clue',
'cluster': 'clusṭr',
'coach': 'coaħ',
'coal': 'coø',
'coalition': 'coaŀt¬',
'coast': 'coa§',
'coastal': 'coa§ø',
'coat': 'co@',
'cocaine': 'coƈiṇ',
'code': 'coḍ',
'coffee': 'coffē',
'cognitive': 'cogṅṫṿ',
'coin': 'cön',
'cold': 'cold',
'collaborate': 'colab', 'collaborates': 'colabs',
'collaboration': 'colabt¬', 'collaborations': 'colabt¬s',
'collapse': 'collapṣ',
'collar': 'collar',
'colleague': 'coḷague',
'collection': 'coḷ¢¬',
'collective': 'coḷcṫṿ',
'collector': 'coḷ¢or',
'colonial': 'coloṅø',
'colony': 'colony',
'color': 'color',
'colorful': 'colorful',
'column': 'column',
'columnist': 'columṅ§',
'combat': 'comɓt',
'combination': 'comḃɲt¬',
'combined': 'comḃnð',
'comedy': 'comðy',
'comfort': 'comfort',
'comfortable': 'comforƭbḷ',
'coming': 'coṁŋ',
'command': 'coɱđ',
'commander': 'coɱđer',
'comment': 'coṃ£',
'commission': 'comṁß¬',
'commissioner': 'coṁß¬er',
'commitment': 'comṁtṃ£', 'commitments': 'comṁtṃ£s',
'commit': 'comṁt', 'commits': 'comṁts',
'committing': 'comṁṫŋ',
'committee': 'comṁttē',
'commodity': 'commoḋ¥',
'common': 'common',
'commonly': 'commonł',
'communication': 'comuṅƈt¬',
'community': 'commuṅ¥',
'companion': 'comƥn¬',
'company': 'comp', 'companies': 'comṗes',
'comparable': 'comƥɼbḷ',
'comparison': 'comƥṙson',
'compelling': 'complŀŋ',
'compensation': 'compenʂt¬',
'competition': 'compt¬', 'competitions': 'compt¬s',
'competitor': 'compṫtor', 'competitors': 'compṫtors',
'competitive': 'compeṫṫṿ',
'competitor': 'compeṫtor',
'complaint': 'complä£',
'complete': 'compḷṭ',
'completely': 'compḷṭł',
'complex': 'compḷx',
'complexity': 'compḷẋ¥',
'compliance': 'compŀanc',
'complicated': 'compŀc@ð',
'component': 'compoṇ£',
'composition': 'compoṡt¬',
'compound': 'compôđ',
'comprehensive': 'compṛḥnṡṿ',
'compromise': 'comproṁṣ',
'computer': 'compuṭr',
'concentration': 'conc£ɼt¬',
'concept': 'concpt',
'conception': 'concpt¬',
'concern': 'concern',
'concerned': 'concernð',
'concerning': 'concerṅŋ',
'concert': 'concert',
'conclusion': 'conclus¬',
'concrete': 'concṛṭ',
'condition': 'conḋt¬',
'conduct': 'cođu¢',
'conference': 'confeṛnc',
'confession': 'confeß¬',
'confidence': 'conḟḍnc',
'confident': 'conḟḍ£',
'conflict': 'confŀ¢',
'confrontation': 'confronƭt¬',
'confusion': 'confus¬',
'Congress': 'Coŋṛß',
'congressional': 'coŋṛß¬ø',
'connection': 'coṇ¢¬',
'conscience': 'consċenc',
'conscious': 'consċôs',
'consciousness': 'consċôsṇß',
'consecutive': 'conṣcuṫṿ',
'consensus': 'conṣnsus',
'consent': 'conṣ£',
'consequence': 'conṣquenc',
'consequently': 'conṣque£ł',
'conservation': 'conṣrv@¬',
'conservative': 'conṣrvaṫṿ',
'considerable': 'conṡḍɼbḷ',
'considerably': 'conṡḍɼbł',
'consideration': 'conṡḍr@¬',
'consistent': 'conṡsṭ£',
'consistently': 'conṡsṭ£ł',
'conspiracy': 'consṗɼcy',
'constant': 'consƭ£',
'constantly': 'consƭ£ł',
'constitution': 'consṫtut¬',
'constitutional': 'consṫtut¬ø',
'constraint': 'con§ɼi£',
'construction': 'con§ru',
'consultant': 'consulƭ£',
'consumer': 'consuṃr',
'consumption': 'consumpt¬',
'contact': 'conƭ¢',
'contain': 'conƭin', 'contains': 'conƭins',
'container': 'conƭiṇr',
'contained': 'conƭinð',
'contemporary': 'conṭmpoɼỷ',
'content': 'conṭ£',
'contest': 'conṭ§',
'context': 'conṭxt',
'continent': 'conṫṇ£',
'continued': 'conṫnuð',
'continuing': 'conṫnüŋ',
'continuous': 'conṫnuôs',
'contract': 'co£ɼ¢',
'contractor': 'co£ɼ¢or',
'contrast': 'co£ɼ§',
'contribution': 'co£ṙbut¬',
'contributor': 'co£ṙbutor',
'control': 'co£rol',
'controversial': 'co£roṿrṡø',
'controversy': 'co£roṿrsy',
'convenience': 'conṿṅenc',
'convention': 'conṿ£¬',
'conventional': 'conṿnṫ¬ø',
'conversation': 'conṿrʂt¬',
'conversion': 'conṿrs¬',
'conviction': 'convi¢¬',
'convinced': 'convincð',
'cook': 'cōk',
'cookie': 'cōkie',
'cooking': 'cōkiŋ',
'cool': 'cōl',
'cooperate': 'cōp', 'cooperates': 'cōps',
'cooperation': 'cōpt¬', 'cooperations': 'cōpt¬s',
'cooperative': 'cōpṫṿ', 'cooperatives': 'cōpṫṿs',
'coordinator': 'cōrḋɲtor',
'cop': 'cop',
'copy': 'copy',
'cord': 'cord',
'core': 'coṛ',
'corn': 'corn',
'corner': 'corṇr',
'corporate': 'corp',
'corporation': 'corpt¬', 'corporations': 'corpt¬s',
'correct': 'coṛ¢',
'correctly': 'coṛ¢ł',
'correlation': 'coṛl@¬',
'correspondent': 'coṛsponḍ£',
'corridor': 'corṙdor',
'corruption': 'corrupt¬',
'cost': 'co§',
'costly': 'co§ł',
'costume': 'co§uṃ',
'cottage': 'coƭg',
'cotton': 'cotton',
'couch': 'côħ',
'could': 'côld',
'council': 'cônċl',
'counsel': 'cônṣl',
'counseling': 'cônṣŀŋ',
'counselor': 'cônṣlor',
'count': 'cô£',
'counter': 'cônṭr',
'counterpart': 'cônṭrƥrt',
'country': 'cô£ỷ',
'county': 'côn¥',
'coup': 'côp',
'couple': 'côpḷ',
'courage': 'côɼg',
'course': 'côrṣ',
'court': 'côrt',
'courtroom': 'côrtrōm',
'cousin': 'côṡn',
'cover': 'coṿr',
'coverage': 'coṿɼg',
'cow': 'cow',
'crack': 'cɼck',
'craft': 'cɼft',
'crash': 'cɼsh',
'crazy': 'cɼzy',
'cream': 'cṛam',
'creation': 'cṛ@¬',
'creative': 'cṛaṫṿ',
'creativity': 'cṛaṫvi¥',
'creature': 'cṛ@uṛ',
'credibility': 'crðiḃŀ¥',
'credit': 'crðit',
'crew': 'cṛw',
'crime': 'cṙṃ',
'criminal': 'cṙṁɲl',
'crisis': 'cṙṡs',
'criteria': 'cṙṭṙa',
'critic': 'cṙṫc',
'critical': 'cṙṫƈl',
'criticism': 'cṙṫċsm',
'crop': 'crop',
'cross': 'croß',
'crowd': 'crowd',
'crowded': 'crowdð',
'crucial': 'cruċø',
'cruel': 'cruel',
'cruise': 'crüṣ',
'cry': 'cỷ',
'crystal': 'cỷ§ø',
'Cuban': 'Cuɓn',
'cue': 'cue',
'cultural': 'cultuɼl',
'culture': 'cultuṛ',
'cup': 'cup',
'cure': 'cuṛ',
'curiosity': 'cuṙoṡ¥',
'curious': 'cuṙôs',
'currency': 'cuṛncy',
'current': 'cuṛ£',
'currently': 'cuṛ£ł',
'curriculum': 'curṙculum',
'curtain': 'curƭin',
'curve': 'curṿ',
'custody': 'cu§ody',
'custom': 'cu§om',
'customer': 'cu§oṃr',
'cut': 'cut',
'cute': 'cuṭ',
'cycle': 'cycḷ',


// D- \\
'during': 'duṙŋ',
'drive': 'dṙṿ', 'drives': 'dṙṿs',
'driving': 'dṙviŋ', 'drivings': 'dṙviŋs',
'decrease': 'ḍcṛaṣ', 'decreases': 'ḍcṛaṣs',
'decreased': 'dcṛasð',
'database': 'db', 'databases': 'dbṣs',
'danger': 'ɗŋr', 'dangers': 'ɗŋrs',
'damage': 'ɗɱg', 'damages': 'ɗɱgs',
'damaging': 'ɗɱġŋ', 'damagings': 'ɗɱġŋs',
'detail': 'ḍƭil', 'details': 'ḍƭils',
'detailed': 'dtälð',
'detention': 'ḍṭ£¬',
'digital': 'ḋġƭl',
'distribution': 'ḋ§¬',
'distributing': 'ḋsṫŋ',
'distributor': 'ḋ§or', 'distributors': 'ḋ§ors',
'dive': 'ḋṿ',
'division': 'ḋv', 'divisions': 'ḋvs',
'delete': 'ḍl',


'dad': 'ɗd',
'daily': 'ɗił',
'dam': 'ɗm',
'damn': 'ɗmn',
'dance': 'ɗnc',
'dancer': 'ɗncr',
'dancing': 'ɗnċŋ',
'danger': 'ɗŋer',
'dangerous': 'ɗŋerôs',
'dark': 'ɗrk',
'darkness': 'ɗrkṇß',
'data': 'ɗƭ',
'date': 'ɗṭ',
'daughter': 'ɗughṭr',
'dawn': 'ɗwn',
'day': 'ɗy',
'dead': 'ḍad',
'deadline': 'ḍadŀṇ',
'deadly': 'ḍadł',
'deal': 'ḍø',
'dealer': 'ḍaḷr',
'dear': 'ḍar',
'death': 'ḍaŧ',
'debate': 'ḍɓṭ',
'debris': 'ḍbṙs',
'debt': 'ḍbt',
'debut': 'ḍbut',
'decade': 'ḍƈd',
'decent': 'ḍc£',
'decision': 'ḍċs¬',
'deck': 'ḍck',
'decline': 'ḍcŀṇ',
'deep': 'dēp',
'deeply': 'dēpł',
'deer': 'dēr',
'defeat': 'ḍfe@',
'defendant': 'ḍfenɗ£',
'defender': 'ḍfeđer',
'defend': 'ḍfeđ',
'defense': 'ḍfenṣ',
'defensive': 'ḍfenṡṿ',
'deficit': 'ḍḟċt',
'define': 'ḍf',
'definitely': 'ḍfṭł',
'definition': 'ḍft¬',
'degree': 'degrē',
'delay': 'delay',
'deliberately': 'ḍŀḅɼṭł',
'delicate': 'ḍŀƈṭ',
'delight': 'ḍŀght',
'delivery': 'ḍŀṿỷ',
'demand': 'dɱđ',
'democracy': 'ḍmocɼcy',
'Democrat': 'Democɼt',
'democratic': 'ḍmocɼṫc',
'demographic': 'ḍmogɼpḣc',
'demonstration': 'ḍmon§ɼt¬',
'denial': 'ḍṅø',
'dense': 'ḍnṣ',
'density': 'ḍnṡ¥',
'department': 'ḍpṃ£',
'departure': 'ḍptuṛ',
'dependent': 'ḍpenḍ£',
'depending': 'ḍpenḋŋ',
'deposit': 'ḍpoṡt',
'depressed': 'ḍpṛßð',
'depression': 'ḍpṛß¬',
'depth': 'ḍpŧ',
'deputy': 'ḍpu¥',
'description': 'ḍscṙpt¬',
'desert': 'ḍṣr',
'design': 'ḍṡgn',
'designer': 'ḍṡgṇr',
'desire': 'ḍṡṛ',
'desk': 'ḍsk',
'desperate': 'ḍspeɼṭ',
'desperately': 'ḍspeɼṭł',
'despite': 'ḍsṗṭ',
'dessert': 'ḍßert',
'destination': 'ḍ§iɲt¬',
'destruction': 'ḍ§ru¢¬',
'detective': 'ḍṭcṫṿ',
'determination': 'ḍṭrṁɲt¬',
'devastating': 'ḍvasƭṫŋ',
'developer': 'ḍṿr', 'developers': 'ḍṿrs',
'develop': 'ḍvlop',
'developer': 'ḍvloper',
'developing': 'ḍvloṗŋ',
'development': 'ḍv',
'developmental': 'ḍvlopṃnƭl',
'device': 'ḍvic',
'devil': 'ḍvil',
'diabetes': 'ḋaḅṭs',
'diagnosis': 'ḋagnoṡs',
'dialogue': 'ḋøogue',
'diamond': 'ḋamođ',
'diary': 'ḋaỷ',
'diet': 'ḋet',
'difference': 'ḋfṛnc',
'different': 'ḋf',
'differently': 'ḋfṛ£ł',
'difficult': 'ḋfcut',
'difficulty': 'ḋfcu¥',
'digital': 'ḋġƭl',
'dignity': 'ḋgṅ¥',
'dilemma': 'ḋḷɱ',
'dimension': 'ḋṃns¬',
'dining': 'ḋṅŋ',
'dinner': 'ḋnṇr',
'diplomat': 'ḋploɱt',
'diplomatic': 'ḋploɱṫc',
'direct': 'ḋṛ¢',
'direction': 'ḋṛ¢¬',
'directly': 'ḋṛ¢ł',
'director': 'ḋṛ¢or',
'dirt': 'ḋrt',
'dirty': 'ḋr¥',
'disability': 'ḋʂḃŀ¥',
'disabled': 'ḋʂbḷð',
'disappointed': 'ḋʂpö£ð',
'disappointment': 'ḋʂpö£ṃ£',
'disaster': 'ḋʂsṭr',
'disc': 'ḋsc',
'discipline': 'ḋsċpŀṇ',
'discount': 'ḋscô£',
'discourse': 'ḋscôrṣ',
'discover': 'ḋscoṿr',
'discovery': 'ḋscoṿỷ',
'discrimination': 'ḋscṙṁɲt¬',
'discussion': 'ḋscuß¬',
'disease': 'ḋṣaṣ',
'dish': 'ḋsh',
'disk': 'ḋsk',
'disorder': 'ḋsorḍr',
'display': 'ḋsplay',
'dispute': 'ḋspuṭ',
'distance': 'ḋsƭnc',
'distant': 'ḋsƭ£',
'distinct': 'ḋsṫn¢',
'distinction': 'ḋsṫn¢¬',
'distinctive': 'ḋsṫn¢iṿ',
'distribution': 'ḋ§ṙbut¬',
'district': 'ḋ§ṙ¢',
'disturbing': 'ḋ§urḃŋ',
'diverse': 'ḋṿrṣ',
'diversity': 'ḋṿrṡ¥',
'divine': 'ḋviṇ',
'division': 'ḋvis¬',
'divorce': 'ḋvorc',
'DNA': 'DNA',
'doing': 'doiŋ', 'doings': 'doiŋs',
'done': 'doṇ',
'dock': 'dock',
'doctor': 'do¢or', 'doctors': 'do¢ors',
'doctrine': 'do¢ṙṇ',
'document': 'doc', 'documents': 'docs',
'documentary': 'documenƭỷ',
'dog': 'dog',
'doll': 'doll',
'domain': 'doɱin',
'domestic': 'doṃsṫc',
'dominant': 'doṁɲ£',
'donation': 'doɲt¬',
'donor': 'donor',
'door': 'dōr',
'doorway': 'dōrⱳy',
'dose': 'doṣ',
'dot': 'dot',
'double': 'dôbḷ',
'doubt': 'dôbt',
'dough': 'dôgh',
'down': 'down',
'downtown': 'dow£own',
'dozen': 'doẓn',
'draft': 'dɼft',
'drama': 'dɼɱ',
'dramatic': 'dɼɱṫc',
'dramatically': 'dɼɱṫƈł',
'drawer': 'dɼẉr',
'drawing': 'dɼẇŋ',
'dream': 'dṛam',
'dress': 'dṛß',
'dried': 'dṙð',
'drink': 'dṙnk',
'drinking': 'dṙnkiŋ',
'drive': 'dṙṿ',
'driver': 'dṙṿr',
'driveway': 'dṙṿⱳy',
'driving': 'dṙviŋ',
'drop': 'drop',
'drug': 'drug',
'drum': 'drum',
'drunk': 'drunk',
'dry': 'dỷ',
'duck': 'duck',
'due': 'due',
'dumb': 'dumb',
'during': 'duṙŋ',
'dust': 'du§',
'Dutch': 'Dutħ',
'duty': 'du¥',
'dying': 'dẏŋ',
'dynamic': 'dyɲṁc',
'dynamics': 'dyɲṁcs',

// E- \\
'enough': 'enôgh',
'especially': 'spċøł',
'easy': 'esy',
'email': 'eɱil',
'economy': 'econ',
'environment': 'envṃ',
'exercise': 'xrċṣ', 'exercises': 'xrċṣs',
'execution': 'exec',
'executive': 'execṿ', 'executives': 'execṿs',
'explore': 'expl', 'explores': 'expls',
'exploration': 'explor@¬', 'explorations': 'explor@¬s',
'example': 'ex',
'expense': 'expṣ',


'e-mail': 'e-ɱil',
'each': 'eaħ',
'eager': 'eager',
'ear': 'ear',
'early': 'earł',
'earnings': 'earṅŋs',
'earth': 'earŧ',
'earthquake': 'earŧquaḳ',
'ease': 'eaṣ',
'easily': 'eaṡł',
'east': 'ea§',
'eastern': 'ea§rn',
'easy': 'easy',
'eating': 'eaṫŋ',
'ecological': 'ecoloġƈl',
'economic': 'ecoṅc', 'economics': 'ecoṅcs',
'economical': 'econƈl',
'economically': 'econƈł',
'economics': 'ecoṅcs',
'economist': 'ecoṅ§',
'economy': 'economy',
'ecosystem': 'ecosys',
'edge': 'ðge',
'edition': 'ðit¬',
'editor': 'ðitor',
'education': 'ðuƈt¬',
'educational': 'ðuƈt¬ø',
'educator': 'ðuƈtor',
'effect': 'effe¢',
'effective': 'effecṫṿ',
'effectively': 'effecṫṿł',
'effectiveness': 'effecṫṿṇß',
'efficiency': 'efḟċency',
'efficient': 'efḟċe£',
'effort': 'effort',
'egg': 'egg',
'ego': 'ego',
'eight': 'ëght',
'eighth': 'ëghŧ',
'either': 'ëŧer',
'elaborate': 'elaboɼṭ',
'elbow': 'elbow',
'elder': 'elḍr',
'elderly': 'elḍrł',
'election': 'eḷ¢¬',
'electric': 'eḷ¢ṙc',
'electrical': 'eḷ¢ṙƈl',
'electricity': 'eḷ¢ṙċ¥',
'electronic': 'eḷ¢roṅc',
'electronics': 'eḷ¢roṅcs',
'elegant': 'eḷɠ£',
'element': 'eḷm', 'elements': 'eḷms',
'elementary': 'eḷmƭỷ',
'elephant': 'eḷpɦ£',
'elevator': 'eḷv@or',
'eleven': 'eḷṿn',
'eligible': 'eŀġbḷ',
'elite': 'eŀṭ',
'else': 'elṣ',
'elsewhere': 'elṣwḥṛ',
'embarrassed': 'emɓɼßð',
'emergency': 'eṃrgency',
'emerging': 'eṃrġŋ',
'emission': 'eṁß¬',
'emotion': 'emot¬',
'emotional': 'emot¬ø',
'emotionally': 'emot¬øł',
'emphasis': 'empɦṡs',
'empire': 'emṗṛ',
'employ': 'empy', 'employs': 'empys',
'employee': 'empē', 'employees': 'empēs',
'employer': 'emper', 'employers': 'empers',
'employment': 'employṃ£',
'empty': 'emp¥',
'encounter': 'encônṭr',
'encouraging': 'encôɼġŋ',
'end': 'eđ',
'endless': 'eđḷß',
'enemy': 'eṇmy',
'energy': 'eṇrgy',
'enforcement': 'enforcṃ£',
'engage': 'enɠg', 'engages': 'enɠges',
'engagement': 'enɠgeṃ£',
'engaging': 'enɠġŋ',
'engine': 'eŋ',
'engineer': 'eŋer', 'engineers': 'eŋers',
'engineering': 'enġŋ',
'English': 'Eŋŀsh',
'enormous': 'enormôs',
'enough': 'enôgh',
'enterprise': 'enṭrpṙṣ',
'entertainment': 'enṭrƭinṃ£',
'enthusiasm': 'enŧuṡasm',
'entire': 'enṫṛ',
'entirely': 'enṫṛł',
'entity': 'enṫ¥',
'entrance': 'e£ɼnc',
'entrepreneur': 'e£ṛp', 'entrepreneurs': 'e£ṛps',
'entrepreneurship': 'e£ṛpsḣp',
'entrepreneurial': 'e£ṛpṙø',
'entry': 'e£ỷ',
'envelope': 'enṿlop',
'environment': 'environṃ£',
'environmental': 'environṃnƭl',
'epidemic': 'eṗḍṁc',
'episode': 'eṗsoḍ',
'equal': 'equø',
'equality': 'equaŀ¥',
'equally': 'equøł',
'equation': 'equ@¬',
'equipment': 'eqüpṃ£', 'equipments': 'eqüpṃ£s',
'equity': 'eqü¥',
'equivalent': 'eqüvaḷ£',
'era': 'eɼ',
'error': 'error',
'escape': 'esƈp',
'especially': 'espeċøł',
'essay': 'eʂy',
'essence': 'eßenc',
'essential': 'eßenṫø',
'essentially': 'eßenṫøł',
'establishment': 'esƭbŀshṃ£',
'estate': 'esƭṭ',
'estimate': 'esṫɱṭ',
'estimated': 'esṫɱtð',
'etc': 'etc',
'ethical': 'eŧiƈl',
'ethics': 'eŧics',
'ethnic': 'eŧṅc',
'European': 'European',
'evaluation': 'ev',
'even': 'eṿn',
'evening': 'eṿṅŋ',
'event': 'eṿ£',
'eventually': 'eṿ£uøł',
'ever': 'eṿr',
'every': 'eṿỷ',
'everybody': 'eṿỷbody',
'everyday': 'eṿỷɗy',
'everyone': 'eṿỷoṇ',
'everything': 'eṿỷŧiŋ',
'everywhere': 'eṿỷwḥṛ',
'evidence': 'eviḍnc',
'evident': 'eviḍ£',
'evil': 'evil',
'evolution': 'evo',
'exact': 'exa¢',
'exactly': 'exa¢ł',
'exam': 'exam',
'examination': 'exaṁɲt¬',
'excellent': 'excḷ£',
'except': 'excpt',
'exception': 'excpt¬',
'excessive': 'exceßiṿ',
'exchange': 'excɦŋg', 'exchanges': 'excɦŋgs',
'excited': 'exċtð',
'excitement': 'exċṭṃ£',
'exciting': 'exċṫŋ',
'exclusive': 'excluṡṿ',
'exclusively': 'excluṡṿł',
'excuse': 'excuṣ',
'execution': 'execut¬',
'executive': 'execuṫṿ',
'exercise': 'exerċṣ',
'exhibit': 'exḣḃt',
'exhibition': 'exḣḃt¬',
'existence': 'eẋsṭnc',
'existing': 'eẋsṫŋ',
'exit': 'eẋt',
'exotic': 'exoṫc',
'expansion': 'exƥns¬',
'expectation': 'expe¢at¬',
'expected': 'expe¢ð',
'expedition': 'expeḋt¬',
'expense': 'expenṣ',
'expensive': 'expenṡṿ',
'experience': 'exp',
'experienced': 'expcð',
'experiment': 'expṃ£', 'experiments': 'expṃ£s',
'experimentation': 'expt¬',
'experimental': 'expṃnƭl',
'expert': 'expert',
'expertise': 'experṫṣ',
'explanation': 'explaɲt¬',
'explicit': 'expŀċt',
'explosion': 'explos¬',
'export': 'export',
'exposure': 'exposuṛ',
'expression': 'expṛs¬',
'extended': 'exṭđð',
'extension': 'exṭns¬',
'extensive': 'exṭnṡṿ',
'extent': 'exṭ£',
'external': 'exṭrɲl',
'extra': 'extɼ',
'extraordinary': 'extɼorḋɲỷ',
'extreme': 'xtṛṃ', 'extremes': 'xtṛṃs',
'extremely': 'xtṛṃł',
'extrinsic': 'extṙnṡc',
'eye': 'eỵ',
'eyebrow': 'eỵbrow',

// F- \\
'feedback': 'fēdɓk', 'feedbacks': 'fēdɓks',
'first': 'ḟr§',
'foundation': 'fônɗt¬', 'foundations': 'fônɗt¬s',
'function': 'func', 'functions': 'funcs',
'functional': 'funcɲl', 'functionals': 'funcɲls',
'functionality': 'funcɲŀ¥', 'functinalities': 'funcɲŀṫes',

'fabric': 'ƒbṙc',
'face': 'ƒc',
'facility': 'ƒċŀ¥',
'fact': 'ƒ¢', 'facts': 'ƒ¢s',
'factor': 'ƒ¢or',
'factory': 'ƒ¢oỷ',
'faculty': 'ƒcul¥',
'failure': 'ƒiltuṛ',
'faint': 'ƒi£',
'fair': 'ƒir',
'fairly': 'ƒirł',
'faith': 'ƒiŧ',
'fall': 'ƒl',
'falso ': 'ƒlso',
'fame': 'ƒṃ',
'familiar': 'ƒṁŀar',
'famous': 'ƒmôs',
'fan': 'ƒn',
'fantastic': 'ƒnƭsṫc',
'fantasy': 'ƒnƭsy',
'far': 'ƒr',
'fare': 'ƒṛ',
'farm': 'ƒrm',
'farmer': 'ƒrṃr',
'fascinating': 'ƒsċɲṫŋ',
'fashion': 'ƒsh¬',
'fast': 'ƒ§',
'faster': 'ƒ§er',
'fat': 'ƒt',
'fatal': 'ƒƭl',
'fate': 'ƒṭ',
'father': 'ƒŧer',
'fatigue': 'ƒṫgue',
'fault': 'ƒult',
'favor': 'ƒvor',
'favorable': 'ƒvoɼbḷ',
'favorite': 'ƒvoṙṭ',
'fear': 'fear',
'feather': 'feaŧer',
'feature': 'fe@uṛ', 'features': 'fe@uṛs', 
'federal': 'feḍrø', 'federals': 'feḍrøs',
'federation': 'feḍɼt¬', 'federations': 'feḍɼt¬s',
'fee': 'fē',
'feel': 'fēl',
'feeling': 'fēŀŋ',
'fellow': 'fellow',
'female': 'feɱḷ',
'feminist': 'feṁṅ§',
'fence': 'fenc',
'festival': 'fesṫvø',
'fever': 'feṿr',
'few': 'few',
'fewer': 'feẉr',
'fiber': 'ḟḅr',
'fiction': 'ḟ¢¬',
'field': 'ḟeld',
'fierce': 'ḟerc',
'fifteen': 'ḟftēn',
'fifth': 'ḟfŧ',
'fifty': 'ḟf¥',
'fight': 'ḟght',
'fighter': 'ḟghṭr',
'fighting': 'ḟghṫŋ',
'figure': 'ḟguṛ',
'file': 'ḟḷ',
'film': 'ḟlm',
'filter': 'ḟlṭr',
'final': 'ḟɲl',
'finally': 'ḟɲł',
'finance': 'ḟn', 'finances': 'ḟns',
'financed': 'ḟncð',
'financing': 'ḟnċŋ',
'financial': 'ḟnċø', 'financials': 'ḟnċøs',
'find': 'ḟnd', 'finds': 'ḟnds',
'finding': 'ḟnḋŋ',
'fine': 'ḟṇ',
'finger': 'ḟŋer',
'finish': 'ḟṅsh',
'fire': 'ḟṛ',
'firm': 'ḟrm',
'firmly': 'ḟrmł',
'first': 'ḟr§',
'fiscal': 'ḟsƈl',
'fish': 'ḟsh',
'fisherman': 'ḟsḥrɱn',
'fishing': 'ḟsḣŋ',
'fist': 'ḟ§',
'fit': 'ḟt',
'fitness': 'ḟtṇß',
'five': 'ḟṿ',
'fixed': 'ḟxð',
'flag': 'flag',
'flame': 'flaṃ',
'flash': 'flash',
'flat': 'fl@',
'flavor': 'flavor',
'fleet': 'flēt',
'flesh': 'fḷsh',
'flexibility': 'fḷẋḃŀ¥',
'flexible': 'fḷẋbḷ',
'flight': 'fŀght',
'flood': 'flōd',
'floor': 'flōr',
'flour': 'flôr',
'flow': 'flow',
'flower': 'floẉr',
'fluid': 'flüd',
'fly': 'fly',
'flying': 'flẏŋ',
'focus': 'focus',
'fog': 'fog',
'folk': 'folk',
'following': 'folloẇŋ',
'food': 'fōd',
'fool': 'fōl',
'foot': 'fōt',
'football': 'fōtɓl',
'for': 'for',
'force': 'forc',
'forehead': 'foṛḥad',
'foreign': 'foṛign',
'foreigner': 'foṛigṇr',
'forest': 'foṛ§',
'forever': 'foṛṿr',
'fork': 'fork',
'form': 'form',
'formal': 'forɱl',
'format': 'forɱt',
'formation': 'forɱt¬',
'former': 'forṃr',
'formerly': 'forṃrł',
'formula': 'formula',
'forth': 'forŧ',
'fortunately': 'fortuɲṭł',
'fortune': 'fortuṇ',
'forty': 'for¥',
'forum': 'forum',
'forward': 'forⱳrd',
'founder': 'fônḍr',
'four': 'fôr',
'fourth': 'fôrŧ',
'fraction': 'fɼ¢¬',
'fragile': 'fɼġḷ',
'fragment': 'fɼgṃ£',
'frame': 'fɼṃ',
'framework': 'fɼṃwork',
'franchise': 'fɼncḣṣ',
'frankly': 'fɼkł',
'fraud': 'fɼud',
'free': 'frē',
'freedom': 'frēdom',
'freely': 'frēł',
'French': 'Fṛnħ',
'frequency': 'fṛquency',
'frequent': 'fṛque£',
'frequently': 'fṛque£ł',
'fresh': 'fṛsh',
'freshman': 'fṛshɱn',
'friend': 'fṙeđ', 'friends': 'fṙeđs',
'friendly': 'fṙeđł',
'friendship': 'fṙeđsḣp', 'friendships': 'fṙeđsḣps',
'from': 'from',
'front': 'fro£',
'frontier': 'fronṫer',
'frozen': 'froẓn',
'fruit': 'früt',
'frustration': 'fru§ɼt¬',
'fucking': 'fuckiŋ',
'fuel': 'fuel',
'full': 'full',
'full-time': 'full-ṫṃ',
'fully': 'fulł',
'fun': 'fun',
'fund': 'fuđ',
'fundamental': 'fuđaṃnƭl',
'funding': 'fuđiŋ',
'funeral': 'fuṇɼl',
'funny': 'funny',
'fur': 'fur',
'furniture': 'furṅtuṛ',
'furthermore': 'furŧermoṛ',
'future': 'futuṛ',

// G- \\
'general': 'geṇɼl', 'generals': 'geṇɼls',
'government': 'gov', 'governments': 'govs',
'group': 'grôp', 'groups': 'grôps',
'gamification': 'ɠṁḟƈt¬',
'Gamification': 'Ɠṁḟƈt¬',

'gain': 'ɠin',
'galaxy': 'ɠlaxy',
'gallery': 'ɠḷỷ',
'game': 'ɠṃ',
'gang': 'ɠŋ',
'gap': 'ɠp',
'garage': 'ɠɼge',
'garbage': 'ɠrɓg',
'garden': 'ɠrḍn',
'garlic': 'ɠrŀc',
'gas': 'ɠs',
'gasoline': 'ɠsoŀṇ',
'gate': 'ɠṭ',
'gathering': 'ɠŧeṙŋ',
'gay': 'ɠy',
'gaze': 'ɠẓ',
'gear': 'gear',
'gender': 'geđer',
'gene': 'geṇ',
'general': 'geṇɼl',
'generally': 'geṇɼł',
'generation': 'geṇɼt¬',
'generous': 'geṇrôs',
'genetic': 'geṇṫc',
'genius': 'geṅus',
'genre': 'genṛ',
'gentle': 'ge£ḷ',
'gentleman': 'ge£ḷɱn',
'gently': 'gent',
'genuine': 'genüṇ',
'German': 'Gerɱn',
'gesture': 'ge§uṛ',
'ghost': 'gho§',
'giant': 'ġa£',
'gift': 'ġft',
'gifted': 'ġftð',
'girl': 'ġrl',
'girlfriend': 'ġrlfṙeđ',
'given': 'ġṿn',
'glad': 'glad',
'glance': 'glanc',
'glass': 'glaß',
'glimpse': 'gŀmpṣ',
'global': 'gloɓl',
'globe': 'gloḅ',
'glory': 'gloỷ',
'glove': 'gloṿ',
'goal': 'goø',
'goat': 'go@',
'God': 'God',
'gold': 'gold',
'golden': 'golḍn',
'golf': 'golf',
'good': 'gōd',
'governor': 'govnor',
'grace': 'gɼc',
'grade': 'gɼḍ',
'gradually': 'gɼduøł',
'graduate': 'gɼduaṭ',
'graduation': 'gɼdu@¬',
'grain': 'gɼin',
'grand': 'gɼđ',
'grandchild': 'gɼđcḣld',
'grandfather': 'gɼđƒŧer',
'grandmother': 'gɼđmoŧer',
'grandparent': 'gɼđƥṛ£',
'grant': 'gɼ£',
'grape': 'gɼpe',
'grass': 'gɼß',
'grateful': 'gɼṭful',
'grave': 'gɼṿ',
'gravity': 'gɼvi¥',
'gray': 'gɼy',
'great': 'gṛ@',
'greatest': 'gṛaṭ§',
'greatly': 'gṛ@ł',
'Greek': 'Grēk',
'green': 'grēn',
'grief': 'gṙef',
'grin': 'gṙn',
'grip': 'gṙp',
'grocery': 'groceỷ',
'gross': 'groß',
'ground': 'grôđ',
'group': 'grôp',
'growing': 'groẇŋ',
'growth': 'growŧ',
'guarantee': 'guaɼ£ē',
'guard': 'guard',
'guest': 'gue§',
'guidance': 'güɗnc',
'guide': 'güḍ',
'guideline': 'güḍŀṇ',
'guilt': 'gült',
'guilty': 'gül¥',
'guitar': 'güƭr',
'gun': 'gun',
'gut': 'gut',
'guy': 'guy',
'gym': 'gym',


// I- \\
'improve': 'improṿ', 'improves': 'improṿs',
'improving': 'imprviŋ', 'improvings': 'improviŋs',
'incorporated' : 'incorptð',
'important': 'impƭ£', 'importants': 'impƭ£s',


'ice': 'ice',
'icon': 'icon',
'idea': 'iḍa',
'ideal': 'iḍø',
'identical': 'iḍnṫƈl',
'identification': 'iḍnṫḟƈt¬',
'identity': 'iḍnṫ¥',
'ideological': 'iḍoloġƈl',
'ideology': 'iḍology',
'if': 'if',
'ill': 'ill',
'illegal': 'ilḷɠø',
'illness': 'illṇß',
'illusion': 'illus¬',
'image': 'iɱg', 'images': 'iɱgs',
'imagination': 'iɱġɲt¬',
'immediate': 'iṃḋaṭ',
'immediately': 'iṃḋaṭł',
'immigration': 'imṁgɼt¬',
'immigrant': 'imṁgɼ£',
'immune': 'immuṇ',
'impact': 'imƥ¢',
'implementation': 'impḷṃnƭt¬',
'implication': 'impŀƈt¬',
'import': 'import',
'importance': 'imporƭnc',
'important': 'imporƭ£',
'importantly': 'imporƭ£ł',
'impossible': 'impoßibḷ',
'impression': 'impṛß¬',
'impressive': 'impṛßiṿ',
'improved': 'improvð',
'improvement': 'improṿṃ£',
'impulse': 'impulṣ',
'in': 'in',
'incentive': 'incenṫṿ',
'incident': 'inċḍ£',
'including': 'incluḍŋ',
'income': 'incoṃ',
'increase': 'incṛaṣ', 'increases': 'incṛaṣs',
'increased': 'incṛṣð',
'increasing': 'incṛaṡŋ',
'increasingly': 'incṛaṡŋł',
'incredible': 'incṛḍbḷ',
'incredibly': 'incṛḍbł',
'indeed': 'iđēd',
'independence': 'iđepenḍnc',
'independent': 'iđepenḍ£',
'index': 'inḍex',
'Indian': 'Inḍan',
'indication': 'inḍƈt¬',
'indicator': 'inḍƈtor',
'indigenous': 'inḍgenôs',
'individual': 'inḍviduø',
'industrial': 'iđu§ṙø',
'industry': 'iđu§ỷ',
'inevitable': 'iṇviƭbḷ',
'inevitably': 'iṇviƭbly',
'infant': 'inƒ£',
'infection': 'infe¢¬',
'inflation': 'infl@¬',
'influence': 'influenc',
'influential': 'influenṫø',
'informal': 'inforɱl',
'information': 'info',
'infrastructure': 'infɼ§ru¢uṛ',
'ingredient': 'iŋṛḍe£',
'inherent': 'inḥṛ£',
'initial': 'iṅṫø',
'initially': 'iṅṫøł',
'initiative': 'iṅṫaṫṿ',
'injury': 'injuỷ',
'inmate': 'inɱṭ',
'inner': 'inṇr',
'innocent': 'inoce£',
'innovate': 'innoṭ',
'innovation': 'innot¬', 'innovations': 'innot¬s',
'innovative': 'innoṿ',
'input': 'input',
'inquiry': 'inqüỷ',
'insect': 'inṣ¢',
'inside': 'inṡḍ',
'insight': 'inṡght',
'inspection': 'inspe¢¬',
'inspector': 'inspe¢or',
'inspiration': 'insṗɼt¬',
'installation': 'insƭl@¬',
'instance': 'insƭnc',
'instant': 'insƭ£',
'instantly': 'insƭ£ł',
'instead': 'insṭad',
'instead': 'insṭad',
'instinct': 'insṫn¢',
'institution': 'in§¬', 'institutions': 'in§¬s',
'institutional': 'insṫtut¬ø',
'instruction': 'in§ru¢¬',
'instructional': 'in§ru¢¬ø',
'instructor': 'in§ru¢or',
'instrument': 'in§ruṃ£',
'insurance': 'insuɼnce',
'intact': 'inƭ¢',
'integrated': 'inṭgɼtð',
'integration': 'inṭgɼt¬',
'integrity': 'inṭgṙ¥',
'intellectual': 'inṭḷ¢uø',
'intelligence': 'inṭl',
'intelligent': 'inṭlge£',
'intense': 'inṭnṣ',
'intensity': 'inṭnṡ¥',
'intent': 'inṭ£',
'intention': 'inṭ£¬',
'interaction': 'inṭɼ¢¬',
'interest': 'inṭṛ§',
'interested': 'inṭṛ§ð',
'interesting': 'inṭṛ§iŋ',
'interior': 'inṭṙor',
'internal': 'inṭrɲl',
'international': 'inṭrɲṫoɲl',
'Internet': 'Inṭrṇt',
'interpretation': 'inṭrpṛƭt¬',
'interval': 'inṭrvø',
'intervention': 'inṭrṿ£¬',
'interview': 'inṭrview',
'interface': 'inṭrƒc', 'Interface': 'Inṭrƒc',
'intimate': 'inṫɱṭ',
'intrinsic': 'intṙnṡc',
'into': 'i£o',
'introduction': 'i£ro',
'Introduction': 'I£ro',
'invasion': 'invas¬',
'invention': 'inṿ£¬',
'inventory': 'inṿ£oỷ',
'investigation': 'inṿsṫɠt¬',
'investigator': 'inṿsṫɠtor',

'invest': 'inv',
'investment': 'invṃ£',
'investor': 'invtor', 'investors': 'invtors',
'invisible': 'inviṡbḷ',
'invitation': 'inviƭt¬',
'involved': 'involvð',
'involvement': 'involṿṃ£',
'Iraqi': 'Iɼqi',
'Irish': 'Iṙsh',
'iron': 'iron',
'ironically': 'iroṅƈł',
'irony': 'irony',
'Islam': 'Islam',
'Islamic': 'Islaṁc',
'island': 'islađ',
'isolated': 'isol@ð',
'isolation': 'isol@¬',
'Israeli': 'Isɼeŀ',
'issue': 'ißue',
'it': 'it', 'its': 'its',
'Italian': 'Iƭŀan',
'item': 'iṭm',
'itself': 'itṣlf',

// H- \\
'habit': 'ɦḃt',
'habitat': 'ɦḃƭt',
'hair': 'ɦir',
'half': 'ɦlf',
'halfway': 'ɦlfⱳy',
'hall': 'ɦl',
'hallway': 'ɦlⱳy',
'hand': 'ɦđ',
'handful': 'ɦđful',
'handle': 'ɦđḷ',
'handsome': 'ɦđsoṃ',
'happily': 'ɦṗł',
'happiness': 'ɦṗṇß',
'happy': 'ɦpy',
'harass': 'ɦɼß',
'harassment': 'ɦɼßṃ£',
'hard': 'ɦrd',
'hardly': 'ɦrdł',
'hardware': 'ɦrdⱳṛ',
'harm': 'ɦrm',
'harmony': 'ɦrmony',
'harsh': 'ɦrsh',
'harvest': 'ɦrṿ§',
'hat': 'ɦt',
'hay': 'ɦy',
'hazard': 'ɦzard',
'he': 'ḥ',
'head': 'ḥad',
'headache': 'ḥaɗcḥ',
'headline': 'ḥadŀṇ',
'headquarters': 'ḥadquarṭrs',
'health': 'ḥøŧ',
'healthy': 'ḥøŧy',
'hearing': 'ḥaṙŋ',
'heart': 'ḥart',
'heat': 'ḥ@',
'heaven': 'ḥaṿn',
'heavily': 'ḥavił',
'heavy': 'ḥavy',
'heel': 'hēl',
'height': 'ḥight',
'helicopter': 'ḥŀcopṭr',
'hell': 'ḥl',
'hello': 'ḥlo',
'helmet': 'ḥlṃt',
'help': 'ḥlp',
'helpful': 'ḥlpful',
'hence': 'ḥnc',
'her': 'ḥr',
'herb': 'ḥrb',
'here': 'ḥṛ',
'heritage': 'ḥṙƭg',
'hero': 'ḥro',
'hers': 'ḥrs',
'herself': 'ḥrṣlf',
'hey': 'ḥy',
'hi': 'ḣ',
'hidden': 'ḣḍn',
'high': 'ḣgh',
'high-tech': 'ḣgh-ṭħ',
'highly': 'ḣghł',
'highway': 'ḣghⱳy',
'hill': 'ḣll',
'him': 'ḣm',
'himself': 'ḣmṣlf',
'hint': 'ḣ£',
'hip': 'ḣp',
'his': 'ḣs',
'Hispanic': 'Ḣsƥṅc',
'historian': 'ḣ§oṙan',
'historic': 'ḣ§oṙc',
'historical': 'ḣ§oṙƈl',
'historically': 'ḣ§oṙƈł',
'history': 'ḣ§oỷ',
'hit': 'ḣt',
'hockey': 'hocḳy',
'hold': 'hold',
'hole': 'hoḷ',
'holiday': 'hoŀɗy',
'holy': 'holy',
'home': 'hoṃ',
'homeland': 'hoṃlađ',
'homeless': 'hoṃḷß',
'homework': 'hoṃwork',
'honest': 'hoṇ§',
'honestly': 'hoṇ§ł',
'honey': 'hoṇy',
'honor': 'honor',
'hook': 'hōk',
'hope': 'hope',
'hopefully': 'hopefulł',
'horizon': 'hoṙzon',
'hormone': 'hormoṇ',
'horn': 'horn',
'horrible': 'horṙbḷ',
'horror': 'horror',
'horse': 'horṣ',
'hospital': 'hosṗƭl',
'host': 'ho§',
'hostage': 'hosƭg',
'hostile': 'hos~e',
'hot': 'hot',
'hotel': 'hoṭl',
'hour': 'hôr',
'house': 'hôṣ',
'household': 'hôṣhold',
'housing': 'hôṡŋ',
'how': 'how',
'however': 'hoẉṿr',
'huge': 'huge',
'huh': 'huh',
'human': 'huɱn',
'humanity': 'huɱṅ¥',
'humor': 'humor',
'hundred': 'huđrð',
'hunger': 'huŋer',
'hungry': 'huŋỷ',
'hunter': 'hunṭr',
'hunting': 'hunṫŋ',
'hurricane': 'hurṙƈṇ',
'husband': 'husɓđ',
'hypothesis': 'hypoŧeṡs',

// J- \\
'jacket': 'jacḳt',
'jail': 'jäl',
'Japanese': 'Jaƥṇṣ',
'jar': 'jar',
'jaw': 'jaw',
'jazz': 'jazz',
'jeans': 'jeans',
'jet': 'jet',
'Jew': 'Jew',
'jewelry': 'jeẉlỷ',
'Jewish': 'Jeẇsh',
'job': 'job',
'joint': 'jö£',
'joke': 'joḳ',
'journal': 'jôɲl',
'journalism': 'jôrɲŀsm',
'journalist': 'jôrɲŀ§',
'journey': 'jôrṇy',
'joy': 'joy',
'judge': 'judge',
'judgment': 'judgṃ£',
'judicial': 'juḍċø',
'juice': 'jüc',
'jump': 'jump',
'jungle': 'juŋḷ',
'junior': 'juṅor',
'jurisdiction': 'juṙsḍ¢¬',
'juror': 'juror',
'jury': 'juỷ',
'just': 'ju§',
'justice': 'jusṫce',

// K- \\
'key': 'ḳy',
'kid': 'kid',
'killer': 'kiḷr',
'killing': 'kilŀŋ',
'kind': 'kiđ',
'king': 'kiŋ',
'kingdom': 'kiŋdom',
'kiss': 'kiß',
'kit': 'kit',
'kitchen': 'kitcḥn',
'knee': 'knē',
'knife': 'kṅfe',
'know': 'know',
'knowledge': 'knowḷdge',
'Korean': 'Koṛan',

// L- \\
'leave': 'ḷaṿ', 'leaves': 'ḷaṿs',
'leaving': 'ḷaviŋ',
'language': 'laŋ', 'languages': 'laŋs',
'limited': 'ŀṁtð',
'litigation': 'ŀṫɠt¬',
'large': 'larg',
'little': 'ŀl',

'lab': 'lab',
'label': 'laḅl',
'labor': 'labor',
'laboratory': 'lab',
'laboratories': 'labs',
'lack': 'lack',
'ladder': 'laḍr',
'lady': 'lady',
'lake': 'laḳ',
'lamp': 'lamp',
'land': 'lađ',
'landing': 'lađiŋ',
'landmark': 'lađɱrk',
'landscape': 'lađsƈp',
'lane': 'laṇ',
'language': 'laŋuage',
'lap': 'lap',
'large': 'large',
'largely': 'largeł',
'laser': 'laṣr',
'last': 'la§',
'late': 'laṭ',
'lately': 'laṭł',
'later': 'laṭr',
'Latin': 'Laṫn',
'latter': 'l@ṭr',
'laugh': 'laugh',
'laughter': 'laughṭr',
'launch': 'launħ',
'laundry': 'lauđỷ',
'law': 'law',
'lawmaker': 'lawɱḳr',
'lawn': 'lawn',
'lawsuit': 'lawsüt',
'lawyer': 'lawỵr',
'layer': 'laỵr',
'lead': 'ḷad',
'leader': 'ḷaḍr',
'leadership': 'ḷaḍrsḣp',
'leading': 'ḷaḍŋ',
'leaf': 'ḷaf',
'league': 'ḷague',
'learn': 'ḷrn',
'learning': 'ḷarṅŋ',
'learned': 'ḷarnð',
'least': 'ḷa§',
'leather': 'ḷaŧer',
'leave': 'ḷaṿ',
'lecture': 'ḷ¢uṛ',
'left': 'ḷft',
'leg': 'ḷg',
'legacy': 'ḷɠcy',
'legal': 'ḷɠl',
'legally': 'ḷɠł',
'legend': 'ḷgđ',
'legislation': 'ḷġsl@¬',
'legislative': 'ḷġslaṫṿ',
'legislator': 'ḷġsl@or',
'legislature': 'ḷġsl@uṛ',
'legitimate': 'ḷġṫɱṭ',
'lemon': 'ḷmon',
'length': 'ḷŋŧ',
'lens': 'ḷns',
'less': 'ḷß',
'lesson': 'ḷßon',
'letter': 'ḷtṭr',
'level': 'ḷṿl',
'liability': 'ŀab',
'liberal': 'ŀḅɼl',
'liberty': 'ŀḅr¥',
'library': 'ŀbɼỷ',
'license': 'ŀcnṣ',
'lid': 'ŀd',
'lie': 'ŀe',
'life': 'ŀfe',
'lifestyle': 'ŀfe§yḷ',
'lifetime': 'ŀfeṫṃ',
'light': 'ŀght',
'lighting': 'ŀghṫŋ',
'lightly': 'ŀghtł',
'lightning': 'ŀghtṅŋ',
'like': 'ŀḳ', 'likes': 'ŀḳs',
'liking': 'ŀḳiŋ',
'liked': 'ŀkð',
'likelihood': 'ŀḳŀhōd',
'likely': 'ŀḳł',
'likewise': 'ŀḳẇṣ',
'limb': 'ŀmb',
'limit': 'ŀṁt',
'limitation': 'ŀṁƭt¬',
'limited': 'ŀṁtð',
'line': 'ŀṇ',
'link': 'ŀnk',
'lion': 'l¬',
'lip': 'ŀp',
'liquid': 'ŀqüd',
'list': 'ŀ§',
'listener': 'ŀsṭṇr',
'literally': 'ŀṭɼł',
'literary': 'ŀṭɼỷ',
'literature': 'ŀṭɼtuṛ',
'little': 'ŀttḷ',
'live': 'ŀṿ',
'liver': 'ŀṿr',
'living': 'ŀviŋ',
'load': 'load',
'loan': 'loan',
'lobby': 'lobby',
'local': 'loƈl',
'location': 'loƈt¬',
'lock': 'lock',
'log': 'log',
'logic': 'loġc',
'logical': 'loġƈl',
'lonely': 'loṇł',
'long': 'loŋ',
'long-term': 'loŋ-ṭrm',
'longtime': 'loŋṫṃ',
'look': 'lōk', 'looks': 'lōks',
'loop': 'lōp',
'loose': 'lōṣ',
'loss': 'loß',
'lost': 'lo§',
'lot': 'lot',
'lots': 'lots',
'loud': 'lôd',
'love': 'loṿ',
'lovely': 'loṿł',
'lover': 'loṿr',
'low': 'low',
'loyal': 'loyø',
'loyalty': 'loyø¥',
'luck': 'luck',
'lucky': 'lucky',
'lunch': 'lunħ',
'lung': 'luŋ',

// M- \\
'meet': 'mēt', 'meets': 'mēts',
'meeting': 'mēṫŋ', 'meetings': 'mēṫŋs',
'method': 'ṃŧd', 'methods': 'ṃŧds',
'matter': 'ɱtṭr', 'matters': 'ɱtṭrs',
'make': 'ɱḳ', 'makes': 'ɱḳs',
'making': 'ɱk¬',
'mutual': 'mut',
'medium': 'ṃḍum',
'millisecond': 'ṁlŀṣc', 'milliseconds': 'ṁlŀṣcs',

'machine': 'ɱħ', 'machines': 'ɱħs',
'mad': 'ɱd',
'magazine': 'ɱɠżṇ',
'magic': 'ɱġc',
'magnetic': 'ɱgṇṫc',
'magnitude': 'ɱgṅtuḍ',
'mail': 'ɱil',
'main': 'ɱin',
'mainly': 'ɱinł',
'mainstream': 'ɱin§ṛam',
'maintenance': 'ɱinṭɲnc',
'major': 'ɱjor',
'majority': 'ɱjoṙ¥',
'maker': 'ɱḳr',
'makeup': 'ɱḳup',
'male': 'ɱḷ',
'mall': 'ɱl',
'man': 'ɱn',
'manage': 'ɱɲg', 'manages': 'ɱɲgs',
'manager': 'ɱɲgr', 'managers': 'ɱɲgrs',
'management': 'ɱɲgṃ£',
'managing': 'ɱɲġŋ',
'mandate': 'ɱnɗṭ',
'manner': 'ɱṇr',
'mansion': 'ɱns¬',
'manual': 'ɱnuø',
'manufacture': 'ɱnuf',
'manufacturing': 'ɱnuḟŋ',
'manufacturer': 'ɱnufer',
'many': 'ɱny',
'map': 'ɱp',
'marble': 'ɱrbḷ',
'margin': 'ɱrġn',
'marine': 'ɱṙṇ',
'mark': 'ɱrk',
'marker': 'ɱrḳr',

'market': 'ɱrḳt',
'marketing': 'ɱrḳṫŋ',
'marketplace': 'ɱrḳtplace',
'marriage': 'ɱṙag',
'married': 'ɱṙð',
'mask': 'ɱsk',
'mass': 'ɱß',
'massive': 'ɱßiṿ',
'master': 'ɱsṭr',
'match': 'ɱtħ',
'mate': 'ɱṭ',
'material': 'ɱṭṙø',
'math': 'ɱŧ',
'mathematics': 'ɱŧeɱṫcs',
'matter': 'ɱṭr',
'maximum': 'ɱẋmum',
'may': 'ɱy',
'maybe': 'ɱyḅ',
'mayor': 'ɱyor',
'me': 'ṃ',
'meal': 'ṃø',
'mean': 'ṃan',
'meaning': 'ṃaṅŋ',
'meaningful': 'ṃaṅŋful',
'meantime': 'ṃanṫṃ',
'meanwhile': 'ṃanwḣḷ',
'measure': 'ṃasuṛ', 'measures': 'ṃasuṛs',
'measuring': 'ṃasuṙŋ', 'measurings': 'ṃasuṙŋs',
'measurement': 'ṃasuṛṃ£',
'meat': 'ṃ@',
'mechanic': 'ṃħ',
'mechanical': 'ṃħƈl',
'mechanism': 'ṃħṅsm',
'medal': 'ṃɗl',
'media': 'ṃḍa',
'medical': 'ṃḍƈl',
'medication': 'ṃḍƈt¬',
'medicine': 'ṃd',
'medium': 'ṃḍum',
'meeting': 'mēṫŋ',
'member': 'ṃmḅr',
'membership': 'ṃmḅrsḣp',
'memory': 'ṃmoỷ',
'mental': 'ṃnƭl',
'mentally': 'ṃnƭł',
'mention': 'ṃ£¬',
'mentor': 'ṃ£or',
'menu': 'ṃnu',
'merchant': 'ṃrcɦ£',
'mere': 'ṃṛ',
'merely': 'ṃṛł',
'merit': 'ṃṙt',
'mess': 'ṃß',
'message': 'ṃʂg', 'messages': 'ṃʂgs',
'messaging': 'ṃʂġŋ', 'messagings': 'ṃʂġŋs',
'metal': 'ṃƭl',
'metaphor': 'ṃƭphor',
'meter': 'ṃṭr',
'method': 'ṃŧod',
'metropolitan': 'ṃtropoŀƭn',
'Mexican': 'Meẋƈn',
'middle': 'ṁddḷ',
'middle-class': 'ṁddḷ-claß',
'midnight': 'ṁdṅght',
'midst': 'ṁd§',
'might': 'ṁght',
'migration': 'ṁgɼt¬',
'mild': 'ṁld',
'military': 'ṁŀƭỷ',
'milk': 'ṁlk',
'mill': 'ṁll',
'million': 'ṁll¬',
'mind': 'ṁđ',
'mine': 'ṁṇ',
'mineral': 'ṁṇɼl',
'minimal': 'ṁṅɱl',
'minimum': 'ṁṅmum',
'minister': 'ṁṅsṭr',
'ministry': 'ṁṅ§ỷ',
'minor': 'ṁnor',
'minority': 'ṁnoṙ¥',
'minute': 'ṁnu', 'minutes': 'ṁnus',
'miracle': 'ṁɼcḷ',
'mirror': 'ṁrror',
'missile': 'ṁßiḷ',
'missing': 'ṁßiŋ',
'mission': 'ṁß¬',
'missionary': 'ṁßioɲỷ',
'mistake': 'ṁsƭḳ',
'mix': 'ṁx',
'mixed': 'ṁxð',
'mixture': 'ṁxtuṛ',
'mobile': 'moḃḷ',
'mode': 'moḍ',
'model': 'moḍl',
'moderate': 'moḍɼṭ',
'modern': 'moḍrn',
'modest': 'moḍ§',
'molecule': 'moḷcuḷ',
'mom': 'mom',
'moment': 'moṃ£',
'momentum': 'mome£um',
'money': 'moṇy',
'monitor': 'moṅtor',
'monkey': 'monḳy',
'monster': 'monsṭr',
'month': 'monŧ',
'monthly': 'monŧł',
'monument': 'monuṃ£',
'mood': 'mōd',
'moon': 'mōn',
'moral': 'moɼl',
'more': 'moṛ',
'moreover': 'moṛoṿr',
'morning': 'morṅŋ',
'mortality': 'morƭŀ¥',
'mortgage': 'mortɠg',
'most': 'mo§',
'mostly': 'mo§ł',
'mother': 'moŧer',
'motion': 'mot¬',
'motivation': 'moṫv@¬',
'motive': 'moṫṿ',
'motor': 'motor',
'mountain': 'mônƭin',
'mouse': 'môṣ',
'mouth': 'môŧ',
'move': 'moṿ',
'movement': 'moṿṃ£',
'movie': 'movie',
'Mr.': 'Mr.',
'Mrs': 'Mrs',
'Ms': 'Ms',
'much': 'muħ',
'mud': 'mud',
'multiple': 'mulṫpḷ',
'municipal': 'Muṅċƥl',
'murder': 'murḍr',
'muscle': 'muscḷ',
'museum': 'muṣum',
'mushroom': 'mushrōm',
'music': 'muṡc',
'musical': 'muṡƈl',
'musician': 'muṡċan',
'Muslim': 'Musŀm',
'must': 'mu§',
'mutual': 'mutuø',
'my': 'my',
'myself': 'myṣlf',
'mysterious': 'mysṭṙôs',
'mystery': 'mysṭỷ',
'myth': 'myŧ',

// N- \\
'natural': 'ɲtɼl',

'nail': 'ɲil',
'naked': 'ɲkð',
'name': 'ɲṃ',
'narrative': 'ɲɼṫṿ',
'narrow': 'ɲrow',
'nasty': 'ɲ§y',
'nation': 'ɲt¬',
'national': 'ɲt¬ø',
'nationwide': 'ɲt¬ẇḍ',
'native': 'ɲṫṿ',
'natural': 'ɲtuɼl',
'naturally': 'ɲtuɼł',
'nature': 'ɲtuṛ',
'naval': 'ɲvø',
'near': 'ṇar',
'nearby': 'ṇarby',
'nearly': 'ṇarł',
'neat': 'ṇ@',
'necessary': 'ṇcʂỷ',
'necessarily': 'ṇcesʂṙł',
'necessity': 'ṇcßi¥',
'necessitate': 'ṇceßiƭṭ',
'neck': 'ṇck',
'need': 'nēd', 'needs': 'nēds',
'needed': 'nēdð',
'needing': 'nēḍŋ',
'needle': 'nēdḷ',
'negative': 'ṇɠṫṿ', 'negatives': 'ṇɠṫṿs',
'negotiation': 'ṇgoṫ@¬',
'neighbor': 'ṇighbor',
'neighborhood': 'ṇighborhōd',
'neighboring': 'ṇighboṙŋ',
'neither': 'ṇiŧer',
'nerve': 'ṇrṿ',
'nervous': 'ṇrvôs',
'nest': 'ṇ§',
'net': 'ṇt',
'network': 'ṇtwork',
'neutral': 'ṇutɼl',
'never': 'ṇṿr',
'nevertheless': 'ṇṿrŧeḷß',
'new': 'ṇw',
'newly': 'ṇwł',
'news': 'ṇws',
'newspaper': 'ṇwsƥper',
'next': 'ṇxt',
'nice': 'ṅc',
'night': 'night',
'nightmare': 'ṅghtɱṛ',
'nine': 'ṅṇ',
'no': 'no',
'nobody': 'nobody',
'noise': 'nöṣ',
'nomination': 'noṁɲt¬',
'nominee': 'noṁnē',
'none': 'noṇ',
'nonetheless': 'noṇŧeḷß',
'nonprofit': 'nonproḟt',
'noon': 'nōn',
'nor': 'nor',
'norm': 'norm',
'normal': 'norɱl',
'normally': 'norɱł',
'north': 'norŧ',
'northeast': 'norŧea§',
'northern': 'norŧern',
'northwest': 'norŧẉ§',
'nose': 'noṣ',
'not': 'not',
'note': 'noṭ',
'notebook': 'noṭbōk',
'nothing': 'noŧiŋ',
'notice': 'noṫc',
'notion': 'not¬',
'novel': 'noṿl',
'now': 'now',
'nowhere': 'nowḥṛ',
'nuclear': 'nucḷar',
'number': 'numḅr',
'numerous': 'nuṃrôs',
'nurse': 'nurṣ',
'nut': 'nut',
'nutrient': 'nutṙe£',

// O- \\
'order': 'orḍr',

'oak': 'oak',
'object': 'obje¢',
'objection': 'obje¢¬',
'objective': 'obje¢iṿ',
'obligation': 'obŀg',
'observation': 'obṣrv@¬',
'observer': 'obṣrṿr',
'obstacle': 'obsƭcḷ',
'obvious': 'obviôs',
'obviously': 'obviôsł',
'occasion': 'oƈs¬',
'occasional': 'oƈs¬ø',
'occasionally': 'oƈs¬øł',
'occupation': 'ocuƥt¬',
'ocean': 'ocean',
'odd': 'odd', 'odds': 'odds',
'of': 'of',
'off': 'off',
'offender': 'ofenḍr',
'offense': 'offenṣ',
'offensive': 'offenṡṿ',
'offer': 'offer',
'offering': 'offeṙŋ',
'office': 'ofḟce',
'officer': 'ofḟcer',
'official': 'ofḟċø',
'officially': 'ofḟċøł',
'often': 'ofṭn',
'oil': 'öl',
'okay': 'oƙy',
'old': 'old',
'old-fashioned': 'old-ƒsḣonð',
'Olympic': 'Olymṗc', 'Olympics': 'Olymṗcs',
'on': 'on',
'once': 'onc',
'one': 'oṇ',
'one-third': 'oṇ-ŧird',
'ongoing': 'oŋöŋ',
'onion': 'on¬',
'online': 'onŀṇ',
'only': 'onł',
'onto': 'o£o',
'open': 'open',
'opening': 'opeṅŋ',
'openly': 'openł',
'opera': 'opeɼ',
'operating': 'opeɼṫŋ',
'operation': 'opeɼt¬',
'operator': 'opeɼtor',
'opinion': 'oṗ',
'opponent': 'oppoṇ£',
'opportunity': 'opportuṅ¥',
'opposed': 'opposð',
'opposite': 'oppoṡṭ',
'opposition': 'oppoṡt¬',
'optimistic': 'opṫṁsṫc',
'option': 'opt¬',
'or': 'or',
'oral': 'oɼl',
'orange': 'oɼŋ',
'orbit': 'orḃt',
'order': 'orḍr',
'ordinary': 'orḍɲỷ',
'organ': 'orɠn',
'organic': 'orɠṅc',
'organism': 'orɠṅsm',
'organization': 'org', 'organizations': 'orgs',
'organizational': 'orgɲl',
'organized': 'orɠṅzð',
'orientation': 'oṙenƭt¬',
'origin': 'oṙġn',
'original': 'oṙg',
'originally': 'oṙgɲł',
'other': 'oŧer',
'others': 'oŧers',
'otherwise': 'oŧerẇṣ',
'ought': 'ôght',
'our': 'ôr',
'ours': 'ôrs',
'ourselves': 'ôrṣlṿs',
'out': 'ôt',
'outcome': 'ôtcoṃ',
'outdoor': 'ôtdōr',
'outer': 'ôṭr',
'outfit': 'ôtḟt',
'outlet': 'ôtḷt',
'output': 'ôtput',
'outside': 'ôtṡḍ',
'outsider': 'ôtṡḍr',
'outstanding': 'ôt§anḍŋ',
'oven': 'oṿn',
'over': 'oṿr',
'overall': 'oṿɼl',
'overnight': 'oṿrṅght',
'overwhelming': 'oṿrwḥlṁŋ',
'own': 'own',
'owner': 'owṇr',
'ownership': 'owṇrsḣp',
'oxygen': 'oxygen',

// P- \\
'provide': 'proviḍ', 'provides': 'proviḍs',
'person': 'prs',
'personal': 'prsɲl',
'politic': 'poŀṫc', 'politics': 'poŀṫcs',
'political': 'poŀ',
'probability': 'proɓ',
'probabilities': 'proɓies',
'profession': 'profe',
'professional': 'profeɲl',
'protection': 'prot', 'protections': 'prots',
'public': 'pubŀc',
'publication': 'pubŀ', 'publications': 'pubŀs',
'publishing': 'pubŀsḣŋ',
'progress': 'prog',
'progressive': 'proġṿ',
'progressed': 'progð',
'prerequisite': 'pṛṛq', 'prerequisites': 'pṛṛqs',
'prefer': 'pfr', 'prefers': 'pfrs',
'preferred': 'pṛferṛð',
'preference': 'pṛfeṛnc', 'preferences': 'pṛfeṛnces',

'pace': 'ƥc',
'pack': 'ƥk',
'package': 'ƥƙg',
'pad': 'ƥd',
'page': 'ƥg',
'pain': 'ƥin',
'painful': 'ƥinful',
'paint': 'ƥi£',
'painter': 'ƥinṭr',
'painting': 'ƥinṫŋ',
'pair': 'ƥir',
'palace': 'ƥlac',
'pale': 'ƥḷ',
'Palestinian': 'Ƥḷsṫṅan',
'palm': 'ƥlm',
'pan': 'ƥn',
'panel': 'ƥṇl',
'panic': 'ƥṅc',
'pant': 'ƥ£',
'paper': 'ƥper',
'parade': 'ƥɼḍ',
'parent': 'ƥṛ£ ',
'parental': 'ƥṛnƭl',
'parish': 'ƥṙsh',
'park': 'ƥrk',
'parking': 'ƥrkiŋ',
'part': 'ƥrt',
'partial': 'ƥrṫø',
'partially': 'ƥrṫøł',
'participant': 'ƥrṫċƥ£',
'participation': 'ƥrṫċƥt¬',
'particle': 'ƥrṫcḷ',
'particular': 'ƥrṫcular',
'particularly': 'ƥrṫcularł',
'partly': 'ƥrtł',
'partner': 'ƥṇr', 'partners': 'ƥṇrs',
'partnership': 'ƥsḣp', 'partnerships': 'ƥsḣps',
'party': 'ƥr¥',
'pass': 'ƥß',
'passage': 'ƥʂag',
'passenger': 'ƥßeŋer',
'passing': 'ƥßiŋ',
'passion': 'ƥß¬',
'past': 'ƥ§',
'pasta': 'ƥ§a',
'pastor': 'ƥ§or',
'patch': 'ƥtħ',
'patent': 'ƥṭ£',
'path': 'ƥŧ',
'patience': 'ƥṫenc',
'patient': 'ƥṫe£',
'patrol': 'ƥtrol',
'patron': 'ƥtron',
'pattern': 'ƥṭrn',
'pause': 'ƥuṣ',
'pay': 'ƥy',
'payment': 'ƥyṃ£',
'peace': 'peac',
'peaceful': 'peacful',
'peak': 'peak',
'peanut': 'peanut',
'peasant': 'peaʂ£',
'peer': 'pēr',
'pen': 'pen',
'penalty': 'peɲl¥',
'pencil': 'penċl',
'pension': 'pens¬',
'people': 'ppḷ',
'pepper': 'pepper',
'per': 'per',
'perceived': 'percëvð',
'percentage': 'percenƭg',
'perception': 'percept¬',
'perfect': 'perfe¢',
'perfectly': 'perfe¢ł',
'perform': 'prfrm', 'performs': 'prfrms',
'performance': 'prfɱc', 'performances': 'prfɱcs',
'performer': 'perforṃr',
'perhaps': 'perɦps',
'period': 'peṙod',
'permanent': 'perɱṇ£',
'permission': 'perṁß¬',
'permit': 'perṁt',
'Persian': 'Perṡan',
'person': 'person',
'personal': 'persoɲl',
'personality': 'persoɲŀ¥',
'personally': 'persoɲł',
'personnel': 'personṇl',
'perspective': 'perspecṫṿ',
'pet': 'pet',
'phase': 'pɦṣ',
'phenomenon': 'pḥnoṃnon',
'philosophical': 'pḣlosopḣƈl',
'philosophy': 'pḣlosophy',
'phone': 'phoṇ',
'photo': 'photo',
'photograph': 'photogɼph',
'photographer': 'photogɼpḥr',
'photography': 'photogɼphy',
'phrase': 'phɼṣ',
'physical': 'phyṡƈl',
'physically': 'phyṡƈł',
'physician': 'phyṡċan',
'physics': 'phyṡcs',
'piano': 'ṗano',
'pickup': 'ṗckup',
'picture': 'ṗ¢uṛ',
'pie': 'ṗe',
'piece': 'ṗec',
'pig': 'ṗg',
'pile': 'ṗḷ',
'pill': 'ṗll',
'pillow': 'ṗllow',
'pilot': 'ṗlot',
'pin': 'ṗn',
'pine': 'ṗṇ',
'pink': 'ṗnk',
'pioneer': 'ṗonēr',
'pipe': 'ṗpe',
'pistol': 'ṗ§ol',
'pit': 'ṗt',
'pitch': 'ṗtħ',
'pitcher': 'ṗtħer',
'pizza': 'ṗzza',
'place': 'plac',
'placement': 'placṃ£',
'plain': 'plän',
'plaintiff': 'plänṫff',
'plan': 'plan',
'plane': 'plaṇ',
'planet': 'plaṇt',
'planner': 'planṇr',
'planning': 'planṅŋ',
'plant': 'pla£',
'plastic': 'plasṫc',
'plate': 'plaṭ',
'platform': 'pl@form',
'play': 'play',
'player': 'plaỵr',
'playoff': 'playoff',
'plea': 'pḷa',
'pleasant': 'pḷaʂ£',
'please': 'pḷaṣ',
'pleased': 'pḷasð',
'pleasure': 'pḷasuṛ',
'plenty': 'pḷn¥',
'plot': 'plot',
'plus': 'plus',
'pocket': 'pocḳt',
'poem': 'poem',
'poet': 'poet',
'poetry': 'poetỷ',
'point': 'pö£',
'pole': 'poḷ',
'police': 'poŀc',
'policeman': 'poŀcɱn',
'policy': 'poŀcy',
'political': 'poŀṫƈl',
'politically': 'poŀṫƈł',
'politician': 'poŀṫċan',
'politics': 'poŀṫcs',
'poll': 'poll',
'pollution': 'pollut¬',
'pond': 'pođ',
'pool': 'pōl',
'poor': 'pōr',
'pop': 'pop',
'popular': 'popular',
'popularity': 'populaṙ¥',
'population': 'popul@¬',
'porch': 'porħ',
'pork': 'pork',
'port': 'port',
'portfolio': 'portfoŀo',
'portion': 'port¬',
'portrait': 'portɼit',
'position': 'poṡt¬',
'positive': 'poṡṫve',
'possession': 'poßeß¬',
'possibility': 'poßiḃŀ¥',
'possible': 'poßibḷ',
'possibly': 'poßibł',
'post': 'po§',
'poster': 'posṭr',
'pot': 'pot',
'potato': 'poƭto',
'potential': 'poṭnṫø',
'potentially': 'poṭnṫøł',
'pound': 'pôđ',
'poverty': 'pover¥',
'powder': 'powḍr',
'power': 'poẉr',
'powerful': 'poẉrful',
'practical': 'pɼcṫƈl',
'practically': 'pɼcṫƈł',
'practice': 'pɼcṫce',
'practitioner': 'pɼcṫṫoṇr',
'praise': 'pɼiṣ',
'prayer': 'pɼỵr',
'precious': 'pṛċôs',
'precise': 'pṛċṣ',
'precisely': 'pṛċṣł',
'predator': 'pṛɗtor',
'prediction': 'pṛḍ¢¬',
'preference': 'pṛfeṛnc',
'pregnancy': 'pṛgɲncy',
'pregnant': 'pṛgɲ£',
'preliminary': 'pṛŀṁɲỷ',
'premise': 'pṛṁṣ',
'premium': 'pṛṁum',
'preparation': 'pṛƥɼt¬',
'prescription': 'pṛscṙpt¬',
'presence': 'pṛṣnc',
'present': 'pṛṣ£',
'presentation': 'pṛṣnƭt¬',
'presidency': 'pṛṡḍncy',
'president': 'pṛṡḍ£',
'presidential': 'pṛṡḍnṫø',
'press': 'pṛß',
'pressure': 'pṛßuṛ',
'presumably': 'pṛsuɱbł',
'pretty': 'pṛt¥',
'prevention': 'pṛve£¬',
'previous': 'pṛviôs',
'previously': 'pṛviôsł',
'price': 'pṙc',
'pride': 'pṙḍ',
'priest': 'pṙe§',
'primarily': 'pṙɱṙł',
'primary': 'pṙɱỷ',
'prime': 'pṙṃ',
'principal': 'pṙnċƥø',
'principle': 'pṙnċpḷ',
'print': 'pṙ£',
'prior': 'pṙor',
'priority': 'pṙoṙ¥',
'prison': 'pṙson',
'prisoner': 'pṙsoṇr',
'privacy': 'pṙvacy',
'private': 'pṙvaṭ',
'privately': 'pṙvaṭł',
'privilege': 'pṙviḷg',
'prize': 'pṙẓ',
'pro': 'pro',
'probably': 'proɓbł',
'problem': 'prob', 'problems': 'probs',
'procedure': 'procduṛ',
'process': 'proc',
'processing': 'proċŋ',
'processor': 'procsor',
'producer': 'producer',
'produced': 'producð',
'product': 'prod',
'production': 'produ¢¬',
'productive': 'producṫṿ',
'productivity': 'producṫvi¥',
'profession': 'profeß¬',
'professional': 'profeß¬ø',
'professor': 'prof', 'professors': 'profs',
'profile': 'proḟḷ',
'profit': 'proḟt',
'profound': 'profôđ',
'program': 'prog', 'programs': 'progs',
'programming': 'progṁŋ',
'progress': 'progṛß',
'progressive': 'progṛßive',
'project': 'proje¢',
'projection': 'proje¢¬',
'prominent': 'proṁṇ£',
'promise': 'proṁṣ',
'promising': 'proṁṡŋ',
'promotion': 'promot¬',
'proof': 'prōf',
'proper': 'proper',
'properly': 'properł',
'property': 'prop',
'proportion': 'proport¬',
'proposal': 'propoʂl',
'proposed': 'proposð',
'prosecution': 'proṣ¢¬',
'prosecutor': 'proṣcutor',
'prospect': 'prospe¢',
'protection': 'proṭ¢¬',
'protective': 'proṭ¢iṿ',
'protein': 'proṭin',
'protest': 'proṭ§',
'protocol': 'protocol',
'proud': 'prôd',
'provided': 'providð',
'provider': 'proviḍr',
'province': 'provinc',
'provision': 'provis¬',
'psychology': 'psycgy',
'psychological': 'psycƈl',
'psychologist': 'psyc§',
'public': 'pubŀc',
'publication': 'pubŀƈt¬',
'publicity': 'pubŀċ¥',
'publicly': 'pubŀcł',
'publisher': 'pubŀsḥr',
'pulse': 'pulṣ',
'pump': 'pump',
'punishment': 'puṅshṃ£',
'purchase': 'purcɦṣ',
'pure': 'puṛ',
'purple': 'purpḷ',
'purpose': 'purpoṣ',
'purse': 'purṣ',
'pursuit': 'pursüt',
'puzzle': 'puzḷ',

// Q- \\
'quality': 'quaŀ¥',
'quantity': 'quanṫ¥',
'quarter': 'quarṭr',
'quarterback': 'quarṭrɓk',
'queen': 'quēn',
'quest': 'que§',
'question': 'que§¬',
'questionnaire': 'que§¬ɲiṛ',
'quick': 'qück',
'quickly': 'qückł',
'quiet': 'qüet',
'quietly': 'qüetł',
'quite': 'qüṭ',
'quote': 'quoṭ',

// R- \\
'recent': 'ṛc£', 'recents': 'ṛc£s',
'recently': 'ṛc£ł',
'result': 'ṛsult', 'results': 'ṛsults',
'reason': 'ṛsn', 'reasons': 'ṛsns',
'search': 'ṣarħ', 'searches': 'ṣarħes',
'reproduction': 'ṛprod',
'regional': 'ṛġɲl',
'refining': 'ṛḟṅŋ',
'remember': 'ṛṃb', 'remembers': 'ṛṃbrs',
'record': 'ṛc', 'records': 'ṛcds',
'recording': 'ṛciŋ', 'recordings': 'ṛciŋs',
'refine': 'ṛf', 'refines': 'ṛfs',
'region': 'ṛġ', 'regions': 'ṛġs',
'register': 'ṛg', 'registers': 'ṛgs',
'regulation': 'ṛgul', 'regulations': 'ṛguls',
'relation': 'ṛl', 'relations': 'ṛls',
'relationship': 'ṛlsḣp', 'relationships': 'ṛlsḣps',
'road': 'road', 'roads': 'roads',
'require': 'ṛq', 'requires': 'ṛqs',
'required': 'ṛqð',
'requisite': 'ṛqṡṭ', 'requisites': 'ṛqṡṭs',


'rabbit': 'ɼḃt',
'race': 'ɼc',
'racial': 'ɼċø',
'racism': 'ɼċsm',
'rack': 'ɼck',
'radar': 'ɼɗr',
'radiation': 'ɼḍ@¬',
'radical': 'ɼḍƈl',
'radio': 'ɼḍo',
'rage': 'ɼge',
'rail': 'ɼil',
'railroad': 'ɼilroad',
'rain': 'ɼin',
'rally': 'ɼł',
'ranch': 'ɼnħ',
'random': 'ɼđom',
'range': 'ɼŋe',
'rank': 'ɼnk',
'rape': 'ɼpe',
'rapid': 'ɼṗd',
'rapidly': 'ɼṗdł',
'rare': 'ɼṛ',
'rarely': 'ɼṛł',
'rat': 'ɼt',
'rate': 'ɼṭ',
'rather': 'ɼŧer',
'rating': 'ɼṫŋ',
'ratio': 'ɼṫo',
'rational': 'ɼt¬ø',
'raw': 'ɼw',
're': 're',
'reach': 'ṛaħ',
'reaction': 'ṛa¢¬',
'reader': 'ṛaḍr',
'readily': 'ṛaḍł',
'reading': 'ṛaḍŋ',
'ready': 'ṛady',
'real': 'ṛø',
'realistic': 'ṛaŀsṫc',
'reality': 'ṛaŀ¥',
'really': 'ṛał',
'realm': 'ṛøm',
'rear': 'ṛar',
'reason': 'ṛason',
'reasonable': 'ṛasoɲbḷ',
'rebel': 'ṛḅl',
'receiver': 'ṛcëṿr',
'recent': 'ṛc£',
'recently': 'ṛc£ł',
'reception': 'ṛcpt¬',
'recession': 'ṛceß¬',
'recipe': 'ṛċp', 'recipes': 'ṛċps',
'recipient': 'ṛċṗe£',
'recognized': 'ṛcogṅzð',
'recognition': 'ṛcogṅt¬',
'recommendation': 'ṛcoṃnɗt¬',
'record': 'ṛcord',
'recording': 'ṛcorḍŋ',
'recovery': 'ṛcoṿỷ',
'red': 'rð',
'reduction': 'ṛdu¢¬',
'reference': 'ṛfeṛnc',
'reflection': 'ṛfḷ¢¬',
'reform': 'ṛform',
'refrigerator': 'ṛfṙ',
'refuge': 'ṛfuge',
'refugee': 'ṛfugē',
'regard': 'ṛɠrd',
'regard': 'ṛɠrd',
'regarding': 'ṛɠrḍŋ',
'regardless': 'ṛɠrdḷß',
'regime': 'ṛġṃ',
'region': 'ṛg¬',
'regional': 'ṛġoɲl',
'regular': 'ṛgular',
'regularly': 'ṛgularł',
'regulation': 'ṛgul@¬',
'regulator': 'ṛgul@or',
'regulatory': 'ṛgul@oỷ',
'rehabilitation': 'ṛɦb',
'related': 'ṛl@ð',
'relation': 'ṛl@¬',
'relationship': 'ṛl@¬sḣp',
'relative': 'ṛlaṫv',
'relatively': 'ṛlaṫṿł',
'release': 'ṛḷaṣ',
'relevant': 'ṛḷva£',
'reliability': 'ṛŀaḃŀ¥',
'reliable': 'ṛŀabḷ',
'relief': 'ṛŀef',
'religion': 'ṛŀg¬',
'religious': 'ṛŀġôs',
'reluctant': 'ṛlucƭ£',
'remaining': 'ṛɱiṅŋ',
'remark': 'ṛɱrk',
'remarkable': 'ṛɱrƙbḷ',
'reminder': 'ṛṁnḍr',
'remote': 'ṛmoṭ',
'removal': 'ṛmovø',
'rent': 'ṛ£',
'rental': 'ṛnƭl',
'repair': 'ṛƥir',
'repeatedly': 'ṛpeaṭdł',
'replacement': 'ṛplacṃ£',
'report': 'ṛport',
'reportedly': 'ṛportðł',
'reporter': 'ṛporṭr',
'reporting': 'ṛporṫŋ',
'representation': 'ṛpṛṣnƭt¬',
'representative': 'ṛpṛṣnƭṫṿ',
'republic': 'ṛpubŀc',
'Republican': 'Repubŀƈn',
'republican': 'ṛpubŀƈn',
'reputation': 'ṛpuƭt¬',
'request': 'ṛque§',
'required': 'ṛqürð',
'requirement': 'ṛqüṛṃ£',
'rescue': 'ṛscue',
'research': 'ṛṣarħ', 'researchs': 'ṛṣarħs',
'researcher': 'ṛṣarħer',
'reservation': 'ṛṣrv@¬',
'reserve': 'ṛṣrṿ',
'residence': 'ṛṡḍnc',
'resident': 'ṛṡḍ£',
'residential': 'ṛṡḍnṫø',
'resistance': 'ṛṡsƭnc',
'resolution': 'ṛsolut¬',
'resort': 'ṛsort',
'resource': 'ṛsôrc', 'resources': 'ṛsôrcs',
'respect': 'ṛspe¢',
'respectively': 'ṛspecṫṿł',
'respondent': 'ṛsponḍ£',
'response': 'ṛsponṣ',
'responsibility': 'ṛsponṡḃŀ¥',
'responsible': 'ṛsponṡbḷ',
'rest': 'ṛ§',
'restaurant': 'ṛsƭt', 'restaurants': 'ṛsƭts',
'restriction': 'ṛ§ṙ¢¬',
'result': 'ṛsult',
'retail': 'ṛƭil',
'retailer': 'ṛƭiḷr',
'retired': 'ṛṫrð',
'retirement': 'ṛt',
'retreat': 'ṛtṛ@',
'return': 'ṛturn',
'revelation': 'ṛṿl@¬',
'revenue': 'ṛṿnue',
'review': 'ṛview',
'revolution': 'ṛvolut¬',
'revolutionary': 'ṛvolut¬aỷ',
'reward': 'ṛⱳrd',
'rhetoric': 'rḥtoṙc',
'rhythm': 'rhyŧm',
'rib': 'ṙb',
'ribbon': 'ṙbbon',
'rice': 'ṙce',
'rich': 'ṙħ',
'ride': 'ṙḍ',
'rider': 'ṙḍr',
'ridge': 'ṙdge',
'ridiculous': 'ṙḍculôs',
'rifle': 'ṙfḷ',
'right': 'ṙght',
'rim': 'ṙm',
'ring': 'ṙŋ',
'riot': 'ṙot',
'rise': 'ṙṣ',
'risk': 'ṙsk',
'risky': 'ṙsky',
'ritual': 'ṙtuø',
'rival': 'ṙvø',
'river': 'ṙṿr',
'road': 'road',
'robot': 'robot',
'rock': 'rock',
'rocket': 'rocḳt',
'rod': 'rod',
'role': 'roḷ',
'roll': 'roll',
'rolling': 'rolŀŋs',
'Roman': 'Roɱn',
'romance': 'roɱnc',
'romantic': 'roɱnṫc',
'roof': 'rōf', 'roofs': 'rōfs',
'room': 'rōm', 'rooms': 'rōms',
'root': 'rōt', 'roots': 'rōts',
'rope': 'rope', 'ropes': 'ropes',
'rose': 'roṣ',
'rough': 'rôgh',
'roughly': 'rôghł',
'round': 'rôđ',
'route': 'rôṭ',
'routine': 'rôṫṇ',
'routinely': 'rôṫṇł',
'row': 'row',
'royal': 'royø',
'rubber': 'ruḅr',
'rule': 'ruḷ',
'ruling': 'ruŀŋ',
'rumor': 'rumor',
'run': 'run',
'runner': 'runṇr',
'running': 'runṅŋ',
'rural': 'ruɼl',
'rush': 'rush',
'Russian': 'Rusṡan',

// S- & ss = ß \\
'still': 's~',
'standard': 'sƭnɗrd', 'standards': 'sƭnɗrds',
'secret': 'ṣcṛt',
'secrets': 'ṣcṛts',
'startup': '§up', 'startups': '§ups',
'straight': '§ɼight',
'superpower': 'superpoẉr', 'superpowers': 'superpoẉrs',
'security': 'ṣcu', 'securities': 'ṣcus',
'service': 'ṣrvc', 'services': 'ṣrvcs',
'shareholder': 'sɦṛholḍr', 'shareholders': 'sɦṛholḍrs',
'solution': 'solut¬', 'solutions': 'solut¬s',
'second': 'ṣc', 'seconds': 'ṣcs',
'significant': 'ṡgṅḟƈ£',

'sack': 'ʂck',
'sacred': 'ʂcrð',
'sacrifice': 'ʂcṙḟc',
'sad': 'ʂd',
'safe': 'ʂfe',
'safely': 'ʂfeł',
'safety': 'ʂfe¥',
'sake': 'ʂḳ',
'salad': 'ʂlad',
'salary': 'ʂlaỷ',
'sale': 'ʂḷ', 'sales': 'ʂḷs',
'salmon': 'ʂlmon',
'salt': 'ʂlt',
'same': 'ʂṃ',
'sample': 'ʂmpḷ',
'sanction': 'ʂn¢¬',
'sand': 'ʂđ',
'sandwich': 'ʂđẇħ',
'satellite': 'ʂṭlŀṭ',
'satisfaction': 'ʂṫsƒ¢¬',
'sauce': 'ʂuc',
'saving': 'ʂviŋ',
'scale': 'sƈḷ',
'scandal': 'sƈnɗl',
'scared': 'sƈrð',
'scary': 'sƈỷ',
'scenario': 'sceɲṙo',
'scene': 'sceṇ',
'scent': 'sce£',
'schedule': 'scḥduḷ',
'scheme': 'scḥṃ',
'scholar': 'sħolar',
'scholarship': 'sħolarsḣp',
'school': 'sħo', 'schools': 'sħos',
'science': 'sċ', 'sciences': 'sċs',
'scientific': 'sċḟc',
'scientifically': 'sċḟƈł',
'scientist': 'sċṫ§',
'scope': 'scope',
'score': 'scoṛ',
'screen': 'scrēn',
'screening': 'scrēṅŋ',
'script': 'scṙpt',
'sculpture': 'sculptuṛ',
'sea': 'ṣa',
'seal': 'ṣø',
'search': 'ṣarħ',
'season': 'ṣason',
'seat': 'ṣ@',
'second': 'ṣcođ',
'secondary': 'ṣconɗaỷ',
'secret': 'ṣcṛt',
'secretary': 'ṣcṛƭỷ',
'section': 'ṣ¢¬',
'sector': 'ṣ¢or',
'secular': 'ṣcular',
'secure': 'ṣcuṛ',
'security': 'ṣcuṙ¥',
'see': 'sē',
'seen': 'sēn',
'seem': 'sēm',
'seemingly': 'sēṁŋł',
'seed': 'sēd',
'segment': 'ṣgṃ£',
'seldom': 'ṣldom',
'selected': 'ṣḷ¢ð',
'selection': 'ṣḷ¢¬',
'self': 'ṣlf',
'self-esteem': 'ṣlf-e§ēm',
'seller': 'ṣlḷr',
'seminar': 'ṣṁɲr',
'Senate': 'Seɲt',
'senator': 'ṣɲtor',
'senior': 'ṣṅor',
'sensation': 'ṣnʂt¬',
'sense': 'ṣnṣ',
'sensitive': 'ṣnṡṫṿ',
'sensitivity': 'ṣnṡṫvi¥',
'sensor': 'ṣnsor',
'sentence': 'ṣnṭnc',
'sentiment': 'ṣnṫṃ£',
'separate': 'ṣƥɼṭ', 'separates': 'ṣƥɼṭs',
'separating': 'ṣƥɼṫŋ', 'separatings': 'ṣƥɼṫŋs',
'separation': 'ṣƥɼt¬', 'separations': 'ṣƥɼt¬s',
'sequence': 'ṣquenc',
'series': 'ṣṙes',
'serious': 'ṣṙôs',
'seriously': 'ṣṙôsł',
'servant': 'ṣrva£',
'service': 'ṣrvic',
'serving': 'ṣrviŋ',
'session': 'ṣß¬',
'set': 'ṣt',
'setting': 'ṣtṫŋ',
'settlement': 'ṣttḷṃ£',
'seven': 'ṣṿn',
'seventh': 'ṣṿnŧ',
'several': 'ṣṿɼl',
'severe': 'ṣṿṛ',
'severely': 'ṣṿṛł',
'sex': 'ṣx',
'sexual': 'ṣxuø',
'sexuality': 'ṣxuaŀ¥',
'sexually': 'ṣxuøł',
'sexy': 'ṣxy',
'shade': 'sɦḍ',
'shadow': 'sɦdow',
'shallow': 'sɦlow',
'shame': 'sɦṃ',
'shape': 'sɦp',
'share': 'sɦṛ',
'shared': 'sɦrð',
'shark': 'sɦrk',
'sharp': 'sɦrp',
'sharply': 'sɦrpł',
'she': 'sḥ',
'sheep': 'shēp',
'sheer': 'shēr',
'sheet': 'shēt',
'shelf': 'sḥlf',
'shell': 'sḥl',
'shelter': 'sḥlṭr',
'shift': 'sḣft',
'ship': 'sḣp',
'shirt': 'sḣrt',
'shit': 'sḣt',
'shock': 'shock',
'shoe': 'shoe',
'shooting': 'shōṫŋ',
'shop': 'shop',
'shopping': 'shopṗŋ',
'shore': 'shoṛ',
'short': 'short', 'shorts': 'shorts',
'short-term': 'short-ṭrm',
'shortage': 'shorƭg',
'shortly': 'shortł',
'shot': 'shot',
'should': 'shôld',
'shoulder': 'shôlḍr',
'show': 'show',
'shower': 'shoẉr',
'shrimp': 'shṙmp',
'shuttle': 'shuttḷ',
'shy': 'shy',
'sibling': 'ṡbŀŋ',
'sick': 'ṡck',
'side': 'ṡḍ',
'sidewalk': 'ṡḍⱳlk',
'sight': 'ṡght',
'sign': 'ṡgn',
'signal': 'ṡgɲl',
'signature': 'ṡgɲtuṛ',
'significance': 'ṡgṅḟƈnc',
'significant': 'ṡgṅḟƈ£',
'significantly': 'ṡgṅḟƈ£ł',
'silence': 'ṡḷnc',
'silent': 'ṡḷ£',
'silk': 'ṡlk',
'silly': 'ṡlł',
'silver': 'ṡlṿr',
'similar': 'ṡṁlar',
'similarity': 'ṡṁlaṙ¥',
'similarly': 'ṡṁlarł',
'simple': 'ṡmpḷ',
'simply': 'ṡmpł',
'simultaneously': 'ṡmulƭṇôsł',
'sin': 'ṡn',
'since': 'ṡnc',
'singer': 'ṡŋer',
'single': 'ṡŋḷ',
'sink': 'ṡnk',
'sir': 'ṡr',
'sister': 'ṡsṭr',
'site': 'ṡṭ',
'situation': 'ṡtu@¬',
'six': 'ṡx',
'sixth': 'ṡxŧ',
'size': 'ṡẓ',
'skill': 'skl', 'skills': 'skls',
'skilled': 'skillð',
'skin': 'skin',
'skirt': 'skirt',
'skull': 'skull',
'sky': 'sky',
'slave': 'slaṿ',
'slavery': 'slaṿỷ',
'sleep': 'slēp',
'sleeve': 'slēṿ',
'slice': 'sŀc',
'slide': 'sŀḍ',
'slight': 'sŀght',
'slightly': 'sŀghtł',
'slope': 'slope',
'slot': 'slot',
'slow': 'slow',
'slowly': 'slowł',
'small': 'sɱl',
'smart': 'sɱrt',
'smell': 'sṃl',
'smile': 'sṁḷ',
'smoke': 'smoḳ',
'smooth': 'smōŧ',
'snake': 'sɲḳ',
'snow': 'snow',
'so': 'so',
'so-called': 'so-ƈlð',
'soap': 'soap',
'soccer': 'soccer',
'social': 'soc',
'socially': 'socł',
'society': 'soċe¥',
'sock': 'sock',
'sodium': 'soḍum',
'sofa': 'soƒ',
'soft': 'soft',
'softly': 'softł',
'software': 'softⱳṛ',
'soil': 'söl',
'solar': 'solar',
'soldier': 'solḍer',
'sole': 'soḷ',
'solely': 'soḷł',
'solid': 'soŀd',
'solution': 'solut¬',
'some': 'soṃ',
'somebody': 'soṃbody',
'someday': 'soṃɗy',
'somehow': 'soṃhow',
'someone': 'soṃoṇ',
'something': 'soṃŧiŋ',
'sometime': 'soṃṫṃ',
'sometimes': 'soṃṫṃs',
'somewhat': 'soṃw@',
'somewhere': 'soṃwḥṛ',
'son': 'son',
'song': 'soŋ',
'soon': 'sōn',
'sophisticated': 'sopḣsṫƈtð',
'sorry': 'sorỷ',
'sort': 'sort',
'soul': 'sôl',
'sound': 'sôđ',
'soup': 'sôp',
'source': 'sôrc',
'south': 'sôŧ',
'southeast': 'sôŧea§',
'southern': 'sôŧern',
'southwest': 'sôŧẉ§',
'sovereignty': 'soṿṛign¥',
'Soviet': 'Soviet',
'space': 'sƥc',
'Spanish': 'Sƥṅsh',
'speaker': 'speaḳr',
'speaking': 'speakiŋ',
'special': 'speċø',
'specialist': 'speċøi§',
'specialty': 'speċØ¥',
'species': 'speċes',
'specific': 'speċḟc',
'specifically': 'speċḟcøł',
'spectacular': 'specƭcular',
'spectrum': 'spe¢rum',
'speculation': 'specul@¬',
'speech': 'spēħ',
'speed': 'spēd',
'spending': 'spenḍŋ',
'sphere': 'spḥṛ',
'spine': 'sṗṇ',
'spirit': 'sṗṙt',
'spiritual': 'sṗṙtuø',
'spite': 'sṗṭ',
'spokesman': 'spoḳsɱn',
'sponsor': 'sponsor',
'spoon': 'spōn',
'sport': 'sport',
'spot': 'spot',
'spouse': 'spôṣ',
'spray': 'spɼy',
'spread': 'spṛad',
'spring': 'spṙŋ',
'spy': 'spy',
'squad': 'squad',
'square': 'squṛ',
'stability': 'sƭḃŀ¥',
'stable': 'sƭbḷ',
'stack': 'sƭck',
'stadium': 'sƭḍum',
'staff': 'sƭf',
'stage': 'sƭge',
'stair': 'sƭir',
'stake': 'sƭḳ',
'stance': 'sƭnc',
'stand': 'sƭđ',
'standing': 'sƭnḍŋ',
'star': 'sƭr',
'start': 'sƭrt', 'starts': 'sƭrts',
'starter': 'sƭrṭr',
'starting': 'sƭrṫŋ',
'state': 'sƭṭ',
'started': 'sƭrtð',
'statement': 'sƭṭṃ£',
'station': 'sƭt¬',
'statistical': 'sƭtsƈl',
'statistics': 'sƭts',
'statue': 'sƭtue',
'status': 'sƭtus',
'statute': 'sƭtuṭ',
'stay': 'sƭy',
'steadily': '§eaḍł',
'steady': '§eady',
'steak': '§eak',
'steam': '§am',
'steel': '§ēl',
'steep': '§ēp',
'stem': '§em',
'step': '§ep',
'stereotype': '§eṛo¥pe',
'stick': '§ick',
'stiff': '§iff',
'stimulus': '§imulus',
'stock': '§ock',
'stomach': '§oɱħ',
'stone': '§oṇ',
'stop': '§op',
'storage': '§oɼg',
'store': '§oṛ',
'storm': '§orm',
'story': '§oỷ',
'stove': '§koṿ',
'straight': '§ɼight',
'strain': '§ɼin',
'strange': '§ɼŋe',
'stranger': '§ɼŋer',
'strategic': '§ɼṭġc',
'strategy': '§ɼṭgy',
'straw': '§ɼw',
'streak': '§ṛak',
'stream': '§ṛam',
'street': '§rēt', 'streets': '§rēts',
'strength': '§ṛŋŧ',
'stress': '§ṛß',
'stretch': '§ṛtħ',
'strict': '§ṙ¢',
'strictly': '§ṙ¢ł',
'strike': '§ṙḳ',
'striking': '§ṙkiŋ',
'string': '§ṙŋ',
'strip': '§ṙp',
'stroke': '§roḳ',
'strong': '§roŋ',
'strongly': '§troŋł',
'structural': '§ru¢uɼl',
'structure': '§ru¢uṛ',
'struggle': '§ruggḷ',
'student': '§uḍ£',
'studio': '§uḍo',
'study': '§tudy',
'stuff': '§uff',
'stupid': '§uṗd',
'style': '§yḷ',
'subject': 'subje¢',
'subsequent': 'subṣque£',
'subsidy': 'subṡdy',
'substance': 'subsƭnc',
'substantial': 'subsƭnṫø',
'substantially': 'subsƭnṫøł',
'subtle': 'subtḷ',
'suburb': 'suburb',
'suburban': 'suburɓn',
'success': 'suceß',
'successful': 'suceßful',
'successfully': 'suceßfuł',
'such': 'suħ',
'sudden': 'suḍn',
'suddenly': 'suḍnł',
'suffering': 'suffeṙŋ',
'sufficient': 'sufḟċ£',
'sugar': 'suɠr',
'suggestion': 'sugge§¬',
'suicide': 'süċḍ',
'suit': 'süt',
'suitable': 'süƭbḷ',
'suite': 'süṭ',
'sum': 'sum',
'summary': 'suɱỷ',
'summer': 'suṃr',
'summit': 'sumṁt',
'sun': 'sun',
'sunlight': 'sunŀght',
'sunny': 'sunny',
'super': 'super',
'superior': 'supeṙor',
'supermarket': 'superɱrḳt',
'supervisor': 'supervisor',
'supplier': 'suppŀer',
'supply': 'suppł',
'support': 'support',
'supporter': 'supporṭr',
'supportive': 'supporṫṿ',
'supposed': 'supposð',
'supposedly': 'supposðł',
'Supreme': 'Supṛṃ',
'sure': 'suṛ',
'surely': 'suṛł',
'surface': 'surƒc',
'surgeon': 'surgeon',
'surgery': 'surgeỷ',
'surprise': 'surpṙṣ',
'surprised': 'surpṙsð',
'surprising': 'surpṙṡŋ',
'surprisingly': 'surpṙṡŋł',
'surrounding': 'surrônḍŋ',
'surveillance': 'surṿilanc',
'survey': 'surṿy',
'survival': 'survivø',
'survivor': 'survivor',
'suspect': 'suspe¢',
'suspicion': 'susṗc¬',
'suspicious': 'susṗċôs',
'sustainable': 'susƭiɲbḷ',
'sweat': 'sẉ@', 'sweats': 'swe@s',
'sweater': 'sẉ@er',
'sweet': 'swēt',
'swimming': 'sẇmṁŋ',
'swing': 'sẇŋ',
'switch': 'sẇtħ',
'sword': 'sword',
'symbol': 'symbol',
'symbolic': 'symboŀc',
'sympathy': 'symƥŧy',
'symptom': 'symptom',
'syndrome': 'syđroṃ',
'system': 'sys', 'systems': 'syß',

// T- \\
'the': 't',
'these': 'ŧṣ',
'there': 'ŧeṛ',
'thereby': 'ŧeṛby',
'think': 'ŧink',
'thinking': 'ŧinkŋ',
'take': 'ƭḳ',
'through': 'ŧrôgh',
'test': 'ṭ§', 'tests': 'ṭ§s',
'testing': 'ṭsṫŋ', 'testings': 'ṭsṫŋs',
'tomorrow': 'tmrw',
'technology': 'ṭħ', 'technologies': 'ṭħs',

'T-shirt': 'T-sḣrt',
'table': 'ƭbḷ',
'tablespoon': 'ƭbḷspōn',
'tactic': 'ƭcṫc',
'tag': 'ƭg',
'tail': 'ƭil',
'tale': 'ƭḷ',
'talent': 'ƭḷ£',
'talented': 'ƭḷ£ð',
'talk': 'ƭlk',
'tall': 'ƭl',
'tank': 'ƭnk',
'tape': 'ƭpe',
'target': 'ƭrget',
'task': 'ƭsk', 'tasks': 'ƭsks',
'taste': 'ƭsṭ',
'tax': 'ƭx',
'taxpayer': 'ƭxƥỵr',
'tea': 'ṭa',
'teacher': 'ṭacḥr', 'teachers': 'ṭacḥrs',
'teaching': 'ṭacḣŋ',
'team': 'ṭam',
'teammate': 'ṭamɱṭ',
'tear': 'ṭar',
'teaspoon': 'ṭaspōn',
'technical': 'ṭħṅƈl',
'technician': 'ṭħṅċan',
'technique': 'ṭħṅque',
'technological': 'ṭħnoloġƈl',
'technology': 'ṭħnology',
'teen': 'tēn',
'teenage': 'tēɲge',
'teenager': 'tēɲger',
'telephone': 'ṭl', 'telephones': 'ṭls',
'telescope': 'ṭḷscope',
'television': 'ṭḷvis¬',
'temperature': 'ṭmpeɼtuṛ',
'temple': 'ṭmpḷ',
'temporary': 'ṭmp',
'ten': 'ṭn',
'tendency': 'ṭnḍncy',
'tender': 'ṭnḍr',
'tennis': 'ṭnṅs',
'tension': 'ṭns¬',
'tent': 'ṭ£',
'term': 'ṭrm', 'terms': 'ṭrms',
'terrain': 'ṭɼin',
'terrible': 'ṭrṙbḷ',
'terribly': 'ṭrṙbł',
'terrific': 'ṭrṙḟc',
'territory': 'ṭrṙtoỷ',
'terror': 'ṭrror',
'terrorism': 'ṭrroṙsm',
'terrorist': 'ṭrroṙ§',
'test': 'ṭ§',
'testimony': 'ṭsṫimony',
'testing': 'ṭ§iŋ',
'text': 'ṭxt',
'textbook': 'ṭxtbōk',
'texture': 'ṭxtuṛ',
'than': 'ŧan',
'thanks': 'ŧanks',
'Thanksgiving': 'ŧanksġviŋ',
'that': 'ŧ@',
'theater': 'ŧeaṭr',
'their': 'ŧër',
'them': 'ŧem',
'theme': 'ŧeṃ',
'themselves': 'ŧemṣlṿs',
'then': 'ŧen',
'theological': 'ŧeoloġƈl',
'theology': 'ŧeology',
'theoretical': 'ŧeoṛṫƈl',
'theory': 'ŧeoỷ',
'therapist': 'ŧeɼṗ§',
'therapy': 'ŧeɼpy',
'There': 'Ŧeṛ',
'thereby': 'ŧeṛby',
'therefore': 'ŧeṛfoṛ',
'these': 'ŧeṣ',
'they': 'ŧey',
'thick': 'ŧick',
'thigh': 'ŧigh',
'thin': 'ŧin',
'thing': 'ŧiŋ',
'thinking': 'ŧinkiŋ',
'third': 'ŧird',
'thirty': 'ŧir¥',
'this': 'ŧis',
'thoroughly': 'ŧorôghł',
'those': 'ŧoṣ',
'though': 'ŧôgh',
'thought': 'ŧôght',
'thousand': 'ŧôʂđ',
'thread': 'ŧṛad',
'threat': 'ŧṛ@',
'three': 'ŧrē',
'threshold': 'ŧṛshold',
'throat': 'ŧro@',
'through': 'ŧrôgh',
'throughout': 'ŧrôghôt',
'thumb': 'ŧumb',
'thus': 'ŧus',
'ticket': 'ṫcḳt',
'tide': 'ṫḍ',
'tie': 'ṫe',
'tight': 'ṫght',
'tightly': 'ṫghtł',
'tile': '~e',
'till': '~',
'timber': 'ṫmḅr',
'time': 'ṫṃ',
'timing': 'ṫṁŋ',
'tiny': 'ṫny',
'tip': 'ṫp',
'tired': 'ṫrð',
'tissue': 'ṫßue',
'title': 'ṫtḷ',
'to': 'to',
'tobacco': 'toɓco',
'today': 'toɗy',
'toe': 'toe',
'together': 'togeŧer',
'toilet': 'töḷt',
'tolerance': 'toḷɼnc',
'toll': 'toll',
'tomato': 'toɱto',
'tomorrow': 'tomorrow',
'tone': 'toṇ',
'tongue': 'toŋue',
'tonight': 'toṅght',
'too': 'tō',
'tool': 'tōl',
'tooth': 'tōŧ',
'top': 'top',
'topic': 'toṗc',
'total': 'toƭl',
'totally': 'toƭł',
'touch': 'tôħ',
'touchdown': 'tôħdown',
'tough': 'tôgh',
'tour': 'tôr',
'tourism': 'tôṙsm',
'tourist': 'tôṙ§',
'tournament': 'tôrɲṃ£',
'toward': 'toⱳrd',
'towards': 'toⱳrds',
'towel': 'toẉl',
'tower': 'toẉr',
'town': 'town',
'toxic': 'toẋc',
'toy': 'toy',
'trace': 'tɼce',
'track': 'tɼck',
'trade': 'tɼḍ',
'trading': 'tɼḍŋ',
'tradition': 'tɼdt¬',
'traditional': 'tɼd',
'traditionally': 'tɼdɲł',
'traffic': 'tɼḟc',
'tragedy': 'tɼgðy',
'tragic': 'tɼġc',
'trail': 'tɼil',
'trailer': 'tɼiḷr',
'train': 'tɼin',
'trainer': 'tɼiṇr',
'training': 'tɼiṅŋ',
'trait': 'tɼit',
'transaction': 'tɼnʂ¢¬',
'transfer': 'tɼnsfer',
'transformation': 'tɼnsforɱt¬',
'transit': 'tɼnṡt',
'transition': 'tɼnṡt¬',
'translation': 'tɼnsl@¬',
'transmission': 'tɼnsṁß¬',
'transport': 'tɼnsport',
'transportation': 'tɼnsporƭt¬',
'trap': 'tɼp',
'trash': 'tɼsh',
'trauma': 'tɼuɱ',
'travel': 'tɼṿl',
'traveler': 'tɼṿḷr',
'tray': 'tɼy',
'treasure': 'tṛasuṛ',
'treatment': 'tṛ@ṃ£',
'treaty': 'tṛa¥',
'tree': 'trē',
'tremendous': 'tṛṃđôs',
'trend': 'tṛđ',
'trial': 'tṙø',
'tribal': 'tṙɓl',
'tribe': 'tṙḅ',
'trick': 'tṙck',
'trip': 'tṙp',
'triumph': 'tṙumph',
'troop': 'trōp',
'tropical': 'troṗƈl',
'trouble': 'trôbḷ',
'troubled': 'trôblð',
'truck': 'truck',
'true ': 'true',
'truly': 'truly',
'trunk': 'trunk',
'trust': 'tru§',
'truth': 'truŧ',
'tube': 'tuḅ',
'tumor': 'tumor',
'tune': 'tuṇ',
'tunnel': 'tunṇl',
'turkey': 'turḳy',
'turn': 'turn',
'TV': 'TV',
'twelve': 'tẉlṿ',
'twentieth': 'tẉnṫeŧ',
'twenty': 'tẉn¥',
'twice': 'tẇce',
'twin': 'tẇn',
'twist': 'tẇ§',
'two': 'two',
'two-thirds': 'two-ŧirds',
'type': '¥pe',
'typical': '¥ṗƈl',
'typically': '¥ṗƈł',

// U- \\
'under': 'unḍr',
'understand': 'unḍrƭd',
'utility': 'u~i¥',

'ugly': 'ugly',
'ultimate': 'ulṫɱṭ',
'ultimately': 'ulṫɱṭł',
'unable': 'uɲbḷ',
'uncertain': 'uncrƭin',
'uncertainty': 'uncrƭin¥',
'uncle': 'uncḷ',
'uncomfortable': 'uncomforƭbḷ',
'under': 'unḍr',
'undergraduate': 'unḍrgɼduaṭ',
'underlying': 'unḍrlẏŋ',
'understanding': 'unḍrsƭnḍŋ',
'unemployment': 'uṇmployṃ£',
'unexpected': 'uṇxpe¢ð',
'unfair': 'unƒir',
'unfortunately': 'unfortuɲṭł',
'unhappy': 'unɦpy',
'uniform': 'uṅform',
'union': 'un¬',
'unique': 'uṅque',
'unit': 'uṅt',
'United': 'Uṅtð',
'unity': 'uṅ¥',
'universal': 'uṅṿrʂl',
'universe': 'uṅṿrṣ',
'university': 'uṅ',
'unknown': 'unknown',
'unless': 'unḷß',
'unlike': 'unŀḳ',
'unlikely': 'unŀḳł',
'unprecedented': 'unpṛceḍ£ð',
'until': 'un~',
'unusual': 'unusuø',
'up': 'up',
'upon': 'upon',
'upper': 'upper',
'upset': 'upṣt',
'upstairs': 'up§ärs',
'urban': 'urɓn',
'us': 'us',
'use': 'uṣ',
'used': 'usð',
'useful': 'uṣful',
'user': 'uṣr',
'usual': 'usuø',
'usually': 'usuøł',

// V- \\
'validate': 'vaŀɗṭ', 'validate': 'vaŀɗṭs',

'vacation': 'vaƈt¬',
'vaccine': 'vacċṇ',
'vacuum': 'vacūm',
'valid': 'vaŀd',
'validity': 'vaŀḍ¥',
'valley': 'vaḷy',
'valuable': 'vøuabḷ',
'value': 'vø',
'van': 'van',
'variable': 'var',
'variation': 'vaṙ@¬',
'variety': 'vaṙe¥',
'various': 'vaṙôs',
'vast': 'va§',
'vegetable': 'ṿg',
'vehicle': 'ṿḣcḷ',
'vendor': 'ṿđor',
'venture': 'ṿ£uṛ',
'verbal': 'ṿrɓl',
'verdict': 'ṿrḍ¢',
'version': 'ṿrs¬',
'versus': 'ṿrsus',
'vertical': 'ṿrṫƈl',
'very': 'ṿỷ',
'vessel': 'ṿsṣl',
'veteran': 'ṿṭɼn',
'via': 'via',
'victim': 'vicṫm',
'victory': 'vi¢oỷ',
'video': 'viḍo',
'view': 'view',
'viewer': 'vieẉr',
'village': 'vilg',
'violation': 'viol@¬',
'violence': 'vioḷnc',
'violent': 'vioḷ£',
'virtual': 'virtuø',
'virtually': 'virtuøł',
'virtue': 'virtue',
'virus': 'virus',
'visible': 'viṡbḷ',
'vision': ' vis¬',
'visit': 'viṡt',
'visitor': 'viṡtor',
'visual': 'visuø',
'vital': 'viƭl',
'vitamin': 'vit',
'vocal': 'voƈl',
'voice': 'vöc',
'volume': 'voluṃ',
'voluntary': 'volunƭỷ',
'volunteer': 'volu£ēr',
'vote': 'voṭ',
'voter': 'voṭr',
'voting': 'voṫŋ',
'vulnerable': 'vulṇɼbḷ',

// W- \\
'wait': 'ⱳit',
'work': 'work',
'working': 'wrkiŋ',
'worked': 'worḳd',

'wage': 'ⱳge',
'wagon': 'ⱳgon',
'waist': 'ⱳi§',
'wake': 'ⱳḳ',
'walk': 'ⱳlk',
'walking': 'ⱳlkiŋ',
'wall': 'ⱳl',
'war': 'ⱳr',
'warehouse': 'ⱳṛhôṣ',
'warm': 'ⱳrm',
'warmth': 'ⱳrmŧ',
'warning': 'ⱳrṅŋ',
'warrior': 'ⱳṙor',
'waste': 'ⱳ§e',
'watch': 'ⱳtħ',
'water': 'ⱳṭr',
'wave': 'ⱳṿ',
'way': 'ⱳy',
'we': 'ẉ',
'weak': 'ẉak',
'weakness': 'ẉakṇß',
'wealth': 'ẉøŧ',
'wealthy': 'ẉøŧy',
'weapon': 'ẉapon',
'weather': 'ẉaŧer',
'web': 'ẉb',
'wedding': 'ẉdḍŋ',
'weed': 'wēd',
'week': 'wēk',
'weekend': 'wēḳđ',
'weekly': 'wēkł',
'weight': 'ẉight',
'weird': 'ẉird',
'welcome': 'ẉlcoṃ',
'welfare': 'ẉlƒṛ',
'well': 'ẉl',
'well-being': 'ẉll-ḅiŋ',
'well-known': 'ẉll-known',
'west': 'ẉ§',
'western': 'ẉ§ern',
'wet': 'ẉt',
'whale': 'wɦḷ',
'what': 'w@',
'whatever': 'w@eṿr',
'wheat': 'wḥ@',
'wheel': 'whēl',
'wheelchair': 'whēlħär',
'when': 'wḥn',
'whenever': 'wḥṇṿr',
'where': 'wḥṛ',
'whereas': 'wḥṛas',
'wherever': 'wḥṛṿr',
'whether': 'wḥŧer',
'which': 'wḣħ',
'while': 'wḣḷ',
'white': 'wḣṭ',
'who': 'who',
'whoever': 'whoeṿr',
'whole': 'whoḷ',
'whom': 'whom',
'whose': 'whoṣ',
'why': 'y',
'wide': 'ẇḍ',
'widely': 'ẇḍł',
'widespread': 'ẇḍspṛad',
'widow': 'ẇdow',
'wife': 'ẇfe',
'wild': 'ẇld',
'wilderness': 'ẇlḍrṇß',
'wildlife': 'ẇldŀfe',
'will': 'ẇl',
'willing': 'ẇlŀŋ',
'willingness': 'ẇlŀŋṇß',
'win': 'ẇn',
'wind': 'ẇđ',
'window': 'ẇđow',
'wine': 'ẇṇ',
'wing': 'ẇŋ',
'winner': 'ẇnṇr',
'winter': 'ẇnṭr',
'wire': 'ẇṛ',
'wisdom': 'ẇsdom',
'wise': 'ẇṣ',
'wish': 'ẇsh',
'with': 'ẇ',
'withdrawal': 'ẇŧdɼⱳl',
'within': 'ẇŧin',
'without': 'ẇôt',
'witness': 'ẇtṇß',
'wolf': 'wolf',
'woman': 'woɱn',
'wonder': 'wonḍr',
'wonderful': 'wonḍrful',
'wood': 'wōd',
'wooden': 'wōḍn',
'word': 'word',
'work': 'work', 'works': 'works',
'worker': 'worḳr',
'working': 'workiŋ',
'workout': 'workôt',
'workplace': 'workplac',
'workshop': 'workshop',
'world': 'world',
'worldwide': 'worldẇḍ',
'worried': 'worṙð',
'worry': 'worỷ',
'worth': 'worŧ',
'would': 'wôld',
'wound': 'wôđ',
'wrist': 'wṙ§',
'writer': 'wṙṭr',
'writing': 'wṙṫŋ',
'written': 'wṙtṭn',
'wrong': 'wroŋ',

// Y- \\
'yard': 'yard',
'year': 'ỵar', 'years': 'ỵars',
'yellow': 'ỵllow',
'yes': 'ỵs',
'yesterday': 'ỵsṭrɗy',
'yet': 'ỵt',
'yield': 'ẏeld',
'you': 'u',
'young': 'yôŋ',
'youngster': 'yôŋ§er',
'your': 'ur', 'yours': 'urs',
'yourself': 'urṣlf',
'youth': 'yôŧ',

// Z-\
'zone': 'zoṇ',

}

const txt_body = document.getElementById('txt_body');
const p_block = document.getElementById('p_block');
const p_txt = document.getElementById('p_txt');
const p_boustrophedon = document.getElementById('p_boustrophedon');

// const txt = 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz'
// // line-length: 93 characters.
// // p_block limit: 93 characters.
// console.log(txt.length)

// If a text length is 93, split it. At every other
// line thou shall transform in boustrophedon.

function transformBoustrophedon(txt) {
  let original_array = txt.split(" ").reverse();

  const result = original_array.join('&#32;');

  const words = result.split("&#32;")
  // const words = original_array
  for(let i = 0; i < words.length; i++) {

    for(let j = 0; j < words[i].length; j++) {
      if ((words[i][j]) == ".") {
        // slice the punctuation and place the same punctuaction at the beginning
        const punctuaction = words[i].slice(0, j)
        // place at the beginning
        words[i] = `.${punctuaction}`
        // console.log(words)
      } else if ((words[i][j]) == ",") {
        const punctuaction = words[i].slice(0, j)
        words[i] = `,${punctuaction}`
      } else if ((words[i][j]) == "?") {
        const punctuaction = words[i].slice(0, j)
        words[i] = `?${punctuaction}`
      }
    }

  }

  // console.log(words)

  const resultado = words.join('&#32;');

  return resultado;
}



const str = formatting(text)

// cut the str at the 93th character before a whitespace
// const result = str.match(/.{1,93}/gs) ?? [];
const result = str.match(/.{1,93}\s/g) ?? [];



function formatting(text) {
  const words = text.split(" ")

  for (let word of  words) {
    if(abbreviation.hasOwnProperty(word)) words[words.indexOf(word)] = abbreviation[word] //`<span class="abbreviation">${abbreviation[word]}</span>`
  } 
 
  return words.join(" ")
}


function b(arr) {
  const newArr = arr;
  for(let i = 1; i < newArr.length; i += 2) {
    newArr[i] = '<span class="boustrophedon">' + transformBoustrophedon(newArr[i]) + '</span>';
  }

  return newArr;
}

p_block.innerHTML = b(result).join("<br>");


// Ɱḳ t word forɱttð for capslock n pounctuat¬ words to work \\
function test(text) {
  const words = text.split(" ")

  for (let word of words) {
    for (let char of word) {
      console.log(char)
      if (char == '.') {
         
      }
    }
  } 
 
  return words.join(" ")
}


console.log(test('amazing.'))