/*
Trnsfrm english suffixes into fonetic letters, such
as ing = ŋ » e.g. driving » drivŋ
*/
// makiŋ t wrds shorter wi mor alphabet, i.e. ss = ß
// 

/*
Symbols available
- æ
"!@#$%¨&*()_+/*- `{}^:><|?
¬¹²³£¢¬{[]}\§ª´~º.·─ˇ°/?°®ŧ←↓→øþ´łĸˀħŋđðßæ«»©“”nµ─n·̣
¬½¾¼⅜¨⅞™±°¿˛¯`^º˙̣  ÷× <˘/?°®Ŧ¥↑ıØÞ˝Ł&̛ĦŊªÐ§Æ<>©‘’Nµ
 
# DIGRAPH to Letter

¨ means i after the vowel, i.e. ai = ä
1. ai = ä » e.g. available = avälable | 107
2. ei = ë » | 26
3. oi = ö » | 19
4. ui = ü » | 52
5. ee = ē » between = betwēn | 106
6. oo = ō » hood = hōd | 94
7. uu = ū » vacuum = vacūm | 1
au = â
ou = ô
iu

ęąǫų

8. ss = ß » assault = aßault | 158

10. ng = ŋ » authoring = authoriŋ, along = aloµ | 368
11. th = ŧ » authoring = auŧoring | 270
12. ch = ħ » champion = ħampion | 173

13. ed = ð » balanced = balancð n Education = Ðucation | 183
14. de = d » attitude = attitud | 272
15. at = @ » attitude = @itude | 496
16. mi = µ » administrator = adµnistrator | 146
17. ion = ¬ » evaluation = evalu@¬ | 313
18. til = ~ » still = s~ | 7

22. st = § | 452
al = | 445
nt = ¢? » want = wa¢ | 503 
ty = ¥? » ability = abili¥ | 127
nd
tic

igh 
oa
oo
ar
or
ur


ear
air
ure
er 

# Consonant blends or consonant digraph
1. bl
2. br
3. ch
4. ck
5. cl
6. cr
7. dr
8. fl
9. fr
10. gh
11. gl
12. gr
13. ng
14. ph
15. pl
16. pr
17. qu
18. sc
19. sh
20. sk
21. sl
22. sm
23. sn
24. sp
25. st
26. sw
27. th
28. tr
29. tw
30. wh
31. wr


# TRIGRAPHS
1. nth | 5
2. sch | 10
3. scr | 8
4. shr | 2
5. spl | 5
6. spr | 11
7. squ | 3
8. str | 91
9. thr | 15

# VOWEL DIGRAPH
. au
. aw
. ay
. ea
. eu
. ew
. ey
. ie
. oo
. ou
. ow
. oy

BLEND

vowel: 
      x,x,x,x,x,x,-,x,-,x,x,
1.a » ɓ,ƈ,ɗ,ƒ,ɠ,ɦ, ,ƙ, ,ɱ,ɲ,ƥ,ʠ,ɼ,ʂ,ƭ,ʋ,ⱳ, ,ỷ,ȥ

2.e » ḅ,c,ḍ,þ,ø,ḥ, ,ḳ,ḷ,ṃ,ṇ,1, ,ṛ,ṣ,ṭ,ṿ,ẉ, ,ỵ,ẓ

3.i » ḃ,ċ,ḋ,ḟ,ġ,ḣ,ȷ, ,ŀ,ṁ,ṅ,ṗ, ,ṙ,ṡ,ṫ, ,ẇ,ẋ,ẏ,ż

4.o » ḇ,©,ḏ,£, ,ẖ, ,ḵ,ḻ, ,ṉ, , ,ṟ, ,ṯ, , , , ,ẕ

5.u » đĸ

6.y » -,-,-,-,-,-,-,-,ł
consonant: 
1.b,
2.c,
3.d,
4.f,
5.g,
6.h,
7.j,
8.k,
9.l,
10.m,
11.n,
12.p,
13.q,
14.r,
15.s,
16.t,
17.v,
18.w,
19.x,
20.y,
21.z

*/

/*
SUFFIXES
1. anti » 
2. de
3. dis
4. en, im
5. fore
6. in, im
7. 
8.
9.
10.
11.
12.
13.
14.
15.
16.
17.
18.
19.
20.

*/


const abbreviation = {
  // ·ment = mt 
// ing = ng
// cal = al
'for': 'f',
'you': 'u',
'your': 'ur',
'yours': 'urs',
'with': 'wi',
'without': 'wiot',
'want': 'wnt',
'will': 'wl',
'well': 'wel',
'would': 'wld',
'when': 'whn',
'whenever': 'whnvr',
'have': 'ɦv',
'having': 'ɦvŋ',
'here': 'hr',
'know': 'kw',
'knowledge': 'kwldg',
'just': 'jst',
'unlike': 'unlk',
'unlikely': 'unlkly',
'much': 'mh',
'very': 'v',
'back': 'ɓk',
'should': 'shld',
'really': 'rł',
'right': 'rt',
'rights': 'rts',
'feel': 'fl',
'great': 'gr@',
'keep': 'kp',
'keeps': 'kps',
'keeping': 'kpng',
'happen': 'ɦpn',
'last': 'lt',
'recovery': 'rcvry',
'overcome': 'ovrcm',
'week': 'wk',
'question': 'qstn', 'questions': 'qstn·s',
'read': 'r·d',
'seem': 'sēm',
'family': 'ƒmł',
'maybe': 'ɱyb',
// A- \\
'are': 'r',
'ability': 'ablty',
'able': 'abl',
'abortion': 'abrtn',
'about': 'abt',

'above': 'abv',
'abroad': 'abrd',
'absence': 'absnc',
'absolute': 'abslt',
'absolutely': 'absltly',
'abstract': 'abstract',
'abuse': 'abse',
'academic': 'aƈdmc',
'accent': 'acnt',
'acceptable': 'acptbl',
'acceptance': 'acptnc',
'access': 'acß',
'accessible': 'acßbl',
'accident': 'acdnt',
'accomplishment': 'acmplshmnt',
'according': 'acrdng',
'account': 'acont',
'accountability': 'acntblty',
'accounting': 'acntng',
'accuracy': 'acrcy',
'accurate': 'acr@',
'accurately': 'acr@ly',
'accusation': 'acs@n',
'achievement': 'achvmnt',
'acid': 'acd',
'across': 'acrs',
'action': 'actn',
'active': 'actv',
'actively': 'actvly',
'activist': 'actvist',
'activity': 'actvty',
'actor': 'actr', 
'actress': 'actres',
'actual': 'actl',
'actually': 'actł',
'added': 'adð',
'addition': 'adtn',
'additional': 'adtɲl',
'address': 'adrs',
'adequate': 'adq@',
'adjustment': 'adjstmnt',
'administration': 'admstr@n',
'administrative': 'admstr@v',
'administrator': 'admstr@r',
'admission': 'admision',
'adolescent': 'adlscnt',
'adoption': 'adptn',
'adult': 'adlt',
'advance': 'advnc',
'advanced': 'advncð',
'advantage': 'advntg',
'adventure': 'advntr',
'advertising': 'advrtsng',
'advice': 'advc',
'adviser': 'advsr',
'advocate': 'advc@',
'aesthetic': 'aestc',
'affair': 'afär',
'afraid': 'afäd',
'African': 'Afriƈn',
'African-American': 'Afriƈn-Ameriƈn',
'after': 'aftr',
'afternoon': 'aftrnon',
'afterward': 'aftrward',
'again': 'agän',
'against': 'agänst',
'age': 'ag',
'agency': 'agnc',
'agenda': 'agnɗ',
'agent': 'agnt',
'aggression': 'agrsn',
'aggressive': 'agrsv',
'agreement': 'agrmnt',
'agricultural': 'agrcltrl',
'agriculture': 'agrcltr',
'ahead': 'ahd',
'aircraft': 'aircrft',
'airline': 'airln',
'airplane': 'airpln',
'airport': 'airprt',
'alarm': 'alrm',
'album': 'albm',
'alcohol': 'alcl',
'alike': 'alk',
'alive': 'alv',
'all': 'al',
'allegation': 'alg@t¬',
'alleged': 'algð',
'allegedly': 'algðł',
'alley': 'aley',
'alliance': 'alnc',
'ally': 'aly',
'almost': 'almst',
'alone': 'alone',
'along': 'alng',
'alongside': 'alngsd',
'already': 'alrdy',
'also': 'als',
'alternative': 'alt',
'although': 'alŧgh',
'altogether': 'altogthr',
'always': 'alwys',
'amazing': 'aɱzŋ',
'ambassador': 'amɓsdr',
'ambition': 'ambtn',
'ambitious': 'ambtious',
'amendment': 'amndmnt',
'American': 'Ameriƈn',
'amid': 'amd',
'amount': 'amnt',
'analysis': 'aɲlysis',
'analyst': 'aɲlyst',
'ancestor': 'ancstr',
'ancient': 'ancnt',
'and': 'n',
'angel': 'angl',
'anger': 'angr',
'angle': 'angl',
'animal': 'anɱl',
'anniversary': 'anvrsry',
'announcement': 'anoncmnt',
'annual': 'anl',
'annually': 'anly',
'anonymous': 'anonyms',
'another': 'anotr',
'answer': 'answr',
'anxiety': 'anxty',
'anxious': 'anxs',
'anybody': 'anybdy',
'anymore': 'anymr',
'anything': 'anyŧng',
'anyway': 'anywy',
'anywhere': 'anywhr',
'apart': 'aprt',
'apartment': 'apt',
'apology': 'aplgy',
'apparent': 'aprnt',
'apparently': 'aprntly',
'appeal': 'apl',
'appearance': 'aprnc',
'apple': 'aple',
'application': 'aplc@n',
'appointment': 'apntmnt',
'appreciation': 'aprctn',
'approach': 'aprch',
'appropriate': 'aprprt',
'approval': 'aprvl',
'approximately': 'aprxm@ł',
'architect': 'arctet',
'architecture': 'arctetr',
'arena': 'arɲ',
'argument': 'arg',
'arm': 'arm',
'armed': 'armð',
'army': 'army',
'around': 'arnd',
'arrangement': 'arngmnt',
'array': 'arr',
'arrest': 'arst',
'arrival': 'arrivl',
'article': 'artcl',
'artifact': 'artƒct',
'artificial': 'artfcl',
'artist': 'artst',
'artistic': 'artstc',
'aside': 'asd',
'asleep': 'aslp',
'aspect': 'aspct',
'ass': 'aß',
'assault': 'aßlt',
'assembly': 'asmbly',
'assessment': 'aßmnt',
'asset': 'aset',
'assignment': 'asgnmnt',
'assistance': 'aßistnc',
'assistant': 'aßistnt',
'associate': 'asoct',
'associated': 'asoctð',
'association': 'asoctn',
'assumption': 'asumptn',
'astronomer': 'astronomer',
'at': '@',
'athlete': '@hlt',
'athletic': '@hltc',
'atmosphere': '@msphr',
'atop': '@op',
'attack': '@ck',
'attempt': '@mpt',
'attendance': '@enɗnc',
'attention': '@entn',
'attitude': '@itud',
'attorney': '@orney',
'attraction': '@rctn',
'attractive': '@rctv',
'auction': 'ăctn',
'audience': 'ădnc',
'author': 'ătr',
'authority': 'ăthort',
'automatic': 'ătoɱtc',
'automobile': 'ătombl',
'autonomy': 'ătonmy',
'availability': 'avälblty',
'available': 'avälbl',
'average': 'avg',
'award': 'awrd',
'aware': 'awr',
'awareness': 'awrnes',
'awful': 'awfl',



'away': 'away',
'acknowledge': 'akwldg',
'attitude': '@tude', 'attitudes': '@tudes',
'advantage': 'advtg', 'advantages': 'advtgs',
'accelerate': 'aclrt',
'alike': 'alik',
'adjective': 'adj',
'academic': 'aƈdmic',
'account': 'acct·',
'accountant': 'acct·ant',
'accounting': 'acct·ng',
'accommodation': 'acomɗt¬',
'administration': 'adm·tion',
'administrator': 'adµ',
'administrative': 'adµn',
'agriculture': 'agric·',
'agricultural': 'agric·al',
'association': 'assoc·',
'associate': 'asoc·te', 'associates': 'asoc·tes',
'authentication': 'ăŧ',
'authenticate': 'ăŧƈte', 'authenticates': 'ăŧƈs',
'authority': 'autho·', 'authorities': 'autho·s',
'argument': 'arg·', 'arguments': 'arg·s',
'assumption': 'asmptn', 'assumptions': 'asmptns',
'avenue': 'ave·',
'answer': 'nwr', 'answers': 'nwrs',
// B- \\
'before': 'b4',
'between': 'btwn',
'become': 'bcm', 'becomes': 'bcms',
'became': 'bƈm', 
'bring': 'brg', 'brings': 'brgs',
'believe': 'blv', 'believes': 'blvs',
'business': 'biz',
'businesses': 'bizes',
'bankruptcy': 'ɓnkr·',
'brotherhood': 'bhd·',
'brother': 'bro',
'brothers': 'bros',
'build': 'bld',
'building': 'bldng',
'background': 'ɓgd',
'boyfriend': 'boyfrd',
'bureaucracy': 'bcracy',


'baby': 'ɓb',
'back': 'ɓk',
'background': 'ɓkgrnd',
'backyard': 'ɓkyard',
'bacteria': 'ɓktria',
'bad': 'ɓd',
'badly': 'ɓdly',
'bag': 'ɓg',
'balance': 'ɓlanc',
'balanced': 'ɓlncð',
'ball': 'ɓl',
'balloon': 'ɓlōn',
'ballot': 'ɓllot',
'ban': 'ɓn',
'banana': 'ɓɲɲ',
'band': 'ɓnd',
'bank': 'ɓnk',
'banker': 'ɓnker',
'banking': 'ɓnkiŋ',
'bankruptcy': 'ɓnkruptcy',
'bar': 'ɓr',
'bare': 'ɓre',
'barely': 'ɓreł',
'barn': 'ɓrn',
'barrel': 'ɓrel',
'barrier': 'ɓrier',
'base': 'ɓse',
'baseball': 'ɓseɓl',
'basement': 'ɓsement',
'basic': 'ɓsc',
'basically': 'ɓsiƈł',
'basis': 'ɓsis',
'basket': 'ɓsket',
'basketball': 'ɓsketɓl',
'bat': 'ɓt',
'bath': 'ɓŧ',
'bathroom': 'ɓŧrōm',
'battery': 'ɓtry',
'battle': 'ɓtle',
'bay': 'ɓy',
'beach': '',
'beam': '',
'bean': '',
'bear': '',
'beard': '',
'beast': '',
'beat': '',
'beautiful': '',
'beauty': '',
'because': 'bƈuse',
'bed': 'bð',
'bedroom': 'bðrōm',
'bee': '',
'beef': '',
'beer': '',
'before': '',
'before': '',
'before': '',
'beginning': '',
'behalf': 'bɦlf',
'behave': 'bɦv', 'behaves': 'bɦves',
'behavior': 'bɦvr', 'behaviors': 'bɦvrs',
'behaving': 'bɦvŋ', 'behavings': 'bɦvŋs',
'behavioral': 'bɦvral',
'behind': '',
'behind': '',
'being': '',
'belief': '',
'bell': '',
'belly': '',
'below': '',
'below': '',
'belt': '',
'bench': '',
'beneath': '',
'benefit': 's',
'beside': '',
'besides': '',
'besides': '',
'best': '',
'best': '',
'bet': '',
'better': '',
'better': '',
'between': '',
'beyond': '',
'beyond': '',
'bias': '',
'Bible': '',
'bicycle': '',
'bid': '',
'big': '',
'bike': '',
'bill': '',
'billion': '',
'biography': '',
'biological': 'biologiƈl',
'biology': '',
'bird': '',
'birth': '',
'birthday': 'birŧɗy',
'bishop': '',
'bit': '',
'bit': '',
'bite': '',
'bitter': '',
'black': '',
'black': '',
'blade': '',
'blank': '',
'blanket': '',
'blast': '',
'blessing': '',
'blind': '',
'block': '',
'blond': '',
'blood': '',
'bloody': '',
'blow': '',
'blue': '',
'blue': '',
'board': '',
'boat': '',
'body': '',
'bold': '',
'bolt': '',
'bomb': '',
'bombing': '',
'bond': '',
'bone': '',
'bonus': '',
'book': '',
'boom': '',
'boot': '',
'booth': '',
'border': '',
'boring': '',
'boss': '',
'both': '',
'both': '',
'bottle': '',
'bottom': '',
'bottom': '',
'boundary': 'bounɗry',
'bow': '',
'bowl': '',
'box': '',
'boy': '',
'boyfriend': '',
'brain': '',
'brake': '',
'branch': '',
'brand': '',
'brave': '',
'bread': '',
'break': '',
'breakfast': 'breakƒ§',
'breast': '',
'breath': '',
'breathing': '',
'breeze': '',
'brick': '',
'bride': '',
'bridge': '',
'brief': '',
'briefly': '',
'bright': '',
'brilliant': '',
'British': '',
'broad': '',
'broadcast': 'broadƈ§',
'broken': '',
'broker': '',
'bronze': '',
'brother': '',
'brown': '',
'brush': '',
'brutal': '',
'bubble': '',
'buck': '',
'bucket': '',
'buddy': '',
'budget': '',
'bug': '',
'builder': '',
'building': '',
'bulb': '',
'bulk': '',
'bull': '',
'bullet': '',
'bunch': '',
'burden': '',
'bureau': '',
'burning': '',
'bus': '',
'bush': '',
'business': 'biz',
'businessman': 'bizɱn',
'busy': '',
'but': '',
'but': '',
'butt': '',
'butter': '',
'butterfly': '',
'button': '',
'buyer': '',
'by': '',


// C- \\
'could': 'could',
'country': 'c·try',
'create': 'crte', 'creates': 'crtes',
'complete': 'cmplt', 'completes': 'cmplts',
'cover': 'cvr',
'coverage': 'cvrg',
'concept': 'cncpt', 'concepts': 'cncpts',
'compete': 'cmpt', 'competes': 'cmpts',
'competition': 'cmptn', 'competetitions': 'cmptns',
'competitor': 'cmptitor', 'competitors': 'cmptitors',
'commitment': 'comtmt', 'commitments': 'cmtmts',
'commit': 'comt', 'commits': 'comts',
'committing': 'comt·ng',
'compare': 'cmpr', 'compares': 'cmprs',
'customer': 'cstmr', 'customers': 'cstmrs',
'check': 'chk',
'company': 'com·', 'companies': 'com·ies',
'corporate': 'corp·',
'corporation': 'corp·on', 'corporations': 'corp·ons',
'capital': 'ƈptal',
'catholic': 'ƈŧolic',
'center': 'ctr',
'centre': 'ctr',
'central': 'ctr·al',
'centralized': 'ctr·zð',
'chemistry': 'chem',
'chemical': 'chemƈl',
'college': 'coll·',
'clothes': 'cl·th·s',
'clothing': 'cl·th·ng',
'commerce': 'com·r·c',
'commercial': 'com·r·cial',
'community': 'c·m·ty',
'compensation': 'comp·',
'condominium': 'condo·',
'consolidated': 'consolɗtð',
'construction': 'constr·',
'contract': 'cont·',
'cooperative': 'coop·',
'correction': 'corr·',
'contamination': 'contami',
'classroom': 'cl·ro·m',
'class': 'cl·',
'classic': 'cl·ic',
'courtroom': 'courtro·m',
'careful': 'ƈrful',
'carefully': 'ƈrfuly',



'cab': 'ƈb',
'cabin': 'ƈbin',
'cabinet': 'ƈbint',
'cable': 'ƈble',
'cage': 'ƈg',
'cake': 'ƈke',
'calculation': 'ƈlculation',
'calendar': 'ƈlenɗr',
'call': 'ƈl',
'called': 'ƈlð',
'calm': 'ƈlm',
'camera': 'ƈmera',
'camp': 'ƈmp',
'campaign': 'ƈmpaign',
'campus': 'ƈmpus',
'can': 'ƈn',
'Canadian': 'Ƈɲdian',
'cancer': 'ƈncer',
'candidate': 'ƈndiɗt',
'candle': 'ƈndle',
'candy': 'ƈndy',
'canvas': 'ƈnvas',
'cap': 'ƈp',
'capability': 'ƈpability',
'capable': 'ƈpable',
'capacity': 'ƈpacity',
'capital': 'ƈptal',
'captain': 'ƈptain',
'capture': 'ƈpture',
'car': 'ƈr',
'carbohydrate': 'ƈrbohydrate',
'carbon': 'ƈrbon',
'card': 'ƈrd',
'care': 'ƈre',
'career': 'ƈrēr',
'careful': 'ƈreful',
'carefully': 'ƈrefuł',
'cargo': 'ƈrgo',
'carpet': 'ƈrpet',
'carrier': 'ƈrier',
'carrot': 'ƈrot',
'cart': 'ƈrt',
'cartoon': 'ƈrtōn',
'case': 'ƈse',
'cash': 'ƈsh',
'casino': 'ƈsino',
'cast': 'ƈ§',
'casual': 'ƈsual',
'casualty': 'ƈsualty',
'cat': 'ƈt',
'catalog': 'ƈtalog',
'catch': 'ƈtch',
'category': 'ƈtegory',
'cattle': 'ƈttle',
'cause': 'ƈuse',
'cave': 'ƈve',
'ceiling': '',
'celebration': '',
'celebrity': '',
'cell': '',
'cemetery': '',
'center': '',
'central': '',
'century': '',
'CEO': '',
'ceremony': '',
'certain': '',
'certainly': '',
'chain': 'cɦin',
'chair': 'cɦir',
'chairman': 'cɦirɱn',
'challenge': 'cɦlenge',
'chamber': 'cɦmber',
'champion': 'cɦmp',
'championship': 'cɦmpship',
'chance': 'cɦnc',
'change': 'cɦŋg', 'changes': 'cɦŋgs',
'changing': 'cɦŋiŋ',
'channel': 'cɦnel',
'chaos': 'cɦos',
'chapter': 'cɦpter',
'character': 'cɦr',
'characteristic': 'cɦristic',
'charge': 'cɦrg',
'charity': 'cɦrity',
'charm': 'cɦrm',
'chart': 'cɦrt',
'charter': 'cɦrter',
'cheap': '',
'check': '',
'cheek': '',
'cheese': '',
'chef': '',
'chest': '',
'chicken': '',
'chief': '',
'chief': '',
'child': '',
'childhood': '',
'chill': '',
'chin': '',
'Chinese': '',
'chip': '',
'chocolate': '',
'choice': '',
'cholesterol': '',
'Christian': '',
'Christian': '',
'Christianity': '',
'Christmas': 'Chri§ɱs',
'chronic': '',
'chunk': '',
'church': '',
'cigarette': 'ciɠret',
'circle': '',
'circuit': '',
'circumstance': '',
'citizen': '',
'citizenship': '',
'city': '',
'civic': '',
'civil': '',
'civilian': '',
'civilian': '',
'civilization': '',
'claim': '',
'class': '',
'classic': '',
'classical': 'claßiƈl',
'classroom': '',
'clay': '',
'clean': '',
'clear': '',
'clearly': '',
'clerk': '',
'client': '',
'cliff': '',
'climate': 'cliɱt',
'clinic': '',
'clinical': 'cliniƈl',
'clip': '',
'clock': '',
'close': '',
'close': '',
'closed': 'closð',
'closely': '',
'closer': '',
'closest': '',
'closet': '',
'cloth': '',
'clothes': '',
'clothing': '',
'cloud': '',
'club': '',
'clue': '',
'cluster': '',
'coach': '',
'coal': '',
'coalition': '',
'coast': '',
'coastal': '',
'coat': '',
'cocaine': 'coƈine',
'code': '',
'coffee': '',
'cognitive': '',
'coin': '',
'cold': '',
'cold': '',
'collaboration': '',
'collapse': '',
'collar': '',
'colleague': '',
'collection': '',
'collective': '',
'collector': '',
'college': '',
'colonial': '',
'colony': '',
'color': '',
'colorful': '',
'column': '',
'columnist': '',
'combat': 'comɓt',
'combination': 'combiɲt¬',
'combined': 'combinð',
'comedy': 'comðy',
'comfort': '',
'comfortable': '',
'coming': '',
'command': 'coɱnd',
'commander': 'coɱnder',
'comment': '',
'commercial': '',
'commission': '',
'commissioner': '',
'commitment': '',
'committee': '',
'commodity': '',
'common': '',
'commonly': '',
'communication': 'comuniƈt¬',
'community': '',
'companion': '',
'company': '',
'comparable': '',
'comparison': '',
'compelling': '',
'compensation': '',
'competition': '',
'competitive': '',
'competitor': '',
'complaint': '',
'complete': '',
'completely': '',
'complex': '',
'complex': '',
'complexity': '',
'compliance': '',
'complicated': 'complic@ð',
'component': '',
'composition': '',
'compound': '',
'comprehensive': '',
'compromise': '',
'computer': '',
'concentration': '',
'concept': '',
'conception': '',
'concern': '',
'concerned': 'concernð',
'concerning': '',
'concert': '',
'conclusion': '',
'concrete': '',
'condition': '',
'conduct': '',
'conference': '',
'confession': '',
'confidence': '',
'confident': '',
'conflict': '',
'confrontation': '',
'confusion': '',
'Congress': '',
'congressional': 'congreßioɲl',
'connection': '',
'conscience': '',
'conscious': '',
'consciousness': '',
'consecutive': '',
'consensus': '',
'consent': '',
'consequence': '',
'consequently': '',
'conservation': '',
'conservative': '',
'conservative': '',
'considerable': '',
'considerably': '',
'consideration': '',
'consistent': '',
'consistently': '',
'conspiracy': '',
'constant': '',
'constantly': '',
'constitution': '',
'constitutional': 'constitutioɲl',
'constraint': '',
'construction': '',
'consultant': '',
'consumer': '',
'consumption': '',
'contact': '',
'container': '',
'contemporary': '',
'content': '',
'content': '',
'contest': '',
'context': '',
'continent': '',
'continued': 'contnuð',
'continuing': '',
'continuous': '',
'contract': '',
'contractor': '',
'contrast': '',
'contribution': '',
'contributor': '',
'control': '',
'controversial': '',
'controversy': '',
'convenience': '',
'convention': '',
'conventional': 'conventioɲl',
'conversation': '',
'conversion': '',
'conviction': '',
'convinced': 'convincð',
'cook': '',
'cookie': '',
'cooking': '',
'cool': '',
'cooperation': '',
'cooperative': '',
'coordinator': 'coordiɲtor',
'cop': '',
'copy': '',
'cord': '',
'core': '',
'corn': '',
'corner': '',
'corporate': '',
'corporation': '',
'correct': '',
'correctly': '',
'correlation': '',
'correspondent': '',
'corridor': '',
'corruption': '',
'cost': '',
'costly': '',
'costume': '',
'cottage': '',
'cotton': '',
'couch': '',
'could': '',
'council': '',
'counsel': '',
'counseling': '',
'counselor': '',
'count': '',
'counter': '',
'counterpart': '',
'country': '',
'county': '',
'coup': '',
'couple': '',
'courage': '',
'course': '',
'course': '',
'court': '',
'courtroom': '',
'cousin': '',
'cover': '',
'coverage': '',
'cow': '',
'crack': '',
'craft': '',
'crash': '',
'crazy': '',
'cream': '',
'creation': '',
'creative': '',
'creativity': '',
'creature': '',
'credibility': 'crðibility',
'credit': 'crðit',
'crew': '',
'crime': '',
'criminal': 'crimiɲl',
'crisis': '',
'criteria': '',
'critic': '',
'critical': 'critiƈl',
'criticism': '',
'crop': '',
'cross': '',
'crowd': '',
'crowded': 'crowdð',
'crucial': '',
'cruel': '',
'cruise': '',
'cry': '',
'crystal': '',
'Cuban': 'Cuɓn',
'cue': '',
'cultural': '',
'culture': '',
'cup': '',
'cure': '',
'curiosity': '',
'curious': '',
'currency': '',
'current': '',
'currently': '',
'curriculum': '',
'curtain': '',
'curve': '',
'custody': '',
'custom': '',
'customer': '',
'cut': '',
'cute': '',
'cycle': '',


// D- \\
'during': 'd·r·ng',
'drive': 'drv', 'drives': 'drvs',
'driving': 'drv·ng', 'drivings': 'drv·ngs',
'decrease': 'dcrs', 'decreases': 'dcrs·s',
'decreased': 'dcrs·ð',
'database': 'db', 'databases': 'dbses',
'danger': 'ɗngr', 'dangers': 'ɗngrs',
'dangerous': 'ɗngrous',
'damage': 'ɗɱg', 'damages': 'ɗɱgs',
'damaging': 'ɗɱgŋ', 'damagings': 'ɗɱgŋs',
'discover': 'd·c·v·r',
'discovery': 'd·c·v·ry',
'detail': 'd·t·l',
'details': 'd·t·ls',
'detailed': 'd·t·lð',
'defense': 'def·',
'defend': 'def·nd',
'defender': 'def·der',
'definition': 'defi·',
'department': 'dep·mt',
'detention': 'det·',
'digital': 'digi·',
'direction': 'dir',
'director': 'direc·',
'distribution': 'dist·',
'distributing': 'dist·ng',
'distributor': 'dist·tor', 'distributors': 'dist·tors',
'division': 'div·', 'divisions': 'div·s',
'document': 'doc·', 'documents': 'doc·s',
'doctor': 'Dr', 'doctors': 'drs',
'development': 'devmt', 'developmets': 'devmts',
'developer': 'devr', 'developers': 'devrs',
'delete': 'del',


'dad': 'ɗd',
'daily': 'ɗił',
'dam': 'ɗm',
'damn': 'ɗmn',
'dance': 'ɗnc',
'dancer': 'ɗncr',
'dancing': 'ɗncŋ',
'danger': 'ɗnger',
'dangerous': 'ɗngerous',
'dark': 'ɗrk',
'darkness': 'ɗrkneß',
'data': 'ɗta',
'date': 'ɗt',
'daughter': 'ɗughter',
'dawn': 'ɗwn',
'day': 'ɗy',
'dead': '',
'deadline': '',
'deadly': '',
'deal': '',
'dealer': '',
'dear': '',
'death': '',
'debate': 'deɓte',
'debris': '',
'debt': '',
'debut': '',
'decade': 'deƈd',
'decent': '',
'decision': '',
'deck': '',
'decline': '',
'deep': '',
'deep': '',
'deeply': '',
'deer': '',
'defeat': '',
'defendant': 'defenɗnt',
'defender': '',
'defense': '',
'defensive': '',
'deficit': '',
'definitely': '',
'definition': '',
'degree': '',
'delay': '',
'deliberately': '',
'delicate': 'deliƈt',
'delight': '',
'delivery': '',
'demand': 'dɱnd',
'democracy': '',
'Democrat': '',
'democratic': '',
'demographic': '',
'demonstration': '',
'denial': '',
'dense': '',
'density': '',
'department': '',
'departure': '',
'dependent': '',
'depending': '',
'deposit': '',
'depressed': 'depreßð',
'depression': '',
'depth': '',
'deputy': '',
'description': '',
'desert': '',
'design': '',
'designer': '',
'desire': '',
'desk': '',
'desperate': '',
'desperately': '',
'despite': '',
'dessert': '',
'destination': 'destiɲt¬',
'destruction': '',
'detail': '',
'detailed': 'detälð',
'detective': '',
'determination': 'determiɲt¬',
'devastating': '',
'developer': '',
'developing': '',
'development': '',
'developmental': '',
'device': '',
'devil': '',
'diabetes': '',
'diagnosis': '',
'dialogue': '',
'diamond': '',
'diary': '',
'diet': '',
'difference': '',
'different': '',
'differently': '',
'difficult': '',
'difficulty': '',
'digital': '',
'dignity': '',
'dilemma': 'dileɱ',
'dimension': '',
'dining': '',
'dinner': '',
'diplomat': 'diploɱt',
'diplomatic': 'diploɱtic',
'direct': '',
'direction': '',
'directly': '',
'director': '',
'dirt': '',
'dirty': '',
'disability': '',
'disabled': 
'ḋsablð',
'disappointed': 'disapöntð',
'disappointment': '',
'disaster': '',
'disc': '',
'discipline': '',
'discount': '',
'discourse': '',
'discovery': '',
'discrimination': 'discrimiɲt¬',
'discussion': '',
'disease': '',
'dish': '',
'disk': '',
'disorder': '',
'display': '',
'dispute': '',
'distance': '',
'distant': '',
'distinct': '',
'distinction': '',
'distinctive': '',
'distribution': '',
'district': '',
'disturbing': '',
'diverse': '',
'diversity': '',
'divine': '',
'division': '',
'divorce': '',
'DNA': '',
'dock': '',
'doctor': '',
'doctrine': '',
'document': '',
'documentary': '',
'dog': '',
'doll': '',
'domain': 'doɱin',
'domestic': '',
'dominant': 'domiɲnt',
'donation': 'doɲt¬',
'donor': '',
'door': '',
'doorway': '',
'dose': '',
'dot': '',
'double': '',
'doubt': '',
'dough': '',
'down': '',
'down': '',
'downtown': '',
'downtown': '',
'dozen': '',
'draft': '',
'drama': 'draɱ',
'dramatic': 'draɱtic',
'dramatically': 'draɱtiƈł',
'drawer': '',
'drawing': '',
'dream': '',
'dress': '',
'dried': '',
'drink': '',
'drinking': '',
'drive': '',
'driver': '',
'driveway': '',
'driving': '',
'drop': '',
'drug': '',
'drum': '',
'drunk': '',
'dry': '',
'duck': '',
'due': '',
'due': '',
'dumb': '',
'during': '',
'dust': '',
'Dutch': '',
'duty': '',
'dying': '',
'dynamic': 'dyɲmic',
'dynamics': 'dyɲmics',

// E- \\
'enough': 'engh',
'extreme': 'xtrm', 'extremes': 'xtrms',
'extremely': 'xtrm·ly',
'especially': 'spcly',
'easy': 'esy',
'email': 'eɱl',
'example': 'exmp·', 'examples': 'exmp·s',
'economy': 'econ',
'economic': 'econic', 'economics': 'econics',
'economical': 'econƈl',
'engine': 'eng·',
'engineering': 'eng·ng',
'engineer': 'eng·er', 'engineers': 'eng·ers',
'entertainment': 'ent·mt',
'environment': 'env·mt',
'equipment': 'equip·', 'equipments': 'equip·s',
'exercise': 'xrcse', 'exercises': 'xrcses',
'execution': 'exec·',
'executive': 'exec·ve', 'executives': 'exec·ves',
'element': 'elem·', 'elements': 'elem·s',
'explore': 'expl·', 'explores': 'expl·s',
'exploration': 'expl·t·n', 'explorations': 'expl·t·ns',
'employ': 'emp·', 'employs': 'emp·s',
'employee': 'emp·ee', 'employees': 'emp·ees',
'employer': 'emp·er', 'employers': 'emp·ers',
'entrepreneur': 'entrep·', 'entrepreneurs': 'entrep·s',
'entrepreneurship': 'entrep·ship',
'entrepreneurial': 'entrep·rial',
'example': 'ex·',
'experiment': 'xprmnt', 'experiments': 'xprmnts',
'experimentation': 'xprmnt·on',
'experimental': 'xprmnt·al',
'experience': '·xp·',
'expense': 'exp·',


'e-mail': 'e-ɱl',
'each': '',
'each': '',
'eager': '',
'ear': '',
'early': '',
'early': '',
'earnings': 'earnŋs',
'earth': '',
'earthquake': '',
'ease': '',
'easily': '',
'east': '',
'eastern': '',
'easy': '',
'easy': '',
'eating': 'eatŋ',
'ecological': 'ecologiƈl',
'economic': '',
'economically': 'economiƈł',
'economics': '',
'economist': '',
'economy': '',
'ecosystem': '',
'edge': '',
'edition': '',
'editor': '',
'education': 'ðuƈt¬',
'educational': 'ðuƈt¬al',
'educator': 'ðuƈtor',
'effect': '',
'effective': '',
'effectively': '',
'effectiveness': '',
'efficiency': '',
'efficient': '',
'effort': '',
'egg': '',
'ego': '',
'eight': '',
'eighth': '',
'either': '',
'either': '',
'elaborate': '',
'elbow': '',
'elder': '',
'elderly': '',
'election': '',
'electric': 'elect',
'electrical': 'electriƈl',
'electricity': 'elec·ity',
'electronic': '',
'electronics': '',
'elegant': 'eleɠnt',
'element': '',
'elementary': '',
'elephant': 'elepɦnt',
'elevator': '',
'eleven': '',
'eligible': '',
'elite': '',
'else': '',
'elsewhere': '',
'embarrassed': 'emɓraßð',
'emergency': '',
'emerging': '',
'emission': '',
'emotion': '',
'emotional': 'emotioɲl',
'emotionally': 'emotioɲł',
'emphasis': 'empɦsis',
'empire': '',
'employee': '',
'employer': '',
'employment': '',
'empty': '',
'encounter': '',
'encouraging': '',
'end': '',
'endless': '',
'enemy': '',
'energy': '',
'enforcement': '',
'engagement': 'enɠgement',
'engaging': 'enɠgiŋ',
'engine': '',
'engineer': '',
'engineering': '',
'English': '',
'English': '',
'enormous': '',
'enough': '',
'enough': '',
'enterprise': '',
'entertainment': '',
'enthusiasm': '',
'entire': '',
'entirely': '',
'entity': '',
'entrance': '',
'entrepreneur': '',
'entry': '',
'envelope': '',
'environment': '',
'environmental': '',
'epidemic': '',
'episode': '',
'equal': '',
'equality': '',
'equally': '',
'equation': '',
'equipment': '',
'equity': '',
'equivalent': '',
'era': '',
'error': '',
'escape': 'esƈp',
'especially': '',
'essay': '',
'essence': '',
'essential': '',
'essentially': '',
'establishment': '',
'estate': '',
'estimate': 'estiɱt',
'estimated': 'estiɱtð',
'etc': '',
'ethical': 'eŧiƈl',
'ethics': '',
'ethnic': '',
'European': '',
'European': '',
'evaluation': '',
'even': '',
'even': '',
'evening': '',
'event': '',
'eventually': '',
'ever': '',
'every': '',
'everybody': '',
'everyday': 'everyɗy',
'everyone': '',
'everything': '',
'everywhere': '',
'evidence': '',
'evident': '',
'evil': '',
'evil': '',
'evolution': '',
'exact': '',
'exactly': '',
'exam': '',
'examination': 'examiɲt¬',
'example': '',
'excellent': '',
'except': '',
'except': '',
'exception': '',
'excessive': '',
'exchange': 'excɦŋg', 'exchanges': 'excɦŋgs',
'excited': '',
'excitement': '',
'exciting': '',
'exclusive': '',
'exclusively': '',
'excuse': '',
'execution': '',
'executive': '',
'exercise': '',
'exhibit': '',
'exhibition': '',
'existence': '',
'existing': '',
'exit': '',
'exotic': '',
'expansion': '',
'expectation': '',
'expected': '',
'expedition': '',
'expense': '',
'expensive': '',
'experience': '',
'experienced': '',
'experiment': '',
'experimental': '',
'expert': '',
'expertise': '',
'explanation': 'explaɲt¬',
'explicit': '',
'exploration': '',
'explosion': '',
'export': '',
'exposure': '',
'expression': '',
'extended': '',
'extension': '',
'extensive': '',
'extent': '',
'external': 'exterɲl',
'extra': '',
'extraordinary': 'extraordiɲry',
'extreme': '',
'extremely': '',
'eye': '',
'eyebrow': '',

// F- \\
'feature': 'ftr', 'features': 'ftrs', 
'feedback': 'fdɓk', 'feedbacks': 'fdɓks',
'fact': 'ƒct', 'facts': 'ƒcts',
'first': '1st',
'federal': 'fed·', 'federals': 'fed·s',
'federation': 'fed·tion', 'federations': 'fed·s',
'foundation': 'founɗt¬', 'foundations': 'founɗt¬s',
'function': 'func', 'functions': 'funcs',
'functional': 'funcɲl', 'functionals': 'funcɲls',
'functionality': 'funcɲlity', 'functinalities': 'funcɲlities',
'friend': 'fr·d', 'friends': 'fr·ds',
'friendly': 'fr·dly',
'friendship': 'fr·dship', 'friendships': 'fr·dships',


'fabric': 'ƒbric',
'face': 'ƒc',
'facility': 'ƒcility',
'fact': 'ƒct',
'factor': 'ƒctor',
'factory': 'ƒctory',
'faculty': 'ƒculty',
'failure': 'ƒiltur',
'faint': 'ƒint',
'fair': 'ƒir',
'fairly': 'ƒirł',
'faith': 'ƒiŧ',
'fall': 'ƒl',
'falso ': 'ƒlso',
'fame': 'ƒme',
'familiar': 'ƒmiliar',
'famous': 'ƒmous',
'fan': 'ƒn',
'fantastic': 'ƒntastic',
'fantasy': 'ƒntasy',
'far': 'ƒr',
'fare': 'ƒre',
'farm': 'ƒrm',
'farmer': 'ƒrmer',
'fascinating': 'ƒsciɲtiŋ',
'fashion': 'ƒshion',
'fast': 'ƒ§',
'faster': 'ƒ§er',
'fat': 'ƒt',
'fatal': 'ƒtal',
'fate': 'ƒt',
'father': 'ƒŧer',
'fatigue': 'ƒtigue',
'fault': 'ƒult',
'favor': 'ƒvor',
'favorable': 'ƒvorable',
'favorite': 'ƒvorit',
'fear': '',
'feather': '',
'feature': '',
'federal': '',
'fee': '',
'feel': '',
'feeling': '',
'fellow': '',
'fellow': '',
'female': 'feɱle',
'feminist': '',
'fence': '',
'festival': '',
'fever': '',
'few': '',
'fewer': '',
'fiber': '',
'fiction': '',
'field': '',
'fierce': '',
'fifteen': '',
'fifth': '',
'fifty': '',
'fight': '',
'fighter': '',
'fighting': '',
'figure': '',
'file': '',
'film': '',
'filter': '',
'final': 'fiɲl',
'finally': 'fiɲł',
'finance': 'fin', 'finances': 'fins',
'financed': 'fincð',
'financing': 'finciŋ',
'financial': 'fincial', 'financials': 'fincials',
'finding': '',
'fine': '',
'finger': '',
'finish': '',
'fire': '',
'firm': '',
'firm': '',
'firmly': '',
'first': '',
'first': '',
'fiscal': 'fisƈl',
'fish': '',
'fisherman': 'fisherɱn',
'fishing': '',
'fist': '',
'fit': '',
'fitness': '',
'five': '',
'fixed': '',
'flag': '',
'flame': '',
'flash': '',
'flat': '',
'flavor': '',
'fleet': '',
'flesh': '',
'flexibility': '',
'flexible': '',
'flight': '',
'flood': '',
'floor': '',
'flour': '',
'flow': '',
'flower': '',
'fluid': '',
'fly': '',
'flying': '',
'focus': '',
'fog': '',
'folk': '',
'following': '',
'food': '',
'fool': '',
'foot': '',
'football': 'footɓl',
'for': '',
'for': '',
'force': '',
'forehead': '',
'foreign': '',
'foreigner': '',
'forest': '',
'forever': '',
'fork': '',
'form': '',
'formal': 'forɱl',
'format': 'forɱt',
'formation': 'forɱt¬',
'former': '',
'formerly': '',
'formula': '',
'forth': '',
'fortunately': 'fortuɲteł',
'fortune': '',
'forty': '',
'forum': '',
'forward': '',
'founder': '',
'four': '',
'fourth': '',
'fraction': '',
'fragile': '',
'fragment': '',
'frame': '',
'framework': '',
'franchise': '',
'frankly': '',
'fraud': '',
'free': '',
'freedom': '',
'freely': '',
'French': '',
'French': '',
'frequency': '',
'frequent': '',
'frequently': '',
'fresh': '',
'freshman': 'freshɱn',
'friend': '',
'friendly': '',
'friendship': '',
'from': '',
'front': '',
'front': '',
'front': '',
'frontier': '',
'frozen': '',
'fruit': '',
'frustration': '',
'fucking': '',
'fuel': '',
'full': '',
'full-time': '',
'fully': '',
'fun': '',
'fun': '',
'fund': '',
'fundamental': 'funɗmental',
'funding': '',
'funeral': '',
'funny': '',
'fur': '',
'furniture': '',
'furthermore': '',
'future': '',

// G- \\
'general': 'genrl', 'generals': 'genrls',
'government': 'gov', 'governments': 'govs',
'group': 'grp', 'groups': 'grps',
'girlfriend': 'girlfr·d',
'gamification': 'ɠµfiƈt¬',
'Gamification': 'Ɠµfiƈt¬',

'gain': 'ɠin',
'galaxy': 'ɠlaxy',
'gallery': 'ɠlery',
'game': 'ɠme',
'gang': 'ɠng',
'gap': 'ɠp',
'garage': 'ɠrage',
'garbage': 'ɠrɓg',
'garden': 'ɠrden',
'garlic': 'ɠrlic',
'gas': 'ɠs',
'gasoline': 'ɠsolin',
'gate': 'ɠte',
'gathering': 'ɠŧeriŋ',
'gay': 'ɠy',
'gaze': 'ɠze',
'gear': '',
'gender': '',
'gene': '',
'general': '',
'general': '',
'general': '',
'generally': '',
'generation': '',
'generous': '',
'genetic': '',
'genius': '',
'genre': '',
'gentle': '',
'gentleman': 'gentleɱn',
'gently': '',
'genuine': '',
'German': 'Gerɱn',
'gesture': '',
'ghost': '',
'giant': '',
'giant': '',
'gift': '',
'gifted': '',
'girl': '',
'girlfriend': '',
'given': '',
'glad': '',
'glance': '',
'glass': '',
'glimpse': '',
'global': 'gloɓl',
'globe': '',
'glory': '',
'glove': '',
'goal': '',
'goat': '',
'God': '',
'gold': '',
'golden': '',
'golf': '',
'good': '',
'good': '',
'government': '',
'governor': '',
'grace': '',
'grade': '',
'gradually': '',
'graduate': '',
'graduation': '',
'grain': '',
'grand': '',
'grandchild': '',
'grandfather': 'grandƒŧer',
'grandmother': '',
'grandparent': '',
'grant': '',
'grape': '',
'grass': '',
'grateful': '',
'grave': '',
'gravity': '',
'gray': '',
'great': '',
'greatest': '',
'greatly': '',
'Greek': '',
'green': '',
'grief': '',
'grin': '',
'grip': '',
'grocery': '',
'gross': '',
'ground': '',
'group': '',
'growing': '',
'growth': '',
'guarantee': '',
'guard': '',
'guest': '',
'guidance': 'guiɗnc',
'guide': '',
'guideline': '',
'guilt': '',
'guilty': '',
'guitar': '',
'gun': '',
'gut': '',
'guy': '',
'gym': '',


// I- \\
'improve': 'imprv', 'improves': 'imprvs',
'improving': 'imprv·ng', 'improvings': 'imprv·ngs',
'increase': 'incrs', 'increases': 'incrs·s',
'increased': 'incrs·ed',
'interest': 'intrst',
'interesting': 'intrst·ng',
'interested': 'intrsted',
'innovate': 'inno·te',
'innovation': 'inno·tion', 'innovations': 'inno·tion·s',
'innovative': 'inno·ve',
'immigration': 'immigr·',
'incorporated' : 'inc·',
'injury': 'inj·',
'index': 'ind·',
'industry': 'indus·',
'interest': 'int·st',
'invest': 'inv·',
'investment': 'inv·nt',
'investor': 'inv·tor', 'investors': 'inv·tors',
'important': 'imptnt', 'importants': 'imptnts',


'ice': '',
'icon': '',
'idea': '',
'ideal': '',
'ideal': '',
'identical': 'identiƈl',
'identification': 'identifiƈt¬',
'identity': '',
'ideological': 'ideologiƈl',
'ideology': '',
'if': '',
'ill': '',
'illegal': 'ileɠal',
'illness': '',
'illusion': '',
'image': 'iɱg', 'images': 'iɱgs',
'imagination': 'iɱgiɲt¬',
'immediate': '',
'immediately': '',
'immigrant': '',
'immigration': '',
'immune': '',
'impact': '',
'implementation': '',
'implication': 'impliƈt¬',
'import': '',
'importance': '',
'important': '',
'importantly': '',
'impossible': '',
'impression': '',
'impressive': '',
'improved': '',
'improvement': '',
'impulse': '',
'in': '',
'incentive': '',
'incident': '',
'including': '',
'income': '',
'increase': '',
'increased': '',
'increasing': '',
'increasingly': '',
'incredible': '',
'incredibly': '',
'indeed': '',
'independence': '',
'independent': '',
'index': '',
'Indian': '',
'Indian': '',
'indication': 'indiƈt¬',
'indicator': 'indiƈtor',
'indigenous': '',
'individual': '',
'individual': '',
'industrial': '',
'industry': '',
'inevitable': '',
'inevitably': '',
'infant': 'inƒnt',
'infection': '',
'inflation': '',
'influence': '',
'influential': '',
'informal': 'inforɱl',
'information': 'info',
'infrastructure': '',
'ingredient': '',
'inherent': '',
'initial': '',
'initially': '',
'initiative': '',
'injury': '',
'inmate': 'inɱte',
'inner': '',
'innocent': '',
'innovation': '',
'innovative': '',
'input': '',
'inquiry': '',
'insect': '',
'inside': '',
'inside': '',
'inside': '',
'insight': '',
'inspection': '',
'inspector': '',
'inspiration': '',
'installation': '',
'instance': '',
'instant': '',
'instant': '',
'instantly': '',
'instead': '',
'instead': '',
'instinct': '',
'institution': 'inst¬', 'institutions': 'inst¬s',
'institutional': 'institutioɲl',
'instruction': '',
'instructional': 'instructioɲl',
'instructor': '',
'instrument': '',
'insurance': '',
'intact': '',
'integrated': '',
'integration': '',
'integrity': '',
'intellectual': '',
'intellectual': '',
'intelligence': '',
'intelligent': '',
'intense': '',
'intensity': '',
'intent': '',
'intention': '',
'interaction': '',
'interest': '',
'interested': '',
'interesting': '',
'interior': '',
'interior': '',
'internal': 'intrɲl',
'international': 'intrɲtioɲl',
'Internet': '',
'interpretation': '',
'interval': '',
'intervention': '',
'interview': '',
'interface': 'interƒc', 'Interface': 'Interƒc',
'intimate': 'intiɱte',
'into': '',
'introduction': 'intro',
'Introduction': 'Intro',
'invasion': '',
'invention': '',
'inventory': '',
'investigation': 'investiɠt¬',
'investigator': 'investiɠtor',
'investment': '',
'investor': '',
'invisible': '',
'invitation': '',
'involved': '',
'involvement': '',
'Iraqi': '',
'Irish': '',
'iron': '',
'ironically': 'ironiƈł',
'irony': '',
'Islam': '',
'Islamic': '',
'island': '',
'isolated': '',
'isolation': '',
'Israeli': '',
'issue': '',
'it': '',
'Italian': '',
'item': '',
'its': '',
'itself': '',

// H- \\
'habit': 'ɦbit',
'habitat': 'ɦbitat',
'hair': 'ɦir',
'half': 'ɦlf',
'halfway': 'ɦlfway',
'hall': 'ɦl',
'hallway': 'ɦlway',
'hand': 'ɦnd',
'handful': 'ɦndful',
'handle': 'ɦndle',
'handsome': 'ɦndsome',
'happily': 'ɦpił',
'happiness': 'ɦpineß',
'happy': 'ɦpy',
'harassment': 'ɦraßment',
'hard': 'ɦrd',
'hardly': 'ɦrdł',
'hardware': 'ɦrdware',
'harm': 'ɦrm',
'harmony': 'ɦrmony',
'harsh': 'ɦrsh',
'harvest': 'ɦrve§',
'hat': 'ɦt',
'hay': 'ɦy',
'hazard': 'ɦzard',
'he': '',
'head': '',
'headache': 'heaɗche',
'headline': '',
'headquarters': '',
'health': '',
'healthy': '',
'hearing': '',
'heart': '',
'heat': '',
'heaven': '',
'heavily': '',
'heavy': '',
'heel': '',
'height': '',
'helicopter': '',
'hell': '',
'hello': '',
'helmet': '',
'help': '',
'helpful': '',
'hence': '',
'her': '',
'her': '',
'herb': '',
'here': '',
'heritage': '',
'hero': '',
'hers': '',
'herself': '',
'hey': '',
'hi': '',
'hidden': '',
'high': '',
'high': '',
'high-tech': '',
'highly': '',
'highway': '',
'hill': '',
'him': '',
'himself': '',
'hint': '',
'hip': '',
'his': '',
'his': '',
'Hispanic': '',
'historian': '',
'historic': '',
'historical': 'hi§oriƈl',
'historically': 'hi§oriƈł',
'history': '',
'hit': '',
'hockey': '',
'hold': '',
'hole': '',
'holiday': 'holiɗy',
'holy': '',
'home': '',
'home': '',
'homeland': '',
'homeless': '',
'homework': '',
'honest': '',
'honestly': '',
'honey': '',
'honor': '',
'hook': '',
'hope': '',
'hopefully': '',
'horizon': '',
'hormone': '',
'horn': '',
'horrible': '',
'horror': '',
'horse': '',
'hospital': '',
'host': '',
'hostage': '',
'hostile': 'hos~e',
'hot': '',
'hotel': '',
'hour': '',
'house': '',
'household': '',
'housing': '',
'how': '',
'however': '',
'huge': '',
'huh': '',
'human': 'huɱn',
'humanity': 'huɱnity',
'humor': '',
'hundred': '',
'hunger': '',
'hungry': '',
'hunter': '',
'hunting': '',
'hurricane': 'hurriƈne',
'husband': 'husɓnd',
'hypothesis': '',

// J- \\
'jacket': '',
'jail': '',
'Japanese': '',
'jar': '',
'jaw': '',
'jazz': '',
'jeans': '',
'jet': '',
'Jew': '',
'jewelry': '',
'Jewish': '',
'job': '',
'joint': '',
'joke': '',
'journal': 'jouɲl',
'journalism': 'jourɲlism',
'journalist': 'jourɲli§',
'journey': '',
'joy': '',
'judge': '',
'judgment': '',
'judicial': '',
'juice': '',
'jump': '',
'jungle': '',
'junior': '',
'jurisdiction': '',
'juror': '',
'jury': '',
'just': '',
'just': '',
'justice': '',

// K- \\
'key': '',
'kid': '',
'killer': '',
'killing': '',
'kind': '',
'kind': '',
'king': '',
'kingdom': '',
'kiss': '',
'kit': '',
'kitchen': '',
'knee': '',
'knife': '',
'knowledge': '',
'known': '',
'Korean': '',

// L- \\
'look': 'lok', 'looks': 'loks',
'likelyhood': 'l·k·lyh·d',
'likewise': 'l·k·w·s·',
'leave': 'l·ve', 'leaves': 'l·ves',
'leaving': 'l·ving',
'like': 'lk', 'likes': 'lk·s',
'likely': 'lk·ly',
'liking': 'lk·ng',
'liked': 'lk·ed',
'language': 'lang·', 'languages': 'lang·s',
'laboratory': 'lab·',
'laboratories': 'lab·s',
'liability': 'liab·',
'limited': 'l·t·d',
'litigation': 'litiɠt¬',
'large': 'l·g·',
'little': 'lil',
'learn': 'lrn',
'learning': 'lrn·ng',
'learned': 'lrn·ed',


'lab': '',
'label': '',
'labor': '',
'laboratory': '',
'lack': '',
'ladder': '',
'lady': '',
'lake': '',
'lamp': '',
'land': '',
'landing': '',
'landmark': 'landɱrk',
'landscape': 'landsƈp',
'lane': '',
'language': '',
'lap': '',
'large': '',
'largely': '',
'laser': '',
'last': '',
'last': '',
'late': '',
'late': '',
'lately': '',
'later': '',
'later': '',
'Latin': '',
'latter': '',
'laugh': '',
'laughter': '',
'launch': '',
'laundry': '',
'law': '',
'lawmaker': 'lawɱker',
'lawn': '',
'lawsuit': '',
'lawyer': '',
'layer': '',
'lead': '',
'leader': '',
'leadership': '',
'leading': '',
'leaf': '',
'league': '',
'learning': '',
'least': '',
'leather': '',
'leave': '',
'lecture': '',
'left': '',
'leg': '',
'legacy': 'leɠcy',
'legal': 'leɠl',
'legally': 'leɠł',
'legend': '',
'legislation': '',
'legislative': '',
'legislator': '',
'legislature': '',
'legitimate': 'legitiɱte',
'lemon': '',
'length': '',
'lens': '',
'less': '',
'less': '',
'lesson': '',
'letter': '',
'level': '',
'level': '',
'liability': '',
'liberal': '',
'liberal': '',
'liberty': '',
'library': '',
'license': '',
'lid': '',
'lie': '',
'life': '',
'lifestyle': '',
'lifetime': '',
'light': '',
'light': '',
'light': '',
'lighting': '',
'lightly': '',
'lightning': '',
'like': '',
'like': '',
'like': '',
'like': '',
'likelihood': '',
'likely': '',
'likely': '',
'likewise': '',
'limb': '',
'limit': '',
'limitation': '',
'limited': '',
'line': '',
'link': '',
'lion': '',
'lip': '',
'liquid': '',
'liquid': '',
'list': '',
'listener': '',
'literally': '',
'literary': '',
'literature': '',
'little': '',
'little': '',
'little': '',
'live': '',
'liver': '',
'living': '',
'living': '',
'load': '',
'loan': '',
'lobby': '',
'local': 'loƈl',
'location': 'loƈt¬',
'lock': '',
'log': '',
'logic': '',
'logical': 'logiƈl',
'lonely': '',
'long': '',
'long': '',
'long': '',
'long-term': '',
'longtime': '',
'look': '',
'loop': '',
'loose': '',
'loss': '',
'lost': '',
'lot': '',
'lots': '',
'loud': '',
'loud': '',
'love': '',
'lovely': '',
'lover': '',
'low': '',
'low': '',
'loyal': '',
'loyalty': '',
'luck': '',
'lucky': '',
'lunch': '',
'lung': '',

// M- \\
'measure': 'msr', 'measures': 'msrs',
'measuring': 'msr·ng', 'measurings': 'msr·ngs',
'meet': 'mt', 'meets': 'mts',
'meeting': 'mtng', 'meetings': 'mtngs',
'method': 'mthd', 'methods': 'mthds',
'matter': 'ɱtr', 'matters': 'ɱtrs',
'make': 'ɱk', 'makes': 'ɱks',
'making': 'ɱk¬',
'mean': 'mn',
'maintenance': 'ɱinteɲnc',
'medicine': 'med',
'mutual': 'mut',
'minute': 'minu·',
'minutes': 'minu·s',
'medium': 'm·d·',
'millisecond': 'millisec·', 'milliseconds': 'millisec·s',
'message': 'msg', 'messages': 'msgs',
'messaging': 'msg·ng', 'messagings': 'msg·ngs',
'must': 'mst',


'machine': 'ɱch', 'machines': 'ɱchs',
'mad': 'ɱd',
'magazine': 'ɱɠzin',
'magic': 'ɱgic',
'magnetic': 'ɱgnetic',
'magnitude': 'ɱgnitud',
'mail': 'ɱil',
'main': 'ɱin',
'mainly': 'ɱinł',
'mainstream': 'ɱinstream',
'maintenance': 'ɱinteɲnce',
'major': 'ɱjor',
'majority': 'ɱjority',
'maker': 'ɱker',
'makeup': 'ɱkeup',
'male': 'ɱle',
'mall': 'ɱl',
'man': 'ɱn',
'manage': 'ɱɲg', 'manages': 'ɱɲgs',
'manager': 'ɱɲgr', 'managers': 'ɱɲgrs',
'management': 'ɱɲgment',
'managing': 'ɱɲgiŋ',
'mandate': 'ɱnɗt',
'manner': 'ɱner',
'mansion': 'ɱns¬',
'manual': 'ɱnual',
'manufacture': 'ɱnuf',
'manufacturing': 'ɱnufiŋ',
'manufacturer': 'ɱnufer',
'many': 'ɱny',
'map': 'ɱp',
'marble': 'ɱrble',
'margin': 'ɱrgin',
'marine': 'ɱrine',
'mark': 'ɱrk',
'marker': 'ɱrker',

'market': 'ɱkt',
'marketing': 'ɱktiŋ',
'marketplace': 'ɱktplace',
'marriage': 'ɱriag',
'married': 'ɱrið',
'mask': 'ɱsk',
'mass': 'ɱß',
'massive': 'ɱßive',
'master': 'ɱster',
'match': 'ɱtch',
'mate': 'ɱte',
'material': 'ɱterial',
'math': 'ɱŧ',
'mathematics': 'ɱŧeɱtics',
'matter': 'ɱter',
'maximum': 'ɱximum',
'may': 'ɱy',
'maybe': 'ɱybe',
'mayor': 'ɱyor',
'me': '',
'meal': '',
'mean': '',
'mean': '',
'meaning': '',
'meaningful': '',
'meantime': '',
'meanwhile': '',
'measure': '',
'measurement': '',
'meat': '',
'mechanic': 'mech',
'mechanical': 'mechƈl',
'mechanism': 'mechnism',
'medal': 'meɗl',
'media': '',
'medical': 'mediƈl',
'medication': 'mediƈt¬',
'medicine': '',
'medium': '',
'medium': '',
'meeting': '',
'member': '',
'membership': '',
'memory': '',
'mental': '',
'mentally': '',
'mention': '',
'mentor': '',
'menu': '',
'merchant': 'mercɦnt',
'mere': '',
'merely': '',
'merit': '',
'mess': '',
'message': '',
'metal': '',
'metaphor': '',
'meter': '',
'method': '',
'metropolitan': '',
'Mexican': 'Mexiƈn',
'middle': '',
'middle': '',
'middle-class': '',
'midnight': '',
'midst': '',
'might': '',
'migration': '',
'mild': '',
'military': '',
'military': '',
'milk': '',
'mill': '',
'million': '',
'mind': '',
'mine': '',
'mine': '',
'mineral': '',
'minimal': 'miniɱl',
'minimum': '',
'minimum': '',
'minister': '',
'ministry': '',
'minor': '',
'minority': '',
'minute': '',
'miracle': '',
'mirror': '',
'missile': '',
'missing': '',
'mission': '',
'missionary': 'mißioɲry',
'mistake': '',
'mix': '',
'mixed': '',
'mixture': '',
'mm-hmm': '',
'mobile': '',
'mode': '',
'model': '',
'moderate': '',
'modern': '',
'modest': '',
'molecule': '',
'mom': '',
'moment': '',
'momentum': '',
'money': '',
'monitor': '',
'monkey': '',
'monster': '',
'month': '',
'monthly': '',
'monument': '',
'mood': '',
'moon': '',
'moral': '',
'more': '',
'more': '',
'moreover': '',
'morning': '',
'mortality': '',
'mortgage': 'mortɠg',
'most': '',
'most': '',
'mostly': '',
'mother': '',
'motion': '',
'motivation': '',
'motive': '',
'motor': '',
'mountain': '',
'mouse': '',
'mouth': '',
'move': '',
'movement': '',
'movie': '',
'Mr.': '',
'Mrs': '',
'Ms': '',
'much': '',
'much': '',
'mud': '',
'multiple': '',
'municipal': '',
'murder': '',
'muscle': '',
'museum': '',
'mushroom': '',
'music': '',
'musical': 'musiƈl',
'musician': '',
'Muslim': '',
'Muslim': '',
'must': '',
'mutual': '',
'my': '',
'myself': '',
'mysterious': '',
'mystery': '',
'myth': '',

// N- \\
'need': 'nd',
'needs': 'nds',
'needed': 'nded',
'needing': 'ndng',
'national': 'ɲtnl',
'natural': 'ɲtrl',
'necessary': 'ncsry',
'necessarily': 'ncsrly',
'necessitate': 'ncstate',

'nail': 'ɲil',
'naked': 'ɲkð',
'name': 'ɲme',
'narrative': 'ɲrative',
'narrow': 'ɲrow',
'nasty': 'ɲsty',
'nation': 'ɲt¬',
'national': 'ɲt¬l',
'nationwide': 'ɲt¬wide',
'native': 'ɲtiv',
'natural': 'ɲtural',
'naturally': 'ɲturał',
'nature': 'ɲture',
'naval': 'ɲval',
'near': '',
'near': '',
'near': '',
'nearby': '',
'nearby': '',
'nearly': '',
'neat': '',
'necessarily': '',
'necessary': '',
'necessity': '',
'neck': '',
'need': '',
'needle': '',
'negative': 'nɠtiv', 'negatives': 'nɠtivs',
'negotiation': '',
'neighbor': '',
'neighborhood': '',
'neighboring': '',
'neither': '',
'neither': '',
'nerve': '',
'nervous': '',
'nest': '',
'net': '',
'net': '',
'network': '',
'neutral': '',
'never': '',
'nevertheless': '',
'new': '',
'newly': '',
'news': '',
'newspaper': '',
'next': '',
'next': '',
'nice': '',
'night': '',
'nightmare': 'nightɱre',
'nine': '',
'no': '',
'nobody': '',
'noise': '',
'nomination': 'nomiɲt¬',
'nominee': '',
'none': '',
'nonetheless': '',
'nonprofit': '',
'noon': '',
'nor': '',
'norm': '',
'normal': 'norɱl',
'normally': 'norɱł',
'north': '',
'northeast': '',
'northern': '',
'northwest': '',
'nose': '',
'not': '',
'not': '',
'note': '',
'notebook': '',
'nothing': '',
'notice': '',
'notion': '',
'novel': '',
'now': '',
'now': '',
'nowhere': '',
'nuclear': '',
'number': '',
'numerous': '',
'nurse': '',
'nut': '',
'nutrient': '',

// O- \\
'over': 'ovr',
'overall': 'ovral',
'official': 'ofc',
'officially': 'ofly',
'opinion': 'opi',
'order': 'ord',
'opportunity': 'optnty',

'oak': '',
'object': '',
'objection': '',
'objective': '',
'obligation': 'oblig',
'observation': '',
'observer': '',
'obstacle': '',
'obvious': '',
'obviously': '',
'occasion': 'oƈs¬',
'occasional': 'oƈs¬al',
'occasionally': 'oƈs¬ał',
'occupation': '',
'ocean': '',
'odd': '',
'odds': '',
'of': '',
'off': '',
'off': '',
'offender': '',
'offense': '',
'offensive': '',
'offer': '',
'offering': '',
'office': '',
'officer': '',
'official': '',
'official': '',
'officially': '',
'often': '',
'oh': '',
'oil': '',
'ok': '',
'OK': '',
'okay': 'oƙy',
'old': '',
'old-fashioned': 'old-ƒshionð',
'Olympic': '',
'Olympics': '',
'on': '',
'on': '',
'once': '',
'once': '',
'one': '',
'one': '',
'one': '',
'one-third': '',
'ongoing': '',
'onion': '',
'online': '',
'online': '',
'only': '',
'only': '',
'onto': '',
'open': '',
'opening': '',
'openly': '',
'opera': '',
'operating': '',
'operation': '',
'operator': '',
'opinion': '',
'opponent': '',
'opportunity': '',
'opposed': '',
'opposite': '',
'opposition': '',
'optimistic': '',
'option': '',
'or': '',
'oral': '',
'orange': '',
'orange': '',
'orbit': '',
'order': '',
'ordinary': 'ordiɲry',
'organ': 'orɠn',
'organic': 'orɠnic',
'organism': 'orɠnism',
'organization': 'org', 'organizations': 'orgs',
'organizational': 'orgɲl',
'organized': 'orɠnizð',
'orientation': '',
'origin': '',
'original': 'orig',
'originally': 'origɲł',
'other': '',
'other': '',
'other': '',
'others': '',
'otherwise': '',
'ought': '',
'our': '',
'ours': '',
'ourselves': '',
'out': '',
'out': '',
'outcome': '',
'outdoor': '',
'outer': '',
'outfit': '',
'outlet': '',
'output': '',
'outside': '',
'outside': '',
'outside': '',
'outsider': '',
'outstanding': '',
'oven': '',
'over': '',
'over': '',
'overall': '',
'overall': '',
'overnight': '',
'overwhelming': '',
'own': '',
'owner': '',
'ownership': '',
'oxygen': '',

// P- \\
'provide': 'prvd', 'provides': 'prvds',
'program': 'prgm', 'programs': 'prgms',
'president': 'prsdt',
'partnership': 'pship',
'person': 'prs',
'people': 'ppl',
'personal': 'prsɲl',
'politic': 'plt', 'politics': 'plts',
'political': 'poli',
'probability': 'proɓ',
'probabilities': 'proɓies',
'power': 'pwr',
'production': 'prod·tion',
'profession': 'profe',
'professional': 'profeɲl',
'property': 'prop·',
'protection': 'prot·', 'protections': 'prot·s',
'public': 'pub·',
'publication': 'publi', 'publications': 'publis',
'publishing': 'pub·shing',
'progress': 'prog·',
'progressive': 'prog·ve',
'progressed': 'prog·ed',
'problem': 'prob·', 'problems': 'prob·s',
'prerequisite': 'prereq·', 'prerequisites': 'prereq·s',
'prefer': 'pfr', 'prefers': 'pfrs',
'preferred': 'pfr·ed',
'preference': 'pfrnc', 'preferences': 'pfrncs',

'pace': '',
'pack': '',
'package': 'pacƙg',
'pad': '',
'page': '',
'pain': '',
'painful': '',
'paint': '',
'painter': '',
'painting': '',
'pair': '',
'palace': '',
'pale': '',
'Palestinian': '',
'palm': '',
'pan': '',
'panel': '',
'panic': '',
'pant': '',
'paper': '',
'parade': '',
'parent': '',
'parental': '',
'parish': '',
'park': '',
'parking': '',
'part': '',
'part': '',
'part': '',
'partial': '',
'partially': '',
'participant': '',
'participation': '',
'particle': '',
'particular': '',
'particular': '',
'particularly': '',
'partly': '',
'partner': '',
'partnership': '',
'party': '',
'pass': '',
'passage': '',
'passenger': '',
'passing': '',
'passion': '',
'past': '',
'past': '',
'past': '',
'past': '',
'pasta': '',
'pastor': '',
'patch': '',
'patent': '',
'path': '',
'patience': '',
'patient': '',
'patient': '',
'patrol': '',
'patron': '',
'pattern': '',
'pause': '',
'pay': '',
'payment': '',
'peace': '',
'peaceful': '',
'peak': '',
'peanut': '',
'peasant': '',
'peer': '',
'pen': '',
'penalty': 'peɲlty',
'pencil': '',
'pension': '',
'people': '',
'pepper': '',
'per': '',
'perceived': '',
'percentage': '',
'perception': '',
'perfect': '',
'perfectly': '',
'perform': 'prfrm', 'performs': 'prfrms',
'performance': 'prfɱc', 'performances': 'prfɱcs',
'performer': '',
'perhaps': 'perɦps',
'period': '',
'permanent': 'perɱnent',
'permission': '',
'permit': '',
'Persian': '',
'person': '',
'personal': 'persoɲl',
'personality': 'persoɲlity',
'personally': 'persoɲł',
'personnel': '',
'perspective': '',
'pet': '',
'phase': 'pɦse',
'phenomenon': '',
'philosophical': 'philosophiƈl',
'philosophy': '',
'phone': '',
'photo': '',
'photograph': '',
'photographer': '',
'photography': '',
'phrase': '',
'physical': 'physiƈl',
'physically': 'physiƈł',
'physician': '',
'physics': '',
'piano': '',
'pickup': '',
'picture': '',
'pie': '',
'piece': '',
'pig': '',
'pile': '',
'pill': '',
'pillow': '',
'pilot': '',
'pin': '',
'pine': '',
'pink': '',
'pioneer': '',
'pipe': '',
'pistol': '',
'pit': '',
'pitch': '',
'pitcher': '',
'pizza': '',
'place': '',
'placement': '',
'plain': '',
'plain': '',
'plaintiff': '',
'plan': '',
'plane': '',
'planet': '',
'planner': '',
'planning': '',
'plant': '',
'plastic': '',
'plate': '',
'platform': '',
'play': '',
'player': '',
'playoff': '',
'plea': '',
'pleasant': '',
'please': '',
'pleased': '',
'pleasure': '',
'plenty': '',
'plot': '',
'plus': '',
'PM': '',
'pocket': '',
'poem': '',
'poet': '',
'poetry': '',
'point': '',
'pole': '',
'police': '',
'policeman': 'policeɱn',
'policy': '',
'political': 'politiƈl',
'politically': 'politiƈł',
'politician': '',
'politics': '',
'poll': '',
'pollution': '',
'pond': '',
'pool': '',
'poor': '',
'pop': '',
'popular': '',
'popularity': '',
'population': '',
'porch': '',
'pork': '',
'port': '',
'portfolio': '',
'portion': '',
'portrait': '',
'position': '',
'positive': '',
'possession': '',
'possibility': '',
'possible': '',
'possibly': '',
'post': '',
'poster': '',
'pot': '',
'potato': '',
'potential': '',
'potential': '',
'potentially': '',
'pound': '',
'poverty': '',
'powder': '',
'power': '',
'powerful': '',
'practical': 'practiƈl',
'practically': 'practiƈł',
'practice': '',
'practitioner': '',
'praise': '',
'prayer': '',
'precious': '',
'precise': '',
'precisely': '',
'predator': 'preɗtor',
'prediction': '',
'preference': '',
'pregnancy': 'pregɲncy',
'pregnant': 'pregɲnt',
'preliminary': 'prelimiɲry',
'premise': '',
'premium': '',
'preparation': '',
'prescription': '',
'presence': '',
'present': '',
'present': '',
'presentation': '',
'presidency': '',
'president': '',
'presidential': '',
'press': '',
'pressure': '',
'presumably': 'presuɱbł',
'pretty': '',
'pretty': '',
'prevention': '',
'previous': '',
'previously': '',
'price': '',
'pride': '',
'priest': '',
'primarily': 'priɱrił',
'primary': 'priɱry',
'prime': '',
'principal': '',
'principal': '',
'principle': '',
'print': '',
'prior': '',
'prior': '',
'priority': '',
'prison': '',
'prisoner': '',
'privacy': '',
'private': '',
'privately': '',
'privilege': '',
'prize': '',
'pro': '',
'probably': 'proɓbł',
'problem': '',
'procedure': '',
'process': '',
'processing': '',
'processor': '',
'producer': '',
'product': '',
'production': '',
'productive': '',
'productivity': '',
'profession': '',
'professional': 'profeßioɲl',
'professor': '',
'profile': '',
'profit': '',
'profound': '',
'program': '',
'programming': '',
'progress': '',
'progressive': '',
'project': '',
'projection': '',
'prominent': '',
'promise': '',
'promising': '',
'promotion': '',
'proof': '',
'proper': '',
'properly': '',
'property': '',
'proportion': '',
'proposal': '',
'proposed': '',
'prosecution': '',
'prosecutor': '',
'prospect': '',
'protection': '',
'protective': '',
'protein': '',
'protest': '',
'protocol': '',
'proud': '',
'provided': '',
'provider': '',
'province': '',
'provision': '',
'psychology': 'psyc·gy',
'psychological': 'psyc·ƈl',
'psychologist': 'psyc·§',
'public': '',
'publication': 'publiƈt¬',
'publicity': '',
'publicly': '',
'publisher': '',
'pulse': '',
'pump': '',
'punishment': '',
'purchase': 'purcɦse',
'pure': '',
'purple': '',
'purpose': '',
'purse': '',
'pursuit': '',
'puzzle': '',

// Q- \\
'quality': '',
'quantity': '',
'quarter': '',
'quarterback': 'quarterɓk',
'queen': '',
'quest': '',
'question': '',
'questionnaire': 'questionɲire',
'quick': '',
'quickly': '',
'quiet': '',
'quietly': '',
'quite': '',
'quote': '',

// R- \\
'random': 'rndm',
'recent': 'rcnt', 'recents': 'rcnts',
'recently': 'rcntly',
'result': 'rslt', 'results': 'rslts',
'reason': 'rsn', 'reasons': 'rsns',
'room': 'ro·m', 'rooms': 'ro·ms',
'retirement': 'ret·',
'search': 'srch', 'searches': 'srchs',
'research': 'rsch·', 'researchs': 'rschs',
'reproduction': 'reprod·',
'regional': 'regɲl',
'refining': 'ref·ng',
'remember': 'remeb·', 'remembers': 'remeb·s',
'record': 'reco·', 'records': 'reco·s',
'recording': 'reco·ng', 'recordings': 'reco·ngs',
'refine': 'ref·', 'refines': 'ref·s',
'region': 'regi·', 'regions': 'regi·s',
'register': 'reg·', 'registers': 'reg·s',
'regulation': 'regul·', 'regulations': 'regul·s',
'relation': 'rel·', 'relations': 'rel·s',
'relationship': 'rel·ship', 'relationships': 'rel·ships',
'resource': 'res·', 'resources': 'res·s',
'restaurant': 'resta·', 'restaurants': 'resta·s',
'road': 'r·d', 'roads': 'r·ds',
'require': 'req·', 'requires': 'req·s',
'required': 'req·ed',
'requisite': 'req·s·t', 'requisites': 'req·s·t·s',
'recipe': 'rcp', 'recipes': 'rcps',


'rabbit': '',
'race': '',
'racial': '',
'racism': '',
'rack': '',
'radar': 'raɗr',
'radiation': '',
'radical': 'radiƈl',
'radio': '',
'rage': '',
'rail': '',
'railroad': '',
'rain': '',
'rally': '',
'ranch': '',
'random': '',
'range': '',
'rank': '',
'rape': '',
'rapid': '',
'rapidly': '',
'rare': '',
'rarely': '',
'rat': '',
'rate': '',
'rather': '',
'rather': '',
'rather': '',
'rating': '',
'ratio': '',
'rational': 'ratioɲl',
'raw': '',
're': '',
'reach': '',
'reaction': '',
'reader': '',
'readily': '',
'reading': '',
'ready': '',
'real': '',
'realistic': '',
'reality': '',
'really': '',
'realm': '',
'rear': '',
'reason': '',
'reasonable': 'reasoɲble',
'rebel': '',
'receiver': '',
'recent': '',
'recently': '',
'reception': '',
'recession': '',
'recipe': '',
'recipient': '',
'recognition': '',
'recommendation': 'recomenɗt¬',
'record': '',
'recording': '',
'recovery': '',
'red': '',
'reduction': '',
'reference': '',
'reflection': '',
'reform': '',
'refrigerator': '',
'refuge': '',
'refugee': '',
'regard': 'reɠrd',
'regard': 'reɠrd',
'regarding': 'reɠrdŋ',
'regardless': 'reɠrdleß',
'regime': '',
'region': '',
'regional': 'regioɲl',
'regular': '',
'regularly': '',
'regulation': '',
'regulator': '',
'regulatory': '',
'rehabilitation': 'reɦb',
'related': '',
'relation': '',
'relationship': '',
'relative': '',
'relative': '',
'relatively': '',
'release': '',
'relevant': '',
'reliability': '',
'reliable': '',
'relief': '',
'religion': '',
'religious': '',
'reluctant': '',
'remaining': 'reɱiniŋ',
'remark': 'reɱrk',
'remarkable': 'reɱrƙble',
'reminder': '',
'remote': '',
'removal': '',
'rent': '',
'rental': '',
'repair': '',
'repeatedly': '',
'replacement': '',
'report': '',
'reportedly': '',
'reporter': '',
'reporting': '',
'representation': '',
'representative': '',
'representative': '',
'republic': '',
'Republican': 'Republiƈn',
'republican': 'republiƈn',
'reputation': '',
'request': '',
'required': '',
'requirement': '',
'rescue': '',
'research': '',
'researcher': '',
'reservation': '',
'reserve': '',
'residence': '',
'resident': '',
'residential': '',
'resistance': '',
'resolution': '',
'resort': '',
'resource': '',
'respect': '',
'respect': '',
'respectively': '',
'respondent': '',
'response': '',
'response': '',
'responsibility': '',
'responsible': '',
'rest': '',
'restaurant': '',
'restriction': '',
'result': '',
'retail': '',
'retailer': '',
'retired': '',
'retirement': '',
'retreat': '',
'return': '',
'revelation': 'revelat¬',
'revenue': '',
'review': '',
'revolution': '',
'revolutionary': 'revolut¬ary',
'reward': '',
'rhetoric': '',
'rhythm': '',
'rib': '',
'ribbon': '',
'rice': '',
'rich': '',
'ride': '',
'rider': '',
'ridge': '',
'ridiculous': '',
'rifle': '',
'right': '',
'right': '',
'right': '',
'rim': '',
'ring': '',
'riot': '',
'rise': '',
'risk': '',
'risky': '',
'ritual': '',
'rival': '',
'river': '',
'road': '',
'robot': '',
'rock': '',
'rocket': '',
'rod': '',
'role': '',
'roll': '',
'rolling': '',
'Roman': 'Roɱn',
'romance': 'roɱnce',
'romantic': 'roɱntic',
'roof': '',
'room': '',
'root': '',
'rope': '',
'rose': '',
'rough': '',
'roughly': '',
'round': '',
'round': '',
'route': '',
'routine': '',
'routinely': '',
'row': '',
'royal': '',
'rubber': '',
'rule': '',
'ruling': '',
'rumor': '',
'run': '',
'runner': '',
'running': '',
'running': '',
'rural': '',
'rush': '',
'Russian': '',

// S- & ss = ß \\
'still': 's~',
'state': 'ste',
'start': 'strt', 'starts': 'strts',
'starting': 'strtng',
'started': 'strted',
'some': 'sm',
'standard': 'stnɗrd', 'standards': 'stnɗrds',
'separate': 'sprt', 'separates': 'sprts',
'secret': 'scrt',
'secrets': 'scrts',
'separating': 'sprt·ng', 'separatings': 'sprt·ngs',
'success': 'scs',
'successful': 'scsfl',
'startup': 'stup', 'startups': 'stups',
'straight': 'str8',
'social': 'soc·',
'superpower': 'sprpwr', 'superpowers': 'sprpwrs',
'school': 'sch', 'schools': 'schs',
'security': 'sec·', 'securities': 'sec·s',
'service': 'serv·', 'services': 'serv·s',
'shareholder': 'sɦrholder', 'shareholders': 'sɦrholders',
'solution': 'sltn', 'solutions': 'sltns',
'street': 'st·', 'streets': 'st·s',
'system': 'sys·', 'systems': 'sys·s',
'second': 'sec·', 'seconds': 'sec·s',
'serious': 'srs',
'seriosly': 'srsł',
'shopping': 'shpng',
'significant': 'signifiƈnt',

'sack': '',
'sacred': '',
'sacrifice': '',
'sad': '',
'safe': '',
'safely': '',
'safety': '',
'sake': '',
'salad': '',
'salary': '',
'sale': '',
'sales': '',
'salmon': '',
'salt': '',
'same': '',
'sample': '',
'sanction': '',
'sand': '',
'sandwich': '',
'satellite': '',
'satisfaction': 'satisƒct¬',
'sauce': '',
'saving': '',
'scale': 'sƈle',
'scandal': 'sƈnɗl',
'scared': 'sƈrð',
'scary': 'sƈry',
'scenario': 'sceɲrio',
'scene': '',
'scent': '',
'schedule': '',
'scheme': '',
'scholar': '',
'scholarship': '',
'school': '',
'science': 'sci', 'sciences': 'scis',
'scientific': 'scific',
'scientifically': 'scifiƈł',
'scientist': 'sciti§',
'scope': '',
'score': '',
'screen': '',
'screening': '',
'script': '',
'sculpture': '',
'sea': '',
'seal': '',
'search': '',
'season': '',
'seat': '',
'second': '',
'secondary': 'seconɗry',
'secret': '',
'secret': '',
'secretary': '',
'section': '',
'sector': '',
'secular': '',
'secure': '',
'security': '',
'seed': '',
'seemingly': '',
'segment': '',
'seldom': '',
'selected': '',
'selection': '',
'self': '',
'self-esteem': '',
'seller': '',
'seminar': 'semiɲr',
'Senate': 'Seɲt',
'senator': 'seɲtor',
'senior': '',
'senior': '',
'sensation': '',
'sense': '',
'sensitive': '',
'sensitivity': '',
'sensor': '',
'sentence': '',
'sentiment': '',
'separate': '',
'separation': '',
'sequence': '',
'series': '',
'serious': '',
'seriously': '',
'servant': '',
'service': '',
'serving': '',
'session': '',
'set': '',
'setting': '',
'settlement': '',
'seven': '',
'seventh': '',
'several': '',
'severe': '',
'severely': '',
'sex': '',
'sexual': '',
'sexuality': '',
'sexually': '',
'sexy': '',
'shade': 'sɦd',
'shadow': 'sɦdow',
'shallow': 'sɦlow',
'shame': 'sɦm',
'shape': 'sɦp',
'share': 'sɦre',
'shared': 'sɦrð',
'shark': 'sɦrk',
'sharp': 'sɦrp',
'sharply': 'sɦrpł',
'she': '',
'sheep': '',
'sheer': '',
'sheet': '',
'shelf': '',
'shell': '',
'shelter': '',
'shift': '',
'ship': '',
'shirt': '',
'shit': '',
'shock': '',
'shoe': '',
'shooting': '',
'shop': '',
'shopping': '',
'shore': '',
'short': '',
'short': '',
'short-term': '',
'shortage': '',
'shortly': '',
'shorts': '',
'shot': '',
'should': '',
'shoulder': '',
'show': '',
'shower': '',
'shrimp': '',
'shuttle': '',
'shy': '',
'sibling': '',
'sick': '',
'side': '',
'sidewalk': '',
'sight': '',
'sign': '',
'signal': 'sigɲl',
'signature': 'sigɲture',
'significance': 'signifiƈnce',
'significant': 'signifiƈnt',
'significantly': 'signifiƈntł',
'silence': '',
'silent': '',
'silk': '',
'silly': '',
'silver': '',
'similar': '',
'similarity': '',
'similarly': '',
'simple': '',
'simply': '',
'simultaneously': '',
'sin': '',
'since': '',
'since': '',
'since': '',
'singer': '',
'single': '',
'sink': '',
'sir': '',
'sister': '',
'site': '',
'situation': '',
'six': '',
'sixth': '',
'size': '',
'skill': 'skl', 'skills': 'skls',
'skilled': '',
'skin': '',
'skirt': '',
'skull': '',
'sky': '',
'slave': '',
'slavery': '',
'sleep': '',
'sleeve': '',
'slice': '',
'slide': '',
'slight': '',
'slightly': '',
'slope': '',
'slot': '',
'slow': '',
'slowly': '',
'small': 'sɱl',
'smart': 'sɱrt',
'smell': '',
'smile': '',
'smoke': '',
'smooth': '',
'snake': 'sɲke',
'snow': '',
'so': '',
'so': '',
'so-called': 'so-ƈlð',
'soap': '',
'soccer': '',
'social': '',
'socially': '',
'society': '',
'sock': '',
'sodium': '',
'sofa': 'soƒ',
'soft': '',
'softly': '',
'software': '',
'soil': '',
'solar': '',
'soldier': '',
'sole': '',
'solely': '',
'solid': '',
'solution': '',
'some': '',
'somebody': '',
'someday': 'someɗy',
'somehow': '',
'someone': '',
'something': '',
'sometime': '',
'sometimes': '',
'somewhat': 'somw@',
'somewhere': '',
'son': '',
'song': '',
'soon': '',
'soon': '',
'sophisticated': 'sophistiƈtð',
'sorry': '',
'sort': '',
'soul': '',
'sound': '',
'soup': '',
'source': '',
'south': '',
'southeast': '',
'southern': '',
'southwest': '',
'sovereignty': '',
'Soviet': '',
'space': '',
'Spanish': '',
'speaker': '',
'special': '',
'specialist': '',
'specialty': '',
'species': '',
'specific': '',
'specifically': 'soecifiƈł',
'spectacular': '',
'spectrum': '',
'speculation': '',
'speech': '',
'speed': '',
'spending': '',
'sphere': '',
'spine': '',
'spirit': '',
'spiritual': '',
'spite': '',
'spokesman': 'spokesɱn',
'sponsor': '',
'spoon': '',
'sport': '',
'spot': '',
'spouse': '',
'spray': '',
'spread': '',
'spring': '',
'spy': '',
'squad': '',
'square': '',
'square': '',
'stability': '',
'stable': '',
'stack': '',
'stadium': '',
'staff': '',
'stage': '',
'stair': '',
'stake': '',
'stance': '',
'stand': '',
'standing': '',
'star': '',
'start': '',
'starter': '',
'starting': '',
'state': '',
'statement': '',
'station': '',
'statistical': 'statsƈl',
'statistics': 'stats',
'statue': '',
'status': '',
'statute': '',
'stay': '',
'steadily': '',
'steady': '',
'steak': '',
'steam': '',
'steel': '',
'steep': '',
'stem': '',
'step': '',
'stereotype': '',
'stick': '',
'stiff': '',
'stimulus': '',
'stock': '',
'stomach': 'stoɱch',
'stone': '',
'stop': '',
'storage': '',
'store': '',
'storm': '',
'story': '',
'stove': '',
'straight': '',
'straight': '',
'strain': '',
'strange': '',
'stranger': '',
'strategic': '',
'strategy': '',
'straw': '',
'streak': '',
'stream': '',
'street': '',
'strength': '',
'stress': '',
'stretch': '',
'strict': '',
'strictly': '',
'strike': '',
'striking': '',
'string': '',
'strip': '',
'stroke': '',
'strong': '',
'strongly': '',
'structural': '',
'structure': '',
'struggle': '',
'student': '',
'studio': '',
'study': '',
'stuff': '',
'stupid': '',
'style': '',
'subject': '',
'subject': '',
'subsequent': '',
'subsidy': '',
'substance': '',
'substantial': '',
'substantially': '',
'subtle': '',
'suburb': '',
'suburban': 'suburɓn',
'success': '',
'successful': '',
'successfully': '',
'such': '',
'such': '',
'sudden': '',
'sudden': '',
'suddenly': '',
'suffering': '',
'sufficient': '',
'sugar': 'suɠr',
'suggestion': '',
'suicide': '',
'suit': '',
'suitable': '',
'suite': '',
'sum': '',
'summary': 'suɱry',
'summer': '',
'summit': '',
'sun': '',
'sunlight': '',
'sunny': '',
'super': '',
'superior': '',
'supermarket': 'superɱrket',
'supervisor': '',
'supplier': '',
'supply': '',
'support': '',
'supporter': '',
'supportive': '',
'supposed': '',
'supposedly': '',
'Supreme': '',
'sure': '',
'sure': '',
'surely': '',
'surface': 'surƒc',
'surgeon': '',
'surgery': '',
'surprise': '',
'surprised': '',
'surprising': '',
'surprisingly': '',
'surrounding': '',
'surveillance': '',
'survey': '',
'survival': '',
'survivor': '',
'suspect': '',
'suspicion': '',
'suspicious': '',
'sustainable': 'sustaiɲble',
'sweat': '',
'sweater': '',
'sweet': '',
'swimming': '',
'swing': '',
'switch': '',
'sword': '',
'symbol': '',
'symbolic': '',
'sympathy': '',
'symptom': '',
'syndrome': '',
'system': '',

// T- \\
'the': 't',
'they': 'ŧey',
'their': 'ŧeir',
'these': 'ŧse',
'time': 'tm',
'there': 'ŧere',
'thereby': 'ŧreby',
'them': 'ŧem',
'think': 'ŧink',
'thinking': 'ŧnkŋ',
'take': 'tk',
'through': 'ŧrough',
'test': 'tst', 'tests': 'tst·s',
'testing': 'tst·ng', 'testings': 'tst·ngs',
'tomorrow': 'tmrw',
'temporary': 'temp·',
'teacher': 'tchr', 'teachers': 'tchrs',
'telephone': 'tel', 'telephones': 'tels',
'technology': 'tech', 'technologies': 'techs',
'traditional': 'trad',
'three': 'ŧrē',

'T-shirt': '',
'table': '',
'tablespoon': '',
'tactic': '',
'tag': '',
'tail': '',
'tale': '',
'talent': '',
'talented': '',
'talk': '',
'tall': '',
'tank': '',
'tape': '',
'target': '',
'task': '',
'taste': '',
'tax': '',
'taxpayer': '',
'tea': '',
'teacher': '',
'teaching': '',
'team': '',
'teammate': 'teamɱte',
'tear': '',
'teaspoon': '',
'technical': 'techniƈl',
'technician': '',
'technique': '',
'technological': 'technologiƈl',
'technology': '',
'teen': '',
'teenage': 'tēɲge',
'teenager': 'tēɲger',
'telephone': '',
'telescope': '',
'television': '',
'temperature': '',
'temple': '',
'temporary': '',
'ten': '',
'tendency': '',
'tender': '',
'tennis': '',
'tension': '',
'tent': '',
'term': '',
'terms': '',
'terrain': '',
'terrible': '',
'terribly': '',
'terrific': '',
'territory': '',
'terror': '',
'terrorism': '',
'terrorist': '',
'terrorist': '',
'test': '',
'testimony': '',
'testing': '',
'text': '',
'textbook': '',
'texture': '',
'than': 'ŧan',
'thanks': 'ŧanks',
'Thanksgiving': 'ŧanksgiviŋ',
'that': 'ŧa',
'theater': 'ŧeater',
'their': '',
'them': '',
'theme': '',
'themselves': 'ŧmslvs',
'then': '',
'theological': 'ŧeologiƈl',
'theology': '',
'theoretical': 'ŧeoretiƈl',
'theory': '',
'therapist': '',
'therapy': '',
'There': 'Ŧer',
'thereby': '',
'therefore': '',
'these': '',
'they': '',
'thick': '',
'thigh': '',
'thin': '',
'thing': '',
'thinking': '',
'third': '',
'thirty': '',
'this': '',
'this': '',
'thoroughly': '',
'those': '',
'though': 'ŧough',
'thought': 'ŧought',
'thousand': '',
'thread': '',
'threat': '',
'three': '',
'threshold': '',
'throat': '',
'through': '',
'through': '',
'throughout': '',
'thumb': '',
'thus': '',
'ticket': '',
'tide': '',
'tie': '',
'tight': '',
'tight': '',
'tightly': '',
'tile': '~e',
'till': '~',
'timber': '',
'time': '',
'timing': '',
'tiny': '',
'tip': '',
'tired': '',
'tissue': '',
'title': '',
'to': '',
'tobacco': 'toɓco',
'today': 'toɗy',
'toe': '',
'together': '',
'toilet': '',
'tolerance': '',
'toll': '',
'tomato': 'toɱto',
'tomorrow': '',
'tone': '',
'tongue': '',
'tonight': '',
'too': '',
'tool': '',
'tooth': '',
'top': '',
'top': '',
'top': '',
'topic': '',
'total': '',
'total': '',
'totally': '',
'touch': '',
'touchdown': '',
'tough': '',
'tour': '',
'tourism': '',
'tourist': '',
'tournament': 'tourɲment',
'toward': '',
'towards': '',
'towel': '',
'tower': '',
'town': '',
'toxic': '',
'toy': '',
'trace': '',
'track': '',
'trade': '',
'trading': '',
'tradition': 'tradt¬',
'traditional': 'trad',
'traditionally': 'tradɲł',
'traffic': '',
'tragedy': '',
'tragic': '',
'trail': '',
'trailer': '',
'train': '',
'trainer': '',
'training': '',
'trait': '',
'transaction': '',
'transfer': '',
'transformation': 'transforɱt¬',
'transit': '',
'transition': '',
'translation': '',
'transmission': '',
'transport': '',
'transportation': '',
'trap': '',
'trash': '',
'trauma': 'trauɱ',
'travel': '',
'traveler': '',
'tray': '',
'treasure': '',
'treatment': '',
'treaty': '',
'tree': '',
'tremendous': '',
'trend': '',
'trial': '',
'tribal': 'triɓl',
'tribe': '',
'trick': '',
'trip': '',
'triumph': '',
'troop': '',
'tropical': 'tropiƈl',
'trouble': '',
'troubled': '',
'truck': '',
'true ': '',
'truly': '',
'trunk': '',
'trust': '',
'truth': '',
'tube': '',
'tumor': '',
'tune': '',
'tunnel': '',
'turkey': '',
'turn': '',
'TV': '',
'twelve': '',
'twentieth': '',
'twenty': '',
'twice': '',
'twin': '',
'twist': '',
'two': '',
'two-thirds': '',
'type': '',
'typical': 'typiƈl',
'typically': 'typiƈł',

// U- \\
'under': 'ndr',
'understand': 'ndrtd',
'uniform': 'unif',
'university': 'uni',
'utility': 'u~t',

'ugly': '',
'uh': '',
'ultimate': 'ultiɱte',
'ultimately': 'ultiɱteł',
'unable': 'uɲble',
'uncertain': '',
'uncertainty': '',
'uncle': '',
'uncomfortable': '',
'under': '',
'under': '',
'undergraduate': '',
'underlying': '',
'understanding': '',
'unemployment': '',
'unexpected': '',
'unfair': 'unƒir',
'unfortunately': 'unfortuɲteł',
'unhappy': 'unɦpy',
'uniform': '',
'union': '',
'unique': '',
'unit': '',
'United': '',
'unity': '',
'universal': '',
'universe': '',
'university': '',
'unknown': '',
'unless': '',
'unlike': '',
'unlike': '',
'unlikely': '',
'unprecedented': '',
'until': 'un~',
'unusual': '',
'up': '',
'up': '',
'upon': '',
'upper': '',
'upset': '',
'upstairs': '',
'urban': 'urɓn',
'us': '',
'use': '',
'used': '',
'useful': '',
'user': '',
'usual': '',
'usually': '',

// V- \\
'validate': 'valɗt', 'validate': 'valɗts',

'vacation': 'vaƈt¬',
'vaccine': '',
'vacuum': '',
'valid': '',
'validity': '',
'valley': '',
'valuable': '',
'value': '',
'van': '',
'variable': '',
'variation': '',
'variety': '',
'various': '',
'vast': '',
'vegetable': '',
'vehicle': '',
'vendor': '',
'venture': '',
'verbal': 'verɓl',
'verdict': '',
'version': 'vrsn',
'versus': '',
'vertical': 'vertiƈl',
'very': '',
'very': '',
'vessel': '',
'veteran': '',
'veteran': '',
'via': '',
'victim': '',
'victory': '',
'video': '',
'view': '',
'viewer': '',
'village': 'vilg',
'violation': '',
'violence': '',
'violent': '',
'virtual': '',
'virtually': '',
'virtue': '',
'virus': '',
'visible': '',
'vision': '',
'visit': '',
'visitor': '',
'visual': '',
'vital': '',
'vitamin': '',
'vocal': 'voƈl',
'voice': '',
'volume': '',
'voluntary': '',
'volunteer': '',
'vote': '',
'voter': '',
'voting': '',
'vulnerable': '',

// W- \\
'wisdom': 'wsdm',
'wait': 'w8',
'work': 'wrk',
'working': 'wrkng',
'worked': 'wrked',

'wage': '',
'wagon': '',
'waist': '',
'wake': '',
'walk': '',
'walking': '',
'wall': '',
'war': '',
'warehouse': '',
'warm': '',
'warmth': '',
'warning': '',
'warrior': '',
'waste': '',
'watch': '',
'water': '',
'wave': '',
'way': '',
'way': '',
'we': '',
'weak': '',
'weakness': '',
'wealth': '',
'wealthy': '',
'weapon': '',
'weather': '',
'web': '',
'wedding': '',
'weed': '',
'week': '',
'weekend': '',
'weekly': '',
'weight': '',
'weird': '',
'welcome': '',
'welfare': 'welƒr',
'well': '',
'well': '',
'well-being': '',
'well-known': '',
'west': '',
'western': '',
'wet': '',
'whale': 'wɦle',
'what': 'w@',
'whatever': 'w@vr',
'wheat': '',
'wheel': '',
'wheelchair': 'whēlchär',
'when': '',
'when': '',
'whenever': '',
'where': '',
'where': '',
'whereas': '',
'wherever': '',
'whether': '',
'which': '',
'while': '',
'white': '',
'who': '',
'whoever': '',
'whole': '',
'whole': '',
'whom': '',
'whose': '',
'why': 'y',
'wide': '',
'widely': '',
'widespread': '',
'widow': '',
'wife': '',
'wild': '',
'wilderness': '',
'wildlife': '',
'will': '',
'will': '',
'willing': '',
'willingness': '',
'win': '',
'wind': '',
'window': '',
'wine': '',
'wing': '',
'winner': '',
'winter': '',
'wire': '',
'wisdom': '',
'wise': '',
'wish': '',
'with': '',
'withdrawal': '',
'within': '',
'within': '',
'without': '',
'witness': '',
'wolf': '',
'woman': 'woɱn',
'wonder': '',
'wonderful': '',
'wood': '',
'wooden': '',
'word': '',
'work': '',
'worker': '',
'working': '',
'workout': '',
'workplace': '',
'works': '',
'workshop': '',
'world': '',
'worldwide': '',
'worldwide': '',
'worried': '',
'worry': '',
'worth': '',
'worth': '',
'would': '',
'wound': '',
'wow': '',
'wrist': '',
'writer': '',
'writing': '',
'written': '',
'wrong': '',

// Y- \\
'yard': '',
'year': '',
'yellow': '',
'yes': '',
'yesterday': 'yesterɗy',
'yet': '',
'yield': '',
'you': '',
'young': '',
'youngster': '',
'your': 'ur',
'yours': '',
'yourself': '',
'youth': '',

// Z-\
'zone': '',

}

const txt_body = document.getElementById('txt_body');
const p_block = document.getElementById('p_block');
const p_txt = document.getElementById('p_txt');
const p_boustrophedon = document.getElementById('p_boustrophedon');

// const txt = 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz'
// // line-length: 93 characters.
// // p_block limit: 93 characters.
// console.log(txt.length)

// If a text length is 93, split it. At every other
// line thou shall transform in boustrophedon.

function transformBoustrophedon(txt) {
  let original_array = txt.split(" ").reverse();

  const result = original_array.join('&#32;');

  const words = result.split("&#32;")
  // const words = original_array
  for(let i = 0; i < words.length; i++) {

    for(let j = 0; j < words[i].length; j++) {
      if ((words[i][j]) == ".") {
        // slice the punctuation and place the same punctuaction at the beginning
        const punctuaction = words[i].slice(0, j)
        // place at the beginning
        words[i] = `.${punctuaction}`
        // console.log(words)
      } else if ((words[i][j]) == ",") {
        const punctuaction = words[i].slice(0, j)
        words[i] = `,${punctuaction}`
      } else if ((words[i][j]) == "?") {
        const punctuaction = words[i].slice(0, j)
        words[i] = `?${punctuaction}`
      }
    }

  }

  // console.log(words)

  const resultado = words.join('&#32;');

  return resultado;
}


const text = `
Introduction

This book is not about why gamification is amazing. It is not about how gamification is the future and how inspiring life could be with it. It is not necessarily for the late adopters who are simply curious about what gamification is. It also does not focus on what the gamification industry is doing as a whole, especially when that is continuously changing every month. Rather, this book is about implementing good gamification design into your products, workplace, and lifestyle.

It is a deep exploration into what makes a game fun and how to apply those fun and engaging elements in real-life productive activities. It is about how you can use gamification and scientifically proven methods to improve your company, your life, and the lives of those around you.

Effective gamification is a combination of game design, game dynamics, behavioral economics, motivational psychology, UX/UI (User Experience and User Interface), neurobiology, technology platforms, as well as ROI-driving business implementations. This book explores the interplay between these disciplines to capture the core principles that contribute to good gamification design. I will be sharing my observations in multiple industries and sectors based on my 12-year journey of passionately and relentlessly pursuing the craft of Gamification.

Chapters in this book tend to build on previous chapters, so skipping around is not suggested. That said, if you have been an avid reader of my work and viewer of my videos, you might already have a firm grasp of the 8 Core Drives within the Octalysis Framework. In that case, feel free to skip to a section that you want to home in on.

If you are extremely busy and aren’t sure if you want to commit to this book, I recommend starting off with Chapters 3, 5, 10, 14, and 15 to decide whether you would like to read the entire book.

Within the book, there will be many everyday scenarios to illustrate the potential of these Core Drives and the flexibility of their applications beyond traditional “gamification” examples. I myself still constantly gain new insights and revelations when I reflect and speculate upon the various possibilities contained in the 8 Core Drives. I hope you do too.

As this book is titled “Actionable Gamification,” my goal is for it to become a strategy guide in helping my readers master the games that truly make a difference in their lives. If you absorb the contents of this book, you will have literally obtained what many companies pay tens of thousands of dollars to acquire.

My ultimate aim is to enable the widespread adoption of good gamification and human-focused design in all types of industries. I care deeply about creating a world that is sustainably more enjoyable and productive. In that world, there no longer will be a great divide between what people have to do and what they want to do - our lives become better as we spend time enjoying everything we do.

I’m excited for you to dive into the contents of this book so that we can start to build a world that harnesses the power of play together . Let’s begin.

Yu-kai Chou (Written February 14th 2014)
`

const str = formatting(text)

// cut the str at the 93th character before a whitespace
// const result = str.match(/.{1,93}/gs) ?? [];
const result = str.match(/.{1,93}\s/g) ?? [];



function formatting(text) {
  const words = text.split(" ")

  for (let word of  words) {
    if(abbreviation.hasOwnProperty(word)) words[words.indexOf(word)] = abbreviation[word] //`<span class="abbreviation">${abbreviation[word]}</span>`
  }

  return words.join(" ")
}


function b(arr) {
  const newArr = arr;
  for(let i = 1; i < newArr.length; i += 2) {
    newArr[i] = '<span class="boustrophedon">' + transformBoustrophedon(newArr[i]) + '</span>';
  }

  return newArr;
}

p_block.innerHTML = b(result).join("<br>");