const abbreviation = {
      // ·ment = mt 
  // ing = ng
  // cal = al
  'for': 'f·',
  'you': 'u',
  'your': 'ur',
  'yours': '·urs',
  'with': 'w/',
  'without': 'w/out',
  'whatever': 'w/e',
  'what': 'w·t',
  'want': 'w·nt',
  'will': 'w·l',
  'well': 'we·l',
  'would': 'w·ld',
  'when': 'wh·n',
  'whenever': 'wh·n·v·r',
  'have': 'hv',
  'having': 'hv·ng',
  'here': 'h·r·',
  'know': 'k·w',
  'knowledge': 'k·w·dg·',
  'just': 'j·st',
  'unlike': 'unl·k·',
  'unlikely': 'unl·k·ly',
  'much': 'm·h',
  'very': 'v·',
  'back': 'b·k',
  'should': 'sh·ld',
  'really': 'r·ly',
  'right': 'r·t',
  'rights': 'r·ts',
  'feel': 'f·l',
  'great': 'gr·t',
  'keep': 'k·p',
  'keeps': 'k·ps',
  'keeping': 'k·p·ng',
  'happen': 'h·p·n',
  'still': 's·l',
  'last': 'l·t',
  'over': '·v·r',
  'overall': '·v·r·l',
  'recovery': 'r·c·ry',
  'overcome': '·v·r·c·m·',
  'week': 'w·k',
  'question': 'qstn', 'questions': 'qstn·s',
  'read': 'r·d',
  'seem': 'se·m',
  'though': 't·gh',
  'family': 'fml',
  'maybe': 'myb',
  '': '',
  '': '',
  '': '',
  // A- \\
  'actually': 'act·ly',
  'always': 'al·ys',
  'away': 'a·y',
  'about': 'ab·t',
  'acknowledge': 'ack·w·dg·',
  'attitude': 'at·tude', 'attitudes': 'at·tudes',
  'advantage': 'advtg', 'advantages': 'advtgs',
  'accelerate': 'aclrt',
  'alike': 'al·k·',
  'adjective': 'adj·',
  'academic': 'acad·',
  'account': 'acct·',
  'accountant': 'acct·ant',
  'accounting': 'acct·ng',
  'accommodation': 'accomm·',
  'administration': 'adm·tion',
  'administrator': 'adm·',
  'administrative': 'admin·',
  'agriculture': 'agric·',
  'agricultural': 'agric·al',
  'alternative': 'alt·',
  'association': 'assoc·',
  'associate': 'asoc·te', 'associates': 'asoc·tes',
  'authentication': 'auth·',
  'authenticate': 'auth·cate', 'authenticates': 'auth·s',
  'authority': 'autho·', 'authorities': 'autho·s',
  'argument': 'arg·', 'arguments': 'arg·s',
  'assumption': 'asmptn', 'assumptions': 'asmptns',
  'avenue': 'ave·',
  'answer': 'nwr', 'answers': 'nwrs',
  // B- \\
  'before': 'b4',
  'between': 'btwn',
  'become': 'bcm', 'becomes': 'bcms',
  'bring': 'brg', 'brings': 'brgs',
  'believe': 'blv', 'believes': 'blvs',
  'behave': 'bhv', 'behaves': 'bhv·es',
  'behavior': 'bhvr', 'behaviors': 'bhvrs',
  'behaving': 'bhv·ng', 'behavings': 'bhv·ngs',
  'business': 'biz',
  'bankruptcy': 'bankr·',
  'brotherhood': 'bhd·',
  'brother': 'bro·',
  'brothers': 'bro·s',
  'build': 'bld',
  'building': 'bldng',
  'bathroom': 'bthrom',
  'bedroom': '🛏️ro·m',
  'background': 'b·g·d',
  'boyfriend': 'boyfr·d',
  'bureaucracy': 'b·cracy',
  // C- \\
  'could': 'c·ld',
  'call': 'c·l',
  'called': 'c·led',
  'country': 'c·try',
  'create': 'crte', 'creates': 'crtes',
  'complete': 'cmplt', 'completes': 'cmplts',
  'cover': 'c·v·r',
  'coverage': 'c·v·r·g',
  'change': 'c·nge', 'changes': 'c·nges',
  'concept': 'cncpt', 'concepts': 'cncpts',
  'compete': 'cmpt', 'competes': 'cmpts',
  'competition': 'cmpt·tion', 'comptetitions': 'cmpt·tions',
  'competitor': 'cmptitor', 'competitors': 'cmptitors',
  'commitment': 'comtmt', 'commitments': 'cmtmts',
  'commit': 'comt', 'commits': 'comts',
  'committing': 'comt·ng',
  'compare': 'cmpr', 'compares': 'cmprs',
  'customer': 'cstmr', 'customers': 'cstmrs',
  'character': 'char·',
  'check': 'ch·k',
  'company': 'com·', 'companies': 'com·ies',
  'corporate': 'corp·',
  'corporation': 'corp·on', 'corporations': 'corp·ons',
  'capital': 'cap·t·',
  'catholic': 'cath·',
  'center': 'ctr',
  'centre': 'ctr',
  'central': 'ctr·al',
  'centralized': 'ctr·zed',
  'chemistry': 'chem·',
  'chemical': 'chem·al',
  'college': 'coll·',
  'clothes': 'cl·th·s',
  'clothing': 'cl·th·ng',
  'commerce': 'com·r·c',
  'commercial': 'com·r·cial',
  'community': 'c·m·ty',
  'compensation': 'comp·',
  'condominium': 'condo·',
  'consolidated': 'consol·',
  'construction': 'constr·',
  'contract': 'cont·',
  'cooperative': 'coop·',
  'correction': 'corr·',
  'contamination': 'contam·',
  'classroom': 'cl·ro·m',
  'class': 'cl·',
  'classic': 'cl·ic',
  'courtroom': 'courtro·m',
  'careful': 'crful',
  'carefully': 'crfuly',
  // D- \\
  'during': 'd·r·ng',
  'drive': 'drv', 'drives': 'drvs',
  'driving': 'drv·ng', 'drivings': 'drv·ngs',
  'decrease': 'dcrs', 'decreases': 'dcrs·s',
  'decreased': 'dcrs·ed',
  'database': 'DB', 'databases': 'DBS',
  'danger': 'dngr', 'dangers': 'dngrs',
  'dangerous': 'dngrous',
  'damage': 'dmg', 'damages': 'dmgs',
  'damaging': 'dmg·ng', 'damagings': 'dmg·ngs',
  'discover': 'd·c·v·r',
  'discovery': 'd·c·v·ry',
  'detail': 'd·t·l',
  'details': 'd·t·ls',
  'detailed': 'd·t·led',
  'defense': 'def·',
  'defend': 'def·nd',
  'defender': 'def·der',
  'definition': 'defi·',
  'department': 'dep·mt',
  'detention': 'det·',
  'digital': 'digi·',
  'direction': 'dir',
  'director': 'direc·',
  'distribution': 'dist·',
  'distributing': 'dist·ng',
  'distributor': 'dist·tor', 'distributors': 'dist·tors',
  'division': 'div·', 'divisions': 'div·s',
  'document': 'doc·', 'documents': 'doc·s',
  'doctor': 'Dr', 'doctors': 'drs',
  'development': 'devmt', 'developmets': 'devmts',
  'developer': 'devr', 'developers': 'devrs',
  'delete': 'del',
  // E- \\
  'enough': 'engh',
  'extreme': 'xtrm', 'extremes': 'xtrms',
  'extremely': 'xtrm·ly',
  'especially': 'spcly',
  'easy': 'esy',
  'email': 'em·l',
  'example': 'exmp·', 'examples': 'exmp·s',
  'economy': 'econ·',
  'economic': 'econ·ic', 'economics': 'eco·ics',
  'economical': 'econ·cal',
  'electric': 'elec·',
  'electrical': 'elec·ical',
  'electricity': 'elec·ity',
  'engine': 'eng·',
  'engineering': 'eng·ng',
  'engineer': 'eng·er', 'engineers': 'eng·ers',
  'entertainment': 'ent·mt',
  'environment': 'env·mt',
  'equipment': 'equip·', 'equipments': 'equip·s',
  'exchange': 'exch·',
  'exercise': 'xrcse', 'exercises': 'xrcses',
  'execution': 'exec·',
  'executive': 'exec·ve', 'executives': 'exec·ves',
  'element': 'elem·', 'elements': 'elem·s',
  'explore': 'expl·', 'explores': 'expl·s',
  'exploration': 'expl·t·n', 'explorations': 'expl·t·ns',
  'employ': 'emp·', 'employs': 'emp·s',
  'employee': 'emp·ee', 'employees': 'emp·ees',
  'employer': 'emp·er', 'employers': 'emp·ers',
  'entrepreneur': 'entrep·', 'entrepreneurs': 'entrep·s',
  'entrepreneurship': 'entrep·ship',
  'entrepreneurial': 'entrep·rial',
  'example': 'ex·',
  'experiment': 'xprmnt', 'experiments': 'xprmnts',
  'experimentation': 'xprmnt·on',
  'experimental': 'xprmnt·al',
  'experience': '·xp·',
  'expense': 'exp·',
  // F- \\
  'feature': 'ftr', 'features': 'ftrs', 
  'feedback': 'fdbk', 'feedbacks': 'fdbks',
  'fact': 'fct', 'facts': 'fcts',
  'first': '1st',
  'federal': 'fed·', 'federals': 'fed·s',
  'federation': 'fed·tion', 'federations': 'fed·s',
  'finance': 'fin·', 'finances': 'fin·s',
  'financed': 'fin·ed',
  'financing': 'fin·ng',
  'financial': 'fin·ial', 'financials': 'fin·als',
  'foundation': 'foun·tion', 'foundations': 'foun·tions',
  'functional': 'func·al', 'functionals': 'func·als',
  'functionality': 'func·ity', 'functinalities': 'func·ities',
  'friend': 'fr·d', 'friends': 'fr·ds',
  'friendly': 'fr·dly',
  'function': 'func·', 'functions': 'func·s',
  'friendship': 'fr·dship', 'friendships': 'fr·dships',
  // G- \\
  'general': 'gen·', 'generals': 'gen·s',
  'global': 'glob·',
  'government': 'gov·', 'governments': 'gov·s',
  'group': 'gr·p', 'groups': 'gr·ps',
  'girlfriend': 'girlfr·d',
  // I- \\
  'improve': 'imprv', 'improves': 'imprvs',
  'improving': 'imprv·ng', 'improvings': 'imprv·ngs',
  'increase': 'incrs', 'increases': 'incrs·s',
  'increased': 'incrs·ed',
  'interest': 'intrst',
  'interesting': 'intrst·ng',
  'interested': 'intrsted',
  'image': 'img', 'images': 'imgs',
  'innovate': 'inno·te',
  'innovation': 'inno·tion', 'innovations': 'inno·tion·s',
  'innovative': 'inno·ve',
  'immigration': 'immigr·',
  'incorporated' : 'inc·',
  'information': 'info·',
  'injury': 'inj·',
  'index': 'ind·',
  'industry': 'indus·',
  'interest': 'int·st',
  'invest': 'inv·',
  'investment': 'inv·nt',
  'investor': 'inv·tor', 'investors': 'inv·tors',
  'important': 'mptnt', 'importants': 'mptnts',
  // L- \\
  'look': 'lok', 'looks': 'loks',
  'likelyhood': 'l·k·lyh·d',
  'likewise': 'l·k·w·s·',
  'leave': 'l·ve', 'leaves': 'l·ves',
  'leaving': 'l·ving',
  'like': 'lk', 'likes': 'lk·s',
  'likely': 'lk·ly',
  'liking': 'lk·ng',
  'liked': 'lk·ed',
  'language': 'lang·', 'languages': 'lang·s',
  'laboratory': 'lab·',
  'laboratories': 'lab·s',
  'liability': 'liab·',
  'limited': 'l·t·d',
  'litigation': 'litig·',
  'large': 'l·g·',
  'little': 'lil',
  'learn': 'lrn',
  'learning': 'lrn·ng',
  'learned': 'lrn·ed',
  // M- \\
  'measure': 'msr', 'measures': 'msrs',
  'measuring': 'msr·ng', 'measurings': 'msr·ngs',
  'meet': 'mt', 'meets': 'mts',
  'meeting': 'mt·ng', 'meetings': 'mt·ngs',
  'method': 'mthd', 'methods': 'mthds',
  'matter': 'mtr', 'matters': 'mtrs',
  'make': 'mk', 'makes': 'mks',
  'making': 'mk·ng',
  'manage': 'mng', 'manages': 'mngs',
  'manager': 'mngr', 'managers': 'mngrs',
  'management': 'mng·mt',
  'managing': 'mng·ng',
  'mean': 'mn',
  'machine': 'mach·',
  'machines': 'mach·s',
  'maintenance': 'maint·  ',
  'manufacture': 'manuf·',
  'manufacturing': 'manuf·ng',
  'manufacturer': 'manuf·er',
  'market': 'mkt',
  'marketing': 'mkt·ng',
  'mechanic': 'mech·',
  'mechanical': 'mech·al',
  'medicine': 'med·',
  'merchant': 'merch·',
  'mortgage': 'mortg·',
  'mutual': 'mut·',
  'minute': 'minu·',
  'minutes': 'minu·s',
  'medium': 'm·d·',
  'millisecond': 'millisec·', 'milliseconds': 'millisec·s',
  'message': 'msg', 'messages': 'msgs',
  'messaging': 'msg·ng', 'messagings': 'msg·ngs',
  // N- \\
  'need': 'n·d',
  'needs': 'n·ds',
  'needed': 'n·ded',
  'needing': 'n·d·ng',
  'national': 'natio·',
  'natural': 'nat·',
  'necessary': 'n·c·s·ry',
  'necessarily': 'n·c·s·ly',
  'necessitate': 'n·c·state',
  'negative': 'ngtv', 'negatives': 'ngtvs',
  // O- \\
  'official': 'off·',
  'officially': 'off·ly',
  'opinion': 'opi·',
  'order': 'ord·',
  'organization': 'org·', 'organizations': 'org·s',
  'opportunity': 'op·tu·ty',
  // P- \\
  'perform': 'prfrm', 'performs': 'prfrms',
  'performance': 'prfrm·ce', 'performances': 'prfrm·ces',
  'provide': 'prvd', 'provides': 'prvd·s',
  'program': 'pr·g·m', 'programs': 'pr·g·ms',
  'president': 'pr·s·d·t',
  'partnership': 'p·ship',
  'person': 'pers·',
  'people': 'p·p·l·',
  'personal': 'pers·al',
  'politic': 'pol·', 'politics': 'pol·s',
  'political': 'pol·al',
  'probability': 'probab·',
  'probabilities': 'probab·s',
  'power': 'pwr',
  'production': 'prod·tion',
  'profession': 'profe·',
  'professional': 'profe·al',
  'property': 'prop·',
  'protection': 'prot·', 'protections': 'prot·s',
  'public': 'pub·',
  'publication': 'pub·tion', 'publications': 'pub·tions',
  'publishing': 'pub·shing',
  'psychology': 'psyc·gy',
  'psychological': 'psyc·cal',
  'psychologist': 'psyc·st',
  'progress': 'prog·',
  'progressive': 'prog·ve',
  'progressed': 'prog·ed',
  'problem': 'prob·', 'problems': 'prob·s',
  'prerequisite': 'prereq·', 'prerequisites': 'prereq·s',
  'prefer': 'pfr', 'prefers': 'pfrs',
  'preferred': 'pfr·ed',
  'preference': 'pfrnc', 'preferences': 'pfrncs',
  // R- \\
  'random': 'rndm',
  'recent': 'rcnt', 'recents': 'rcnts',
  'recently': 'rcntly',
  'result': 'rslt', 'results': 'rslts',
  'reason': 'rsn', 'reasons': 'rsns',
  'room': 'ro·m', 'rooms': 'ro·ms',
  'retirement': 'ret·',
  'search': 'srch', 'searches': 'srchs',
  'research': 'r·s·ch·', 'researchs': 'rschs',
  'reproduction': 'reprod·',
  'rehabilitation': 'rehab·',
  'regional': 'regi·al',
  'refining': 'ref·ng',
  'remember': 'remeb·', 'remembers': 'remeb·s',
  'record': 'reco·', 'records': 'reco·s',
  'recording': 'reco·ng', 'recordings': 'reco·ngs',
  'refine': 'ref·', 'refines': 'ref·s',
  'region': 'regi·', 'regions': 'regi·s',
  'register': 'reg·', 'registers': 'reg·s',
  'regulation': 'regul·', 'regulations': 'regul·s',
  'relation': 'rel·', 'relations': 'rel·s',
  'relationship': 'rel·ship', 'relationships': 'rel·ships',
  'resource': 'res·', 'resources': 'res·s',
  'restaurant': 'resta·', 'restaurants': 'resta·s',
  'road': 'r·d', 'roads': 'r·ds',
  'require': 'req·', 'requires': 'req·s',
  'required': 'req·ed',
  'requisite': 'req·s·t', 'requisites': 'req·s·t·s',
  'recipe': 'rcp', 'recipes': 'rcps',
  // S- \\
  'state': 'st·e',
  'start': 'st·t', 'starts': 'st·ts',
  'starting': 'st·tng',
  'started': 'st·ted',
  'some': 's·m·',
  'standard': 'stndrd', 'standards': 'stndrd·s',
  'separate': 'sprt', 'separates': 'sprts',
  'separating': 'sprt·ng', 'separatings': 'sprt·ngs',
  'success': 'scs',
  'successful': 'scsfl',
  'startup': 'st·tup', 'startups': 'st·tups',
  'straight': 'str8',
  'social': 'soc·',
  'scientific': 'sci·fic',
  'superpower': 's·p·r·p·w·r', 'superpowers': 's·p·r·p·w·rs',
  'school': 'sch·', 'schools': 'sch·s',
  'science': 'sci·', 'sciences': 'sci·s',
  'security': 'sec·', 'securities': 'sec·s',
  'service': 'serv·', 'services': 'serv·s',
  'shareholder': 's·holder', 'shareholders': 's·holders',
  'solution': 'sol·', 'solutions': 'sol·s',
  'street': 'st·', 'streets': 'st·s',
  'system': 'sys·', 'systems': 'sys·s',
  'second': 'sec·', 'seconds': 'sec·s',
  'serious': 's·r·s',
  'seriosly': 's·r·s·l·y',
  'shopping': 'shpng',
  'significant': 'signi·',
  // T- \\
  'they': 't·y',
  'their': 't·r',
  'these': 't·se',
  'time': 't·m·',
  'there': 't·re',
  'thereby': 't·reby',
  'them': 'th·m',
  'themselves': 'thmslvs',
  'think': 't·nk',
  'thinking': 't·nk·ng',
  'take': 't·k·',
  'through': 't·gh',
  'test': 'tst', 'tests': 'tst·s',
  'testing': 'tst·ng', 'testings': 'tst·ngs',
  'tomorrow': 't·m·r·w',
  'temporary': 'temp·',
  'teacher': 't·ch·r', 'teachers': 't·ch·rs',
  'telephone': 'tel·', 'telephones': 'tel·s',
  'technology': 'tech·', 'technologies': 'tech·s',
  'traditional': 'trad·',
  'three': 'thre',
  // U- \\
  'under': 'ndr',
  'understand': 'ndr·td',
  'uniform': 'unif·',
  'university': 'univ·',
  'utility': 'util·',
  // V- \\
  'validate': 'valdt', 'validate': 'valdts',
  'village': 'vill·',
  // W- \\
  'wisdom': 'wsdm',
  'wait': 'w8',
}

const test = "Test successful!"

export { test }